//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDDebug, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>, NSString;

@interface CDDXPCConnection : NSObject
{
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_dispatch_queue> *_connectionQueue;
    NSObject<OS_dispatch_queue> *_replyQueue;
    BOOL _hasValidConnection;
    long long _sequenceNumber;
    NSString *_serviceName;
    CDDebug *_debug;
}

- (unsigned long long)sequenceNumber;
- (void)sendBarrier:(CDUnknownBlockType)arg1;
- (void)invalidateConnection;
- (void)cancelConnection;
- (id)makeStashWithId:(unsigned long long)arg1;
- (BOOL)sendMessageAsync:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (id)initWithMachServiceName:(id)arg1 dispatchQueue:(id)arg2;
@property(readonly) NSString *serviceName; // @synthesize serviceName=_serviceName;
- (id)connection;
- (void).cxx_destruct;
- (void)dealloc;
- (BOOL)establishConnection;
@property(readonly) CDDebug *debug; // @synthesize debug=_debug;

@end

