//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"
#import "NSURLSessionDownloadDelegate.h"

@class ACAccount, ACAccountStore, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString, NSURL, NSURLSession, NSURLSessionConfiguration, PKPaymentDevice, PKPaymentWebServiceBackgroundContext, PKPaymentWebServiceContext;

@interface PKPaymentWebService : NSObject <NSURLSessionDelegate, NSURLSessionDownloadDelegate>
{
    NSURLSession *_urlSession;
    NSURLSession *_backgroundSession;
    ACAccountStore *_accountStore;
    PKPaymentDevice *_paymentDevice;
    NSMutableDictionary *_passesByLocalURL;
    NSOperationQueue *_delegateOperationQueue;
    NSObject<OS_dispatch_queue> *_backgroundDownloadQueue;
    BOOL _sharedService;
    PKPaymentWebServiceContext *_context;
    PKPaymentWebServiceBackgroundContext *_backgroundContext;
    id <PKPaymentProvisioningServiceDelegate> _delegate;
    id <PKPaymentBackgroundProvisioningServiceDelegate> _backgroundDelegate;
    unsigned int _maxCards;
}

+ (id)sharedService;
+ (id)_sharedCookieStorage;
+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL sharedService; // @synthesize sharedService=_sharedService;
- (id)_accountStore;
@property(nonatomic) unsigned int maxCards; // @synthesize maxCards=_maxCards;
@property id <PKPaymentBackgroundProvisioningServiceDelegate> backgroundDelegate; // @synthesize backgroundDelegate=_backgroundDelegate;
@property(retain) PKPaymentWebServiceBackgroundContext *backgroundContext; // @synthesize backgroundContext=_backgroundContext;
- (void)rewrapInAppPayment:(id)arg1 merchantIdentifier:(id)arg2 applicationData:(id)arg3 pass:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)inAppPaymentNonceForPass:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)backgroundDownloadWithPassTypeIdentifier:(id)arg1 serialNumber:(id)arg2;
- (void)backgroundDownloadRemotePassAssets:(id)arg1;
- (void)userPassesWithCompletion:(CDUnknownBlockType)arg1;
- (void)backgroundDownloadPassesSinceLastUpdatedTag:(BOOL)arg1;
- (void)devicePassesSinceLastUpdatedTag:(BOOL)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)submitVerificationCode:(id)arg1 verificationData:(id)arg2 forPass:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)requestVerificationCodeForPass:(id)arg1 usingChannel:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)verificationChannelsForPass:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)provisionCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unregisterDeviceWithCompletion:(CDUnknownBlockType)arg1;
- (void)invalidateBackgroundSession;
- (void)startBackgroundURLSessionWithIdentifier:(id)arg1 context:(id)arg2 backgroundDelegate:(id)arg3;
- (id)initWithContext:(id)arg1 delegate:(id)arg2;
- (void)sharedServiceDidRegister;
- (id)_downloadCacheLocation;
- (id)_errorUserInfoWithErrorCode:(int)arg1;
- (id)_errorUserInfoWithData:(id)arg1;
- (int)_resultForUnexpectedStatusCode:(int)arg1;
- (void)passAtURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)backgroundDownloadPassAtURL:(id)arg1;
- (void)_handleRetryAfterTSMSyncForPushTopic:(id)arg1 withRequest:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_handleRetryAfterRegisterWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)_passWithFileURL:(id)arg1;
- (void)_handlePassDownloadTask:(id)arg1 data:(id)arg2;
- (void)_handlePassListDownloadTask:(id)arg1 data:(id)arg2;
- (void)_handleRemoteAssetDownloadTask:(id)arg1 data:(id)arg2;
- (BOOL)_trustPassesExtendedValidation:(struct __SecTrust *)arg1;
- (id)_reencryptPayload:(id)arg1 forRegion:(id)arg2;
- (id)_paymentDevice;
- (void)_passWithData:(id)arg1 response:(id)arg2 error:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)_movePassToDownloadCache:(id)arg1;
- (void)backgroundDownloadRemotePassAssets:(id)arg1 forSuffixesAndScreenScales:(id)arg2;
- (void)_archiveBackgroundContext;
- (void)backgroundDownloadPassesForPushTopic:(id)arg1 sinceLastUpdatedTag:(BOOL)arg2;
- (id)_downloadPassesWithURLs:(id)arg1;
- (void)passWithPassTypeIdentifier:(id)arg1 serialNumber:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)_addVerificationRequestRecordForChannel:(id)arg1 pass:(id)arg2;
- (id)_fakeVerificationChannelsWithRealChannels:(id)arg1;
- (void)_deviceProvisioningDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)_downloadPassAtURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_provisionCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_deviceRegistrationDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)_performRequest:(id)arg1 retries:(unsigned int)arg2 authHandling:(BOOL)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)_handleAuthenticationFailureWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_didRegisterWithRegionMap:(id)arg1;
- (void)registerDeviceAtBrokerURL:(id)arg1 withConsistencyData:(id)arg2 retries:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
@property(readonly) NSURL *primaryBrokerURL;
- (void)registerDeviceWithConsistencyData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_deviceConfigurationDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)_performRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_archiveContext;
- (id)_errorWithResult:(int)arg1 data:(id)arg2;
- (int)_resultForResponse:(id)arg1 error:(id)arg2 successHandler:(CDUnknownBlockType)arg3;
- (void)_cleanupPassDownloadCache;
- (BOOL)_canBypassTrustExtendedValidation;
- (void)sharedPaymentServiceChanged:(id)arg1;
- (id)paymentServicesURL;
- (void)eligibilityForPaymentCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)remotePaymentCredentialsWithCompletion:(CDUnknownBlockType)arg1;
- (void)registerDeviceWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly) BOOL needsRegistration;
- (void)configurePaymentServiceWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly) int paymentSetupSupportedInRegion;
@property(readonly) BOOL needsConfiguration;
@property(readonly) NSURLSessionConfiguration *sessionConfiguration;
@property(readonly) ACAccount *account;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (id)initWithContext:(id)arg1;
@property(retain) PKPaymentWebServiceContext *context; // @synthesize context=_context;
@property id <PKPaymentProvisioningServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

