//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AppLaunchStatsStateHandler : NSObject
{
    CDUnknownBlockType budgetHandler;
    CDUnknownBlockType forecastHandler;
    CDUnknownBlockType messageStatusHandler;
    CDUnknownBlockType queryHandler;
    CDUnknownBlockType scoreHandler;
    CDUnknownBlockType trendHandler;
    CDUnknownBlockType olderHandler;
    CDUnknownBlockType noprewarmHandler;
}

@property(copy) CDUnknownBlockType queryHandler; // @synthesize queryHandler;
@property(copy) CDUnknownBlockType noprewarmHandler; // @synthesize noprewarmHandler;
@property(copy) CDUnknownBlockType olderHandler; // @synthesize olderHandler;
@property(copy) CDUnknownBlockType trendHandler; // @synthesize trendHandler;
@property(copy) CDUnknownBlockType scoreHandler; // @synthesize scoreHandler;
@property(copy) CDUnknownBlockType messageStatusHandler; // @synthesize messageStatusHandler;
@property(copy) CDUnknownBlockType forecastHandler; // @synthesize forecastHandler;
@property(copy) CDUnknownBlockType budgetHandler; // @synthesize budgetHandler;
- (void).cxx_destruct;
- (id)init;

@end

