//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface HistogramElement : NSObject <NSCoding>
{
    NSString *stringkey;
    double probability;
    unsigned long long count;
    unsigned long long queryID;
}

@property(nonatomic) unsigned long long queryID; // @synthesize queryID;
@property(nonatomic) double probability; // @synthesize probability;
@property(retain, nonatomic) NSString *stringkey; // @synthesize stringkey;
- (id)initWithString:(id)arg1 withCount:(unsigned long long)arg2 withQueryID:(unsigned long long)arg3;
- (id)initWithString:(id)arg1 withProbability:(double)arg2 withQueryID:(unsigned long long)arg3;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long count; // @synthesize count;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

