//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface PBBProtoPerformanceResult : PBCodable <NSCopying>
{
    double _timeDelta;
    double _timeEnded;
    double _timeStarted;
    NSString *_activityType;
    NSString *_identifier;
    struct {
        unsigned int timeDelta:1;
        unsigned int timeEnded:1;
        unsigned int timeStarted:1;
    } _has;
}

@property(retain, nonatomic) NSString *activityType; // @synthesize activityType=_activityType;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) BOOL hasTimeEnded;
@property(nonatomic) BOOL hasTimeStarted;
@property(nonatomic) BOOL hasTimeDelta;
@property(readonly, nonatomic) BOOL hasActivityType;
@property(nonatomic) double timeEnded; // @synthesize timeEnded=_timeEnded;
@property(nonatomic) double timeStarted; // @synthesize timeStarted=_timeStarted;
@property(nonatomic) double timeDelta; // @synthesize timeDelta=_timeDelta;
@property(readonly, nonatomic) BOOL hasIdentifier;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

