//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TKVibrationRecorderTouchSurfaceRecordedDataWrapper : NSObject
{
    BOOL _warmUpModeEnabled;
    BOOL _displayLinkHasRefreshedAtLeastOnce;
    unsigned int _maximumFramesPerSecondRate;
    void *_recordedData;
    unsigned long _recordedDataElementsCount;
    unsigned long _recordedDataCursor;
    double _vibrationPatternMaximumDuration;
    double _vibrationPatternDidStartTimestamp;
    double _warmUpModeDidStartTimestamp;
}

@property(nonatomic, setter=_setDisplayLinkHasRefreshedAtLeastOnce:) BOOL _displayLinkHasRefreshedAtLeastOnce; // @synthesize _displayLinkHasRefreshedAtLeastOnce;
@property(nonatomic, setter=_setWarmUpModeDidStartTimestamp:) double _warmUpModeDidStartTimestamp; // @synthesize _warmUpModeDidStartTimestamp;
@property(nonatomic, setter=_setVibrationPatternDidStartTimestamp:) double _vibrationPatternDidStartTimestamp; // @synthesize _vibrationPatternDidStartTimestamp;
- (void)_recordFinalDataWithNormalizedTouchLocation:(struct CGPoint)arg1 touchPhase:(int)arg2 timeIntervalSinceBeginningOfPattern:(double)arg3;
- (void)_prepareRecordedDataBufferForStoringEnoughElementsForRecordingDuration:(double)arg1;
@property(nonatomic, setter=_setRecordedDataCursor:) unsigned long _recordedDataCursor; // @synthesize _recordedDataCursor;
@property(nonatomic, setter=_setRecordedDataElementsCount:) unsigned long _recordedDataElementsCount; // @synthesize _recordedDataElementsCount;
@property(nonatomic, setter=_setRecordedData:) void *_recordedData; // @synthesize _recordedData;
@property(nonatomic, setter=_setMaximumFramesPerSecondRate:) unsigned int _maximumFramesPerSecondRate; // @synthesize _maximumFramesPerSecondRate;
- (void)_updateMaximumFramesPerSecondRate:(id)arg1;
@property(nonatomic, getter=_isWarmUpModeEnabled, setter=_setWarmUpModeEnabled:) BOOL _warmUpModeEnabled; // @synthesize _warmUpModeEnabled;
- (BOOL)getNormalizedTouchLocation:(struct CGPoint *)arg1 touchPhase:(int *)arg2 forTimeInterval:(double)arg3;
- (void)recordNormalizedTouchLocation:(struct CGPoint)arg1 touchPhase:(int)arg2;
- (void)didStopRecording;
@property(nonatomic, setter=_setVibrationPatternMaximumDuration:) double _vibrationPatternMaximumDuration; // @synthesize _vibrationPatternMaximumDuration;
- (id)initWithVibrationPatternMaximumDuration:(double)arg1;
- (void)dealloc;

@end

