//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iTunesStoreUI/SUStorePageViewController.h>

@class NSString, SUMescalSession;

@interface SUAccountViewController : SUStorePageViewController
{
    BOOL _failed;
    int _style;
    SUMescalSession *_mescalSession;
    int _mescalState;
    NSString *_primingSignature;
}

+ (id)_latestAccountViewController;
- (void)_closeMescalSession;
- (id)_authenticationQueryParametersForStyle:(int)arg1;
- (void)_mescalDidOpenWithSession:(id)arg1 error:(id)arg2;
- (id)_bagKeyForStyle:(int)arg1;
@property(readonly, nonatomic, getter=_mescalSession) SUMescalSession *_mescalSession; // @synthesize _mescalSession;
- (void)enqueueFetchOperation;
- (id)newViewControllerForPage:(id)arg1 ofType:(int)arg2 returningError:(id *)arg3;
- (id)newFetchOperation;
- (id)copyArchivableContext;
- (void)_forceOrientationBackToSupportedOrientation;
- (id)initWithExternalAccountURL:(id)arg1;
- (void)handleFailureWithError:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
@property(nonatomic) int style; // @synthesize style=_style;
- (id)init;
- (void)dealloc;

@end

