//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SUCellConfigurationCache : NSObject
{
    id _cellContext;
    NSMutableArray *_configurations;
}

- (id)initWithClass:(Class)arg1 tableHeight:(float)arg2;
@property(retain, nonatomic) id cellContext; // @synthesize cellContext=_cellContext;
- (id)configurationForRow:(unsigned int)arg1;
- (void)resetLayoutCaches;
- (void)reset;
- (void)dealloc;

@end

