//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iTunesStoreUI/SUScriptObject.h>

@class NSURL, SLRequest, SUScriptAppleAccount;

@interface SUScriptFacebookRequest : SUScriptObject
{
    SLRequest *_request;
    int _requestMethod;
    SUScriptAppleAccount *_scriptAccount;
    NSURL *_url;
}

+ (id)webScriptNameForKeyName:(id)arg1;
+ (id)webScriptNameForSelector:(SEL)arg1;
+ (void)initialize;
@property(readonly) int requestMethod;
- (id)initWithURL:(id)arg1 requestMethod:(id)arg2;
- (void)performRequestWithFunction:(id)arg1;
- (void)addParameterWithKey:(id)arg1 value:(id)arg2;
- (void)addMultiPartData:(id)arg1 withName:(id)arg2 type:(id)arg3;
- (void)_performRequest:(id)arg1 withScriptFunction:(id)arg2;
- (BOOL)_isRequestAllowed:(id *)arg1;
@property(readonly) int requestMethodDelete;
@property(readonly) int requestMethodPost;
@property(readonly) int requestMethodGet;
- (id)attributeKeys;
- (id)_className;
- (id)scriptAttributeKeys;
- (void)setParameters:(id)arg1;
@property(retain) SUScriptAppleAccount *account;
@property(readonly, copy) NSURL *URL;
- (void)dealloc;

@end

