//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iTunesStoreUI/SUScriptObject.h>

@interface SUScriptPurchaseManager : SUScriptObject
{
}

+ (id)webScriptNameForSelector:(SEL)arg1;
+ (void)initialize;
- (id)isPurchasingItemIdentifier:(id)arg1;
- (id)isPurchasedItemIdentifier:(id)arg1;
- (void)_purchaseRequestsChangedNotification:(id)arg1;
- (id)_className;
- (id)init;
- (void)dealloc;

@end

