//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreMediaStream/MSStreamsProtocol.h>

@interface MSResetServerProtocol : MSStreamsProtocol
{
    struct __MSRSPCContext {
        struct __MSSPCContext _super;
        CDUnknownFunctionPointerType finishedCallback;
        CDUnknownFunctionPointerType authFailedCallback;
        CDUnknownFunctionPointerType didReceiveServerSideConfigurationVersionCallback;
    } _context;
}

- (void)abort;
- (void)resetServerState;
- (void)_coreProtocolDidFinishError:(id)arg1;
- (void)_coreProtocolDidFailAuthenticationError:(id)arg1;
- (id)initWithPersonID:(id)arg1 baseURL:(id)arg2;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end

