//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBSSystemService : NSObject
{
}

+ (id)sharedService;
- (void)reboot;
- (void)sendActions:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (id)clientCallbackQueue;
- (void)terminateApplicationGroup:(int)arg1 forReason:(int)arg2 andReport:(BOOL)arg3 withDescription:(id)arg4;
- (void)terminateApplication:(id)arg1 forReason:(int)arg2 andReport:(BOOL)arg3 withDescription:(id)arg4;
- (void)openDataActivationURL:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)fireCompletion:(CDUnknownBlockType)arg1 error:(id)arg2;
- (id)_badArgumentError;
- (void)shutdown;
- (void)setBadgeValue:(id)arg1 forBundleID:(id)arg2;
- (BOOL)canOpenApplication:(id)arg1 reason:(int *)arg2;
- (int)pidForApplication:(id)arg1;
- (void)openApplication:(id)arg1 options:(id)arg2 withResult:(CDUnknownBlockType)arg3;
- (id)init;
- (void)dealloc;
- (void)openApplication:(id)arg1 options:(id)arg2 clientPort:(unsigned int)arg3 withResult:(CDUnknownBlockType)arg4;
- (unsigned int)createClientPort;
- (void)cleanupClientPort:(unsigned int)arg1;
- (void)openURL:(id)arg1 application:(id)arg2 options:(id)arg3 clientPort:(unsigned int)arg4 withResult:(CDUnknownBlockType)arg5;
- (id)systemApplicationBundleIdentifier;

@end

