//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSMutableDictionary;

@interface CKDMMCSItemGroupSet : NSObject
{
    NSMutableDictionary *_itemsByGroupTuple;
}

@property(retain, nonatomic) NSMutableDictionary *itemsByGroupTuple; // @synthesize itemsByGroupTuple=_itemsByGroupTuple;
- (id)allItemGroups;
- (id)CKPropertiesDescription;
@property(readonly, nonatomic) NSError *error;
- (void).cxx_destruct;
- (void)addItem:(id)arg1;
- (id)initWithItems:(id)arg1;
- (id)description;
- (id)init;

@end

