//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class CKDPAsset, CKDPDate, CKDPLocationCoordinate, CKDPPackage, CKDPRecordReference, NSData, NSMutableArray, NSString;

@interface CKDPRecordFieldValue : PBCodable <NSCopying>
{
    double _doubleValue;
    long long _signedValue;
    CKDPAsset *_assetValue;
    NSData *_bytesValue;
    CKDPDate *_dateValue;
    NSMutableArray *_listValues;
    CKDPLocationCoordinate *_locationValue;
    CKDPPackage *_packageValue;
    CKDPRecordReference *_referenceValue;
    NSString *_stringValue;
    int _type;
    struct {
        unsigned int doubleValue:1;
        unsigned int signedValue:1;
        unsigned int type:1;
    } _has;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) BOOL hasType;
- (id)_descriptionForType:(int)arg1;
- (id)_prettyRepresentationFromObject:(id)arg1;
- (id)_prettyDictionaryRepresentation;
@property(retain, nonatomic) CKDPPackage *packageValue; // @synthesize packageValue=_packageValue;
@property(retain, nonatomic) NSMutableArray *listValues; // @synthesize listValues=_listValues;
@property(retain, nonatomic) CKDPAsset *assetValue; // @synthesize assetValue=_assetValue;
@property(retain, nonatomic) CKDPRecordReference *referenceValue; // @synthesize referenceValue=_referenceValue;
@property(retain, nonatomic) CKDPLocationCoordinate *locationValue; // @synthesize locationValue=_locationValue;
@property(retain, nonatomic) CKDPDate *dateValue; // @synthesize dateValue=_dateValue;
@property(nonatomic) long long signedValue; // @synthesize signedValue=_signedValue;
@property(retain, nonatomic) NSData *bytesValue; // @synthesize bytesValue=_bytesValue;
@property(readonly, nonatomic) BOOL hasPackageValue;
@property(readonly, nonatomic) BOOL hasAssetValue;
@property(readonly, nonatomic) BOOL hasReferenceValue;
@property(readonly, nonatomic) BOOL hasLocationValue;
@property(readonly, nonatomic) BOOL hasStringValue;
@property(readonly, nonatomic) BOOL hasDateValue;
@property(nonatomic) BOOL hasDoubleValue;
@property(nonatomic) double doubleValue; // @synthesize doubleValue=_doubleValue;
@property(nonatomic) BOOL hasSignedValue;
@property(readonly, nonatomic) BOOL hasBytesValue;
- (id)listValueAtIndex:(unsigned int)arg1;
- (void)clearListValues;
- (unsigned int)listValuesCount;
- (void)addListValue:(id)arg1;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
@property(retain, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) int type; // @synthesize type=_type;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

