//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIView<CKGradientReferenceView>;

@interface CKGradientView : UIView
{
    UIView<CKGradientReferenceView> *_referenceView;
    NSArray *_colors;
    UIView *_effectView;
    struct CGRect _gradientFrame;
}

+ (id)gradientViews;
- (void)updateGradientImage;
- (void)updateAnimation;
@property(nonatomic) struct CGRect gradientFrame; // @synthesize gradientFrame=_gradientFrame;
@property(nonatomic) UIView<CKGradientReferenceView> *referenceView; // @synthesize referenceView=_referenceView;
- (id)gradient;
@property(retain, nonatomic) UIView *effectView; // @synthesize effectView=_effectView;
@property(retain, nonatomic) NSArray *colors; // @synthesize colors=_colors;
- (void)_removeAllAnimations:(BOOL)arg1;
- (void)didMoveToSuperview;
- (id)description;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

