//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKBalloonView.h>

#import "CKAnimationTimerObserver.h"

@class CKAnimatedImage, CKBalloonImageView, NSArray, NSString;

@interface CKImageBalloonView : CKBalloonView <CKAnimationTimerObserver>
{
    CKAnimatedImage *_animatedImage;
    NSArray *_frames;
    CKBalloonImageView *_tailMask;
}

- (void)animationTimerFired:(unsigned int)arg1;
@property(copy, nonatomic) NSArray *frames; // @synthesize frames=_frames;
- (void)updateAnimationTimerObserving;
@property(retain, nonatomic) CKBalloonImageView *tailMask; // @synthesize tailMask=_tailMask;
@property(retain, nonatomic) CKAnimatedImage *animatedImage; // @synthesize animatedImage=_animatedImage;
- (void)configureForMessagePart:(id)arg1;
- (void)configureForMediaObject:(id)arg1 previewWidth:(float)arg2 orientation:(BOOL)arg3;
- (BOOL)needsGroupOpacity;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1 textAlignmentInsets:(struct UIEdgeInsets *)arg2;
- (void)setCanUseOpaqueMask:(BOOL)arg1;
- (void)setHasTail:(BOOL)arg1;
- (void)prepareForDisplay;
- (id)overlayColor;
- (void)prepareForReuse;
@property(readonly, copy) NSString *description;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

