//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMMessage.h"

@interface IMMessage (CKAdditions)
- (BOOL)__ck_isEqualToMessageUsingGUID:(id)arg1;
- (id)__ck_attachmentText:(BOOL)arg1;
- (id)__ck_downgradedMessage;
- (id)__ck_undowngradedMessage;
- (id)__ck_service;
- (id)__ck_previewText;
- (BOOL)__ck_isiMessage;
- (BOOL)__ck_isSMS;
@end

