//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@interface UICollectionView (CKUtilities)
- (void)__ck_scrollToTopOfCellAtIndexPath:(id)arg1 hidingCellAtIndexPath:(id)arg2 animated:(BOOL)arg3;
- (BOOL)__ck_isScrolledToBottomHidingIndexPath:(id)arg1;
- (struct CGPoint)__ck_scrollToBottomContentOffsetHidingIndexPath:(id)arg1;
- (id)__ck_indexPathForLastItem;
- (struct CGSize)__ck_contentSize;
- (void)__ck_reloadDataKeepingSelection;
@end

