//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_semaphore>;

@interface SFWirelessSettingsController : NSObject
{
    id _delegate;
    BOOL _wifiEnabled;
    BOOL _bluetoothEnabled;
    BOOL _deviceSupportsWAPI;
    BOOL _firstCallbackCompleted;
    BOOL _wirelessAccessPointEnabled;
    struct __SFOperation *_information;
    NSObject<OS_dispatch_semaphore> *_firstCallBackSemaphore;
}

@property(readonly, getter=isWirelessAccessPointEnabled) BOOL wirelessAccessPointEnabled;
@property(readonly) BOOL deviceSupportsWAPI;
- (void)repairAppleID;
@property(getter=isBluetoothEnabled) BOOL bluetoothEnabled;
- (void)handleOperationCallback:(struct __SFOperation *)arg1 event:(long)arg2 withResults:(id)arg3;
@property(getter=isWifiEnabled) BOOL wifiEnabled;
@property __weak id <SFWirelessSettingsControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)dealloc;

@end

