//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface _NSDispatchData : NSData
{
}

+ (BOOL)supportsSecureCoding;
- (void)enumerateByteRangesUsingBlock:(CDUnknownBlockType)arg1;
- (id)subdataWithRange:(struct _NSRange)arg1;
- (void)getBytes:(void *)arg1 range:(struct _NSRange)arg2;
- (Class)classForCoder;
- (void)getBytes:(void *)arg1 length:(unsigned int)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (const void *)bytes;
- (unsigned int)length;
- (unsigned int)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)getBytes:(void *)arg1;
- (BOOL)_allowsDirectEncoding;
- (BOOL)_isDispatchData;

@end

