//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@class NSConcreteMapTable;

@interface NSConcreteMapTableValueEnumerator : NSEnumerator
{
    NSConcreteMapTable *mapTable;
    unsigned int counter;
}

+ (id)enumeratorWithMapTable:(id)arg1;
- (id)nextObject;
- (void)dealloc;

@end

