//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData, NSDictionary, NSString, NSURL;

@interface NSFileWrapper : NSObject <NSCoding>
{
    NSDictionary *_fileAttributes;
    NSString *_preferredFileName;
    NSString *_fileName;
    id _contents;
    id _icon;
    id _moreVars;
}

+ (BOOL)_finishWritingToURL:(id)arg1 byMovingItemAtURL:(id)arg2 addingAttributes:(id)arg3 error:(id *)arg4;
+ (BOOL)_finishWritingToURL:(id)arg1 byTakingContentsFromItemAtURL:(id)arg2 addingAttributes:(id)arg3 usingTemporaryDirectoryAtURL:(id)arg4 backupFileName:(id)arg5 error:(id *)arg6;
+ (id)_temporaryDirectoryURLForWritingToURL:(id)arg1 error:(id *)arg2;
+ (void)_removeTemporaryDirectoryAtURL:(id)arg1;
+ (void)initialize;
+ (void)_writeAttributes:(id)arg1 toURL:(id)arg2;
+ (id)_newContentsAtURL:(id)arg1 path:(id)arg2 itemKind:(id)arg3 oldChildrenByUniqueFileName:(id)arg4 options:(unsigned int)arg5 error:(id *)arg6;
+ (BOOL)_forPath:(id)arg1 getItemKind:(id *)arg2 modificationDate:(id *)arg3;
+ (BOOL)_canSafelyMapFilesAtPath:(id)arg1;
+ (id)_pathForURL:(id)arg1 reading:(BOOL)arg2 error:(id *)arg3;
@property(copy) NSString *preferredFilename;
- (id)initRegularFileWithContents:(id)arg1;
@property(copy) NSDictionary *fileAttributes;
@property(copy) NSString *filename;
@property(readonly, getter=isDirectory) BOOL directory;
- (BOOL)writeToURL:(id)arg1 options:(unsigned int)arg2 originalContentsURL:(id)arg3 error:(id *)arg4;
@property(readonly, copy) NSData *regularFileContents;
@property(readonly, getter=isRegularFile) BOOL regularFile;
- (id)initWithURL:(id)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (id)initWithSerializedRepresentation:(id)arg1;
- (id)_init;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)_fullDescription:(BOOL)arg1;
- (id)addRegularFileWithContents:(id)arg1 preferredFilename:(id)arg2;
- (id)initSymbolicLinkWithDestinationURL:(id)arg1;
- (id)initDirectoryWithFileWrappers:(id)arg1;
@property(readonly, copy) NSData *serializedRepresentation;
- (id)_uniqueFileNameOfChild:(id)arg1;
- (void)_resetFileModificationDate;
- (id)keyForFileWrapper:(id)arg1;
- (void)_addParent:(id)arg1;
- (id)_newImpl;
- (id)_attributesToWrite;
- (BOOL)_writeContentsToURL:(id)arg1 path:(id)arg2 originalContentsURL:(id)arg3 tryHardLinking:(BOOL)arg4 didHardLinking:(char *)arg5 error:(id *)arg6;
- (void)_updateDescendantFileNames;
@property(readonly, copy) NSURL *symbolicLinkDestinationURL;
- (void)_forWritingToURL:(id)arg1 returnContentsLazyReadingError:(id *)arg2;
- (void)_removeChild:(id)arg1 forUniqueFileName:(id)arg2;
- (BOOL)readFromURL:(id)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (BOOL)matchesContentsOfURL:(id)arg1;
- (BOOL)_matchesItemKind:(id)arg1 modificationDate:(id)arg2;
@property(readonly, getter=isSymbolicLink) BOOL symbolicLink;
- (void)_observePreferredFileNameOfChild:(id)arg1;
- (id)addFileWrapper:(id)arg1;
- (void)removeFileWrapper:(id)arg1;
@property(readonly, copy) NSDictionary *fileWrappers;
- (void)_removeParent:(id)arg1;
- (id)_initWithImpl:(id)arg1 preferredFileName:(id)arg2 uniqueFileName:(id)arg3 docInfo:(id)arg4 iconData:(id)arg5;
- (void)_initDirectoryContents;
- (id)_addChild:(id)arg1 forUniqueFileName:(id)arg2;
- (BOOL)_readContentsFromURL:(id)arg1 path:(id)arg2 itemKind:(id)arg3 options:(unsigned int)arg4 error:(id *)arg5;

@end

