//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NSFilePresenterOperationRecord : NSObject
{
    NSString *operationDescription;
    int state;
    id reactor;
}

+ (id)operationRecordWithDescription:(id)arg1;
@property(readonly) int state; // @synthesize state;
- (id)description;
- (void)dealloc;
@property(readonly) NSString *operationDescription; // @synthesize operationDescription;
@property id reactor; // @synthesize reactor;
- (void)didEnd;
- (void)willEnd;
- (void)didBegin;

@end

