//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSXPCCoder.h>

@class NSObject<OS_xpc_object>, NSXPCConnection, NSXPCInterface;

@interface NSXPCDecoder : NSXPCCoder
{
    NSObject<OS_xpc_object> *_oolObjects;
    NSXPCInterface *_interface;
    SEL _replyToSelector;
    unsigned long long _genericIndex;
    void **_decoder;
    NSXPCConnection *_connection;
    struct *_collections[128];
    struct {
        unsigned int offset;
        int type;
    } _rootObject;
    unsigned int _collectionPointer;
    id _allowedClassesList[128];
    int _allowedClassesIndex;
}

+ (id)_createXPCObjectWithData:(id)arg1;
- (void)finalize;
@property(retain) NSXPCInterface *interface; // @synthesize interface=_interface;
@property NSXPCConnection *_connection; // @synthesize _connection;
- (id)decodeObject;
- (int)decodeInt32ForKey:(id)arg1;
- (void)decodeValueOfObjCType:(const char *)arg1 at:(void *)arg2;
- (long long)decodeInt64ForKey:(id)arg1;
- (id)decodeObjectOfClasses:(id)arg1 forKey:(id)arg2;
- (id)decodeXPCObjectOfType:(struct _xpc_type_s *)arg1 forKey:(id)arg2;
- (id)decodeXPCObjectForKey:(id)arg1;
- (double)decodeDoubleForKey:(id)arg1;
- (id)decodeObjectOfClass:(Class)arg1 forKey:(id)arg2;
- (float)decodeFloatForKey:(id)arg1;
- (const char *)decodeBytesForKey:(id)arg1 returnedLength:(unsigned int *)arg2;
- (int)decodeIntegerForKey:(id)arg1;
- (BOOL)allowsKeyedCoding;
- (int)decodeIntForKey:(id)arg1;
- (id)debugDescription;
- (BOOL)containsValueForKey:(id)arg1;
- (BOOL)decodeBoolForKey:(id)arg1;
- (id)decodeObjectForKey:(id)arg1;
- (void)dealloc;
@property SEL replyToSelector; // @synthesize replyToSelector=_replyToSelector;
- (id)decodeInvocation;
- (const char *)_decodeCStringForKey:(id)arg1;
- (id)_initWithRootXPCObject:(id)arg1;
- (void)_validateAllowedClass:(Class)arg1 forKey:(id)arg2 allowingInvocations:(BOOL)arg3;
- (id)_decodeArrayOfObjectsForKey:(id)arg1;
- (id)allowedClasses;

@end

