//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PoolResource : NSObject
{
    long long currentItemPoolDiff;
    long long currentItemPoolValue;
}

- (id)initWith:(long long)arg1;
@property(nonatomic) long long currentItemPoolValue; // @synthesize currentItemPoolValue;
@property(nonatomic) long long currentItemPoolDiff; // @synthesize currentItemPoolDiff;

@end

