//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSTableCell.h>

#import "UIWebViewDelegate.h"

@class NSString, PSSoftwareUpdateAnimatedIcon, PSWebContainerView, UIImage, UILabel, UIProgressView;

@interface PSSoftwareUpdateTitleCell : PSTableCell <UIWebViewDelegate>
{
    int _progressStyle;
    PSSoftwareUpdateAnimatedIcon *_animatedGearView;
    BOOL _animatingGearView;
    UIProgressView *_progressBar;
    UILabel *_updateStatusLabel;
    PSWebContainerView *_releaseNotesSummaryView;
}

+ (int)cellStyle;
@property(retain, nonatomic) PSWebContainerView *releaseNotesSummaryView; // @synthesize releaseNotesSummaryView=_releaseNotesSummaryView;
@property(retain, nonatomic) UILabel *updateStatusLabel; // @synthesize updateStatusLabel=_updateStatusLabel;
@property(nonatomic) int progressDisplayStyle;
- (float)preferredHeightWithTable:(id)arg1;
- (void)setReleaseNotesSummary:(id)arg1;
- (void)setAnimatingGearView:(BOOL)arg1;
- (void)sizeToFitWithTable:(id)arg1;
- (id)newSoftwareUpdateAnimatedIconWithFrame:(struct CGRect)arg1;
@property(readonly, retain, nonatomic) UIImage *gearBackgroundImage;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)setStatusMessage:(id)arg1;
@property(retain, nonatomic) UIProgressView *progressBar; // @synthesize progressBar=_progressBar;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)setProgress:(float)arg1;
- (void)didMoveToSuperview;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)layoutSubviews;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

