//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString, UIAlertAction;

@interface AUUIAlert : NSObject <UIAlertViewDelegate>
{
    BOOL modernAlerts;
    BOOL stackButtons;
    BOOL prepared;
    id <AUUIAlertDelegate> delegate;
    id context;
    int tag;
    id alert;
    NSString *title;
    NSString *message;
    NSString *okButtonTitle;
    int okButtonIndex;
    NSString *cancelButtonTitle;
    int cancelButtonIndex;
    NSString *alternateButtonTitle;
    int alternateButtonIndex;
    NSString *destructiveButtonTitle;
    int destructiveButtonIndex;
    id viewController;
    UIAlertAction *okAction;
    UIAlertAction *cancelAction;
    UIAlertAction *alternateAction;
    UIAlertAction *destructiveAction;
}

@property(retain, nonatomic) NSString *cancelButtonTitle; // @synthesize cancelButtonTitle;
@property(retain, nonatomic) id alert; // @synthesize alert;
@property(nonatomic) BOOL stackButtons; // @synthesize stackButtons;
@property(retain, nonatomic) NSString *destructiveButtonTitle; // @synthesize destructiveButtonTitle;
@property(retain, nonatomic) NSString *alternateButtonTitle; // @synthesize alternateButtonTitle;
@property(retain, nonatomic) NSString *okButtonTitle; // @synthesize okButtonTitle;
- (void)enableAlternateAction:(BOOL)arg1;
- (void)enableDestructiveAction:(BOOL)arg1;
- (void)enableCancelAction:(BOOL)arg1;
- (void)enableOKAction:(BOOL)arg1;
- (void)dismissWithOKActionAnimated:(BOOL)arg1;
- (void)prepareToShow;
@property(retain, nonatomic) UIAlertAction *okAction; // @synthesize okAction;
@property(retain, nonatomic) UIAlertAction *alternateAction; // @synthesize alternateAction;
@property(retain, nonatomic) UIAlertAction *destructiveAction; // @synthesize destructiveAction;
- (void)applicationDidEnterBackgroundNotification:(id)arg1;
- (id)initWithViewController:(id)arg1 actionSheet:(BOOL)arg2;
- (void)dismissWithCancelActionAnimated:(BOOL)arg1;
- (id)initWithViewController:(id)arg1;
- (void)dismissWithNoActionAnimated:(BOOL)arg1;
- (BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;
@property(retain, nonatomic) UIAlertAction *cancelAction; // @synthesize cancelAction;
@property(retain, nonatomic) NSString *message; // @synthesize message;
@property(retain, nonatomic) id viewController; // @synthesize viewController;
@property(retain, nonatomic) id context; // @synthesize context;
@property(nonatomic) int tag; // @synthesize tag;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(nonatomic) id <AUUIAlertDelegate> delegate; // @synthesize delegate;
- (void)dealloc;
- (void)show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

