//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AirPortAssistant/NetTopoObjectLayer.h>

@interface NetTopoAirPortDeviceLayer : NetTopoObjectLayer
{
}

- (void)initNetTopoAirPortDeviceLayerCommonWithStyle:(int)arg1 andOwningView:(id)arg2;
- (void)setAssociatedNode:(id)arg1;
- (CDStruct_95077174)getConnectionAttachmentLocations;
- (void)pickCorrectImagesForContentsScale:(float)arg1;
- (id)initWithUIStyle:(int)arg1 andOwningView:(id)arg2;
- (void)layoutSublayers;
- (id)debugDescription;
- (id)description;
- (void)dealloc;

@end

