//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, NSString;

@protocol StepByStepUIDelegate
- (void)stepByStepNextStep:(int)arg1 paramDict:(NSDictionary *)arg2;
- (void)stepByStepCompleteWithResult:(long)arg1 paramDict:(NSDictionary *)arg2;
- (void)stepByStepProgressUpdated:(int)arg1 status:(long)arg2 paramString:(NSString *)arg3;
@end

