//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_semaphore>, NSTimer;

@interface WiFiUtils : NSObject
{
    NSDictionary *_unmergedScanInfoDict;
    NSMutableDictionary *_missingBSSIDCounts;
    struct WiFiShimContext *_wifiShim;
    NSObject<OS_dispatch_semaphore> *_wifiBusy;
    BOOL _scanInProgress;
    BOOL _joinInProgress;
    BOOL _scanningActive;
    BOOL _scanOnlyWhenAppActive;
    NSTimer *_scanTimer;
    int _periodicScanType;
    double _periodicScanInterval;
}

+ (BOOL)stringArray:(id)arg1 containsBSSID:(id)arg2;
+ (int)barsForRSSI:(int)arg1;
+ (id)copyFilteredNetworks:(id)arg1 ignoreOptions:(int)arg2;
+ (BOOL)networkIsApple:(id)arg1 productID:(unsigned int *)arg2;
+ (BOOL)scanInfoCanJoin5GHzNetworks:(id)arg1;
+ (BOOL)scanInfoCanJoin2_4GHzNetworks:(id)arg1;
+ (BOOL)scanInfoIsiAPOverWiFiDevice:(id)arg1;
+ (unsigned int)scanInfoSubAppleProductID:(id)arg1;
+ (id)scanInfoAirPortUniqueIdentifier:(id)arg1;
+ (BOOL)scanInfoIsDWDSCapable:(id)arg1 isDWDSEnabled:(char *)arg2;
+ (BOOL)scanInfoIsGuestNetwork:(id)arg1;
+ (BOOL)scanInfoIsIBSS:(id)arg1;
+ (BOOL)network:(id)arg1 shouldBeIgnored:(int)arg2;
+ (BOOL)scanInfoIsAudioDevice:(id)arg1;
+ (BOOL)scanInfoTestBitFromAppleDeviceIE:(id)arg1 forType:(int)arg2;
+ (BOOL)scanInfoIsAirPlayDevice:(id)arg1;
+ (id)scanInfoStringFromAppleDeviceIE:(id)arg1 forType:(int)arg2;
+ (BOOL)scanInfoIsInSoftReset:(id)arg1;
+ (BOOL)scanInfoIs5GHz:(id)arg1;
+ (void)sharedInstanceRelease;
+ (id)scanInfoManufacturerName:(id)arg1;
+ (id)scanInfoModelName:(id)arg1;
+ (BOOL)scanInfoIsMFIAirPlayDevice:(id)arg1;
+ (id)scanInfoBSSIDStr:(id)arg1;
+ (BOOL)scanInfoSupportsSpruce:(id)arg1;
+ (BOOL)scanInfoSupportsACPConfigV1:(id)arg1;
+ (BOOL)scanInfoSupportsMFIConfigV1:(id)arg1;
+ (BOOL)scanInfoIsUnconfigured:(id)arg1;
+ (id)scanInfoNetworkName:(id)arg1;
+ (BOOL)networkIsSecure:(id)arg1 secMode:(int *)arg2 isEnterprise:(char *)arg3;
+ (id)getNetworkPassword:(id)arg1;
+ (id)scanInfoFriendlyName:(id)arg1;
+ (int)scanInfoDeviceKind:(id)arg1;
+ (unsigned int)scanInfoAppleProductID:(id)arg1;
+ (id)sharedInstanceRef;
+ (BOOL)scanInfoIsSTAOnly:(id)arg1;
+ (id)sharedInstance;
- (void)mergeScanResults:(id)arg1;
- (long)joinNetworkWithScanInfo:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (long)scanInfoViaDirectedScanSync:(id)arg1 wifiType:(int)arg2 scanInfo:(id *)arg3;
@property(nonatomic) double periodicScanInterval; // @synthesize periodicScanInterval=_periodicScanInterval;
@property(nonatomic) int periodicScanType; // @synthesize periodicScanType=_periodicScanType;
- (long)asyncWiFiScan:(int)arg1;
- (id)getLinkStatus;
- (id)getIfList;
- (id)getCurrentAssociationInfoOrNil;
- (id)resetScanInfosOfType:(int)arg1;
- (id)unconfiguredScanInfosOfType:(int)arg1;
- (void)setScanOnlyWhenAppActive:(BOOL)arg1;
- (long)_asyncWiFiScan:(int)arg1 isPeriodic:(BOOL)arg2;
- (void)asyncWiFiScanThread:(id)arg1;
- (id)getCurrentAssociationScanInfo;
- (void)scanInfoViaDirectedScanThread:(id)arg1;
- (void)joinNetworkWithNameThread:(id)arg1;
- (void)joinNetworkWithScanInfoThread:(id)arg1;
- (id)unmergedScanInfoDict;
- (void)setJoinInProgress:(BOOL)arg1;
- (BOOL)isJoinInProgress;
- (void)setScanInProgress:(BOOL)arg1;
- (BOOL)isScanInProgress;
- (void)triggerScan;
- (long)closeWiFi;
- (void)scanTimerCallback:(id)arg1;
- (void)setUnmergedScanInfoDict:(id)arg1;
- (long)openWiFi;
@property(retain, nonatomic) NSTimer *_scanTimer; // @synthesize _scanTimer;
- (long)joinNetworkWithNameAsync:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (id)scanInfoForName:(id)arg1 wifiType:(int)arg2;
- (id)scanInfoForMACAddress:(id)arg1;
- (id)getNetworkPasswordForNetworkNamed:(id)arg1;
- (id)mergedScanInfoArray;
- (BOOL)isScanningActive;
- (long)scanInfoViaDirectedScanAsync:(id)arg1 wifiType:(int)arg2 retries:(int)arg3;
- (long)joinNetworkWithScanInfoAsync:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (long)clearScanCacheSync;
- (long)dissassociateSync;
- (BOOL)getAutoJoinState;
- (id)getCurrentAssociationInfo;
- (BOOL)isCurrentlyAssociatedToAnInfrastructureNetwork:(char *)arg1;
- (id)getPreferredNetworks:(BOOL)arg1;
- (void)cancelAsync;
- (id)unmergedScanInfoArray;
- (long)setAutoJoinState:(BOOL)arg1;
- (void)activateScanning:(BOOL)arg1;
- (BOOL)airPortIsOn;
- (id)init;
- (void)dealloc;

@end

