//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CATransform3D {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
};

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct concomp {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
    unsigned short _field7;
    unsigned short _field8;
    unsigned short _field9;
    unsigned short _field10;
    unsigned short _field11;
    unsigned char _field12;
    unsigned char _field13;
    unsigned char _field14;
    struct concomp *_field15[2];
    char _field16[6];
};

struct lineseg;

struct sequence;

struct vImage_Buffer {
    void *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
};

#pragma mark Typedef'd Structures

typedef struct {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    char *_field5;
    char *_field6;
    int _field7;
    int _field8;
    int _field9;
    struct lineseg *_field10;
    int _field11;
    int _field12;
    int _field13;
    struct concomp *_field14;
    int _field15;
    int _field16;
    int _field17;
    int _field18;
    struct sequence *_field19;
    int _field20;
    int _field21;
} CDStruct_7f413479;

