//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IDSServiceMonitor : NSObject
{
    int _availability;
    NSString *_service;
    int _token;
}

- (void)handleActiveAccountsChanged:(id)arg1;
- (void)_postAvailability:(int)arg1;
- (void)updateAvailability;
- (int)serviceAvailability;
- (id)initWithService:(id)arg1;
@property(readonly, retain, nonatomic) NSString *service;
- (void)dealloc;
- (void)_updateAvailability;

@end

