//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SiriUI/SiriUISnippetViewController.h>

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSMutableArray, NSString, SALocalSearchReviewList, UICollectionView, UIView;

@interface SiriUIReviewsViewController : SiriUISnippetViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    SALocalSearchReviewList *_reviewList;
    NSMutableArray *_cellSizeForRowCache;
    struct {
        unsigned int didLoadCollectionView:1;
        unsigned int viewForRatingForReview:1;
        unsigned int offsetForRatingView:1;
    } _delegateFlags;
    id <SiriUIReviewsViewControllerDelegate> _reviewsDelegate;
    int _reviewCharacterLimit;
    UIView *_totalRatingView;
    float _verticalSpaceNeededForRatingView;
    UIView *_providerView;
    NSString *_providerName;
    struct UIOffset _totalRatingViewOffset;
    struct UIOffset _providerViewOffset;
}

@property(copy, nonatomic) NSString *providerName; // @synthesize providerName=_providerName;
- (int)_numberOfColumnsForWidth:(float)arg1;
@property(retain, nonatomic) SALocalSearchReviewList *reviewList; // @synthesize reviewList=_reviewList;
@property(nonatomic) float verticalSpaceNeededForRatingView; // @synthesize verticalSpaceNeededForRatingView=_verticalSpaceNeededForRatingView;
@property(nonatomic) struct UIOffset totalRatingViewOffset; // @synthesize totalRatingViewOffset=_totalRatingViewOffset;
@property(retain, nonatomic) UIView *totalRatingView; // @synthesize totalRatingView=_totalRatingView;
@property(nonatomic) int reviewCharacterLimit; // @synthesize reviewCharacterLimit=_reviewCharacterLimit;
@property(nonatomic) __weak id <SiriUIReviewsViewControllerDelegate> reviewsDelegate; // @synthesize reviewsDelegate=_reviewsDelegate;
- (void)didEndDisplayingReusableHeaderView:(id)arg1;
- (Class)headerViewClass;
- (int)_numberOfRowsForWidth:(float)arg1;
- (int)_rowForItemAtIndex:(int)arg1 forWidth:(float)arg2;
- (id)_punchoutForIndexPath:(id)arg1;
- (void)configureReusableHeaderView:(id)arg1;
- (struct CGSize)_sizeForCellAtIndex:(int)arg1 forWidth:(float)arg2;
- (int)_numberOfCells;
- (float)_horizontalCellSpacing;
- (float)_minCellWidth;
- (float)_effectiveContentWidthForItemCellsForWidth:(float)arg1;
- (struct UIEdgeInsets)_reviewCollectionInsets;
- (id)_displayStringForReviewCount:(int)arg1 providerName:(id)arg2 providerView:(id)arg3;
- (void)siriDidLayoutSnippetView;
@property(nonatomic) struct UIOffset providerViewOffset; // @synthesize providerViewOffset=_providerViewOffset;
@property(retain, nonatomic) UIView *providerView; // @synthesize providerView=_providerView;
- (void)updateSubtitle;
- (void).cxx_destruct;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (float)desiredHeightForWidth:(float)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UICollectionView *view;

@end

