//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Radio/RadioRequest.h>

@class RadioStation, SSURLConnectionRequest;

@interface RadioLikeRequest : RadioRequest
{
    long long _itemID;
    int _likeStatus;
    SSURLConnectionRequest *_request;
    int _seedType;
    RadioStation *_station;
    BOOL _isSeed;
}

- (id)initWithTrack:(id)arg1 station:(id)arg2;
@property(nonatomic) int likeStatus; // @synthesize likeStatus=_likeStatus;
- (void)startWithLikeCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithItemID:(long long)arg1 seedType:(int)arg2 station:(id)arg3;
@property(nonatomic) BOOL isSeed; // @synthesize isSeed=_isSeed;
- (id)initWithTrackID:(id)arg1 station:(id)arg2;
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (id)init;

@end

