//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TelephonyUI/TPLCDBar.h>

@class TPLCDSubImageView, TPLCDTextView, UIView;

@interface TPLCDView : TPLCDBar
{
    UIView *_contentView;
    TPLCDTextView *_textView;
    TPLCDTextView *_labelView;
    TPLCDSubImageView *_imageView;
    unsigned int _layoutAsLabelled:1;
    BOOL _verticallyCenterTextViewIfLabelless;
}

+ (float)defaultLabelFontSize;
+ (float)defaultTextFontSize;
@property BOOL verticallyCenterTextViewIfLabelless; // @synthesize verticallyCenterTextViewIfLabelless=_verticallyCenterTextViewIfLabelless;
- (id)secondLineText;
- (void)setSecondLineText:(id)arg1;
- (void)setLayoutAsLabelled:(BOOL)arg1;
- (void)setSubImage:(id)arg1;
- (void)blinkLabel;
- (void)setLabelFontSize:(float)arg1;
- (void)setTextFontSize:(float)arg1;
- (void)setContentsAlpha:(float)arg1;
- (void)didFinishAnimatingLCDLabelFadeOut:(id)arg1 finished:(id)arg2 context:(id)arg3;
- (void)setLabel:(id)arg1 animate:(BOOL)arg2;
- (struct CGRect)_imageViewFrame;
- (BOOL)shouldCenterText;
- (struct CGRect)_text1Frame;
- (BOOL)shouldCenterContentView;
- (float)_labelVInset;
- (float)_textVInset;
- (void)_resetContentViewFrame;
- (id)subImage;
- (id)initWithDefaultSizeForOrientation:(int)arg1;
- (struct CGRect)fullSizedContentViewFrame;
- (struct CGRect)textFrame;
- (void)setLabel:(id)arg1;
- (id)label;
- (struct CGRect)_labelFrame;
- (void)setShadowColor:(id)arg1;
- (void)setText:(id)arg1;
- (id)text;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)dealloc;

@end

