//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppleAccount/AAFamilyRequest.h>

@class SSAccount;

@interface AAFamilyEligibilityRequest : AAFamilyRequest
{
    SSAccount *_iTunesAccount;
}

+ (Class)responseClass;
- (id)urlRequest;
@property(retain, nonatomic) SSAccount *iTunesAccount; // @synthesize iTunesAccount=_iTunesAccount;
- (id)urlString;
- (void).cxx_destruct;

@end

