//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MessageUI/MFComposeRecipient.h>

@class NSArray, NSString;

@interface MFComposeRecipientGroup : MFComposeRecipient
{
    NSArray *_children;
    NSString *_displayString;
}

- (id)children;
- (int)property;
- (int)recordID;
- (void *)record;
- (id)unlocalizedLabel;
- (id)commentedAddress;
- (id)compositeName;
- (BOOL)isRemovableFromSearchResults;
- (BOOL)isGroup;
- (id)label;
- (id)displayString;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)address;
- (id)initWithChildren:(id)arg1 displayString:(id)arg2;
- (void)_populateSortedChildren;
- (id)completelyMatchedAttributedStrings;
- (BOOL)wasCompleteMatch;
- (id)childrenWithCompleteMatches;
- (id)sortedChildren;
- (id)placeholderName;

@end

