//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MessageUI/MFComposeHeaderView.h>

#import "MFComposeRecipientAtomDelegate.h"
#import "MFCorecipientsIndicatorAtomDelegate.h"
#import "MFDragDestination.h"
#import "MFDragSource.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"

@class MFComposeRecipient, MFCorecipientsIndicatorAtom, MFModernComposeRecipientAtom, NSArray, NSCountedSet, NSMutableArray, NSMutableDictionary, NSString, NSTimer, UIButton, UIFont, UITapGestureRecognizer, UITextField, UIView, _MFMailRecipientTextField;

@interface MFComposeRecipientView : MFComposeHeaderView <UITextFieldDelegate, UIGestureRecognizerDelegate, MFComposeRecipientAtomDelegate, MFDragSource, MFDragDestination, MFCorecipientsIndicatorAtomDelegate>
{
    _MFMailRecipientTextField *_textField;
    NSArray *_textFieldConstraints;
    NSMutableArray *_recipients;
    NSMutableDictionary *_atoms;
    NSCountedSet *_uncommentedAddresses;
    struct __CFDictionary *_atomPresentationOptionsByRecipient;
    unsigned int _defaultAtomPresentationOptions;
    MFModernComposeRecipientAtom *_selectedAtom;
    MFComposeRecipient *_placeholderRecipient;
    int _dragSourceOriginalIndex;
    MFCorecipientsIndicatorAtom *_corecipientsIndicatorAtom;
    UIButton *_addButton;
    BOOL _editable;
    BOOL _picking;
    BOOL _expanded;
    NSArray *_properties;
    int _maxRecipients;
    BOOL _parentIsClosing;
    BOOL _deselectOnNextKeyboardInput;
    BOOL _clearSelectionUIAfterFirstResponder;
    NSTimer *_delayTimer;
    double _inputDelay;
    UITapGestureRecognizer *_tapGestureRecognizer;
    BOOL _needsReflow;
    BOOL _needsLayoutConstraintUpdate;
    UIFont *_baseFont;
    id <MFComposeRecipientViewDelegate> _delegate;
    BOOL _didIgnoreFirstResponderResign;
    BOOL _allowsDragAndDrop;
    BOOL _separatorHidden;
    int _hideLastAtomComma;
}

- (void)addAddress:(id)arg1;
@property(retain, nonatomic) UIFont *baseFont;
- (void)setProperty:(int)arg1;
- (BOOL)finishEnteringRecipient;
- (void)selectComposeRecipientAtom:(id)arg1;
@property(readonly, nonatomic) float offsetForRowWithTextField;
@property(readonly, nonatomic) int numberOfRowsOfTextInField;
- (void)parentDidClose;
- (void)parentWillClose;
@property(nonatomic, getter=isSeparatorHidden) BOOL separatorHidden; // @synthesize separatorHidden=_separatorHidden;
- (void)_tapGestureRecognized:(id)arg1;
- (void)setProperties:(id)arg1;
- (void)textFieldDidBecomeFirstResponder:(id)arg1;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) BOOL editable; // @synthesize editable=_editable;
- (void)textFieldDidResignFirstResponder:(id)arg1;
@property(nonatomic) BOOL expanded; // @synthesize expanded=_expanded;
- (void)textChanged:(id)arg1;
- (BOOL)hasContent;
- (void)setLabel:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)clearText;
- (void)keyboardInputChangedSelection:(id)arg1;
- (BOOL)keyboardInputShouldDelete:(id)arg1;
- (BOOL)keyboardInput:(id)arg1 shouldInsertText:(id)arg2 isMarkedText:(BOOL)arg3;
- (void)willMoveToSuperview:(id)arg1;
- (void)didMoveToSuperview;
@property(readonly, nonatomic) NSString *text;
- (BOOL)becomeFirstResponder;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) id <MFComposeRecipientViewDelegate> delegate; // @dynamic delegate;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)addRecord:(void *)arg1 property:(int)arg2 identifier:(int)arg3;
- (void)addRecipient:(id)arg1;
- (void)removeRecipient:(id)arg1;
@property(copy, nonatomic) NSArray *addresses;
- (void)reflow;
@property(readonly, nonatomic) UIView *addButton; // @synthesize addButton=_addButton;
@property(readonly, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(readonly, nonatomic) MFCorecipientsIndicatorAtom *corecipientsIndicator; // @synthesize corecipientsIndicator=_corecipientsIndicatorAtom;
@property(nonatomic) unsigned int defaultAtomPresentationOptions; // @synthesize defaultAtomPresentationOptions=_defaultAtomPresentationOptions;
- (void)_setNeedsLayoutConstraintUpdate;
- (void)mf_recipientTextField:(id)arg1 didAddRecipientAddress:(id)arg2;
- (void)mf_dismissSearchResults:(id)arg1;
- (BOOL)mf_chooseSelectedSearchResultForTextField:(id)arg1;
- (BOOL)mf_presentSearchResultsForTextField:(id)arg1;
- (void)mf_selectPreviousSearchResultForTextField:(id)arg1;
- (void)mf_selectNextSearchResultForTextField:(id)arg1;
- (BOOL)mf_textFieldShowingSearchResults:(id)arg1;
- (void)showCorecipientIndicator:(BOOL)arg1 withCorecipients:(id)arg2 animated:(BOOL)arg3;
- (void)setAddressAtomPresentationOptions:(unsigned int)arg1 forRecipient:(id)arg2;
- (void)didTapShowCorecipientsForIndicatorAtom:(id)arg1 recipients:(id)arg2;
- (void)_deleteSelectedAtom;
- (void)_delayTimerFired:(id)arg1;
@property(nonatomic) BOOL didIgnoreFirstResponderResign; // @synthesize didIgnoreFirstResponderResign=_didIgnoreFirstResponderResign;
- (BOOL)_shouldShowCorecipientsIndicatorAtom;
- (float)_topRowTextWidth;
- (void)_updateLayoutConstraintsAndGetNumberOfRows:(out unsigned int *)arg1 textFieldWillBeLastRow:(out char *)arg2;
- (unsigned int)_addressAtomPresentationOptionsForRecipient:(id)arg1;
- (BOOL)_addable;
- (int)_recipientIndexAtPoint:(struct CGPoint)arg1;
- (void)_deselectAtom;
@property(retain, nonatomic) MFComposeRecipient *placeholderRecipient;
- (void)clearAllAddressAtomPresentationOptions;
- (void)_removeUncommentedAddress:(id)arg1;
- (void)_removeAddressAtomPresentationOptionsForRecipient:(id)arg1;
- (void)_addUncommentedAddress:(id)arg1;
- (void)_reflowAnimated:(BOOL)arg1;
- (void)_cancelDelayTimer;
- (void)addButtonClicked:(id)arg1;
@property(nonatomic) int hideLastAtomComma; // @synthesize hideLastAtomComma=_hideLastAtomComma;
@property(nonatomic) int maxRecipients; // @synthesize maxRecipients=_maxRecipients;
@property(nonatomic) BOOL allowsDragAndDrop; // @synthesize allowsDragAndDrop=_allowsDragAndDrop;
@property(nonatomic) double inputDelay; // @synthesize inputDelay=_inputDelay;
- (void)_addRecord:(void *)arg1 identifier:(int)arg2;
- (void)addRecipient:(id)arg1 index:(unsigned int)arg2 animate:(BOOL)arg3;
- (void)_removeAllRecipients;
- (id)dragInitiatedAtPoint:(struct CGPoint)arg1;
- (void)animatePlaceholderForDragFailure:(id)arg1;
- (struct CGRect)dropRect;
- (void)dragStartedWithItem:(id)arg1;
- (struct CGRect)frameForDraggedItem:(id)arg1;
- (void)dragEntered:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)dragExited:(id)arg1;
- (void)dragUpdated:(id)arg1 atPoint:(struct CGPoint)arg2;
- (id)viewForDrop;
- (void)dragCompletedForItem:(id)arg1 success:(BOOL)arg2;
- (void)dropItem:(id)arg1;
- (void)_setNeedsReflow;
- (BOOL)containsAddress:(id)arg1;
- (BOOL)allowsDrag;
- (id)supportedDropTypes:(id)arg1;
- (id)viewForDraggedItem:(id)arg1 atScale:(float)arg2;
- (id)viewForDragSource;
- (id)uncommentedAddresses;
- (float)textFieldOffsetForNumberOfRowsToScroll:(unsigned int)arg1 numberOfRowsAboveField:(int)arg2;
- (void)refreshPreferredContentSize;
- (void)composeRecipientAtomSelectNext:(id)arg1;
- (void)composeRecipientAtomSelectPrevious:(id)arg1;
- (void)composeRecipientAtomShowPersonCard:(id)arg1;
- (void)deselectComposeRecipientAtom:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

