//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSPredicateVisitor.h"

@class NSArray, NSFetchRequest, NSManagedObjectID, NSMutableSet, NSPredicate, NSRelationshipDescription, NSString, PHCollection, PHFetchOptions, PHPhotoLibrary;

@interface PHQuery : NSObject <NSPredicateVisitor, NSCopying>
{
    NSPredicate *_cachedFetchOptionsPredicate;
    NSPredicate *_basePredicate;
    NSPredicate *_filterPredicate;
    NSFetchRequest *_fetchRequest;
    int _collectionFetchType;
    BOOL _preparedContainerInfo;
    NSRelationshipDescription *_containerRelationship;
    NSManagedObjectID *_containerIdentifier;
    PHCollection *_containerCollection;
    BOOL _preparedCombinedQueryKeys;
    id _combinedQueryGroupKey;
    NSString *_combinedQueryKeyPath;
    NSManagedObjectID *_combinedQuerySeparatingIdentifier;
    BOOL _preparedFilteringAttributes;
    NSMutableSet *_filteringKeys;
    unsigned long long _filteringAttributesIndexValue;
    unsigned long long _filteringRelationshipsIndexValue;
    unsigned long long _objectToContainerRelationshipIndexValue;
    unsigned long long _containerToObjectRelationshipIndexValue;
    unsigned long long _containerSortingAttributesIndexValue;
    BOOL __includesTrashedObjects;
    BOOL __includesCameraRoll;
    BOOL __includesCloudSharedAssets;
    BOOL __includesiTunesSyncAssets;
    PHFetchOptions *_fetchOptions;
    NSString *_fetchType;
    NSArray *_seedOIDs;
    PHPhotoLibrary *_photoLibrary;
}

+ (void)min:(id *)arg1 andMax:(id *)arg2 forKeypath:(id)arg3 ForType:(id)arg4 restrictedToOIDs:(id)arg5 inLibrary:(id)arg6;
+ (id)queryForCloudSharedAlbums;
+ (id)queryForTopLevelUserCollections;
+ (id)queryForMomentsContainingAssetsWithLocalIdentifiers:(id)arg1;
+ (id)queryForAssetsWithObjectIDs:(id)arg1 options:(id)arg2;
+ (id)combinedFetchRequestForQueries:(id)arg1;
+ (id)_rootFolderID;
+ (id)_queryForKeyAssetInAssetCollection:(id)arg1 withRelationshipKeyPath:(id)arg2 options:(id)arg3;
+ (id)queryForType:(id)arg1 withBasePredicate:(id)arg2 seedOIDs:(id)arg3 inLibrary:(id)arg4;
+ (id)_fetchOptionsForFetchingAssetsFromAssetCollection:(id)arg1 options:(id)arg2;
+ (id)_filterPredicateFromFetchOptionsPredicate:(id)arg1 phClass:(Class)arg2;
+ (id)_containerIdentifierForFetchType:(id)arg1 predicate:(id)arg2 outRelationship:(id *)arg3;
+ (id)defaultSortDescriptorForFetchType:(id)arg1 predicate:(id)arg2;
+ (id)_transformedSortDescriptors:(id)arg1 forFetchType:(id)arg2;
+ (id)_relationshipForFetchType:(id)arg1 predicate:(id)arg2;
+ (id)queryForAssetsWithOptions:(id)arg1;
+ (id)queryForKeyAssetsInAssetCollection:(id)arg1 options:(id)arg2;
+ (id)queryForTertiaryKeyAssetsInAssetCollection:(id)arg1 options:(id)arg2;
+ (id)queryForSecondaryKeyAssetsInAssetCollection:(id)arg1 options:(id)arg2;
+ (id)queryForPrimaryKeyAssetsInAssetCollection:(id)arg1 options:(id)arg2;
+ (id)queryForCustomKeyAssetsInAssetCollection:(id)arg1 options:(id)arg2;
+ (id)queryForAssetsWithBurstIdentifier:(id)arg1 options:(id)arg2;
+ (id)queryForAssetsWithCloudIdentifiers:(id)arg1 options:(id)arg2;
+ (id)queryForAssetsWithLocalIdentifiers:(id)arg1 options:(id)arg2;
+ (id)queryForAssetsWithMediaType:(int)arg1 options:(id)arg2;
+ (id)queryForAssetsInAssetCollection:(id)arg1 options:(id)arg2;
+ (id)queryForType:(id)arg1 withIdentifiers:(id)arg2 local:(BOOL)arg3;
+ (id)queryForType:(id)arg1 withBasePredicate:(id)arg2 inLibrary:(id)arg3;
+ (id)queryForCollectionsInCollectionList:(id)arg1;
+ (id)queryForMomentListsWithSubType:(int)arg1 options:(id)arg2;
+ (id)queryForMomentListsWithSubType:(int)arg1 containingMoment:(id)arg2;
+ (id)queryForRootAlbumCollectionList;
+ (id)queryForCollectionListsWithType:(int)arg1 subtype:(int)arg2 options:(id)arg3;
+ (id)queryForCollectionListsWithCloudIdentifiers:(id)arg1;
+ (id)queryForCollectionListsWithLocalIdentifiers:(id)arg1;
+ (id)queryForCollectionListContainingCollection:(id)arg1;
+ (id)queryForMoments;
+ (id)queryForMomentsInMomentList:(id)arg1;
+ (id)queryForAssetCollectionsWithObjectIDs:(id)arg1;
+ (id)queryForAssetCollectionsWithType:(int)arg1 subtype:(int)arg2 options:(id)arg3;
+ (id)queryForAssetCollectionsWithCloudIdentifiers:(id)arg1;
+ (id)queryForAssetCollectionsWithLocalIdentifiers:(id)arg1;
+ (id)queryForAssetCollectionsContainingAsset:(id)arg1 withType:(int)arg2;
@property(readonly) NSPredicate *filterPredicate;
@property(readonly) NSFetchRequest *fetchRequest;
- (id)containerIdentifier;
@property(readonly) PHPhotoLibrary *photoLibrary; // @synthesize photoLibrary=_photoLibrary;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(readonly) NSArray *seedOIDs; // @synthesize seedOIDs=_seedOIDs;
- (unsigned long long)containerToObjectRelationshipIndexValue;
- (unsigned long long)objectToContainerRelationshipIndexValue;
- (unsigned long long)filteringRelationshipsIndexValue;
- (unsigned long long)filteringAttributesIndexValue;
- (unsigned long long)containerSortingAttributesIndexValue;
- (id)updatedQueryWithChange:(id)arg1;
- (id)_containerRelationship;
- (void)_prepareFilteringAttributes;
- (void)_prepareCombinedQueryKeys;
@property(readonly) NSManagedObjectID *combinedQuerySeparatingIdentifier;
@property(readonly) NSString *combinedQueryKeyPath;
- (void)_prepareContainerInfo;
- (id)_createFetchRequestIncludingBasePredicate:(BOOL)arg1;
@property(readonly) NSPredicate *basePredicate; // @synthesize basePredicate=_basePredicate;
- (id)_effectiveSortDescriptors;
- (id)effectivePredicateForPHClass:(Class)arg1 request:(id)arg2 includingBasePredicate:(BOOL)arg3;
- (void)_setContainerCollection:(id)arg1;
@property(nonatomic, setter=_setIncludesCameraRoll:) BOOL _includesCameraRoll; // @synthesize _includesCameraRoll=__includesCameraRoll;
@property(nonatomic, setter=_setIncludesiTunesSyncAssets:) BOOL _includesiTunesSyncAssets; // @synthesize _includesiTunesSyncAssets=__includesiTunesSyncAssets;
@property(nonatomic, setter=_setIncludesCloudSharedAssets:) BOOL _includesCloudSharedAssets; // @synthesize _includesCloudSharedAssets=__includesCloudSharedAssets;
@property(nonatomic, setter=_setIncludesTrashedObjects:) BOOL _includesTrashedObjects; // @synthesize _includesTrashedObjects=__includesTrashedObjects;
@property(copy, nonatomic) PHFetchOptions *fetchOptions; // @synthesize fetchOptions=_fetchOptions;
- (id)initForType:(id)arg1 withBasePredicate:(id)arg2 seedOIDs:(id)arg3 inLibrary:(id)arg4;
- (id)initForType:(id)arg1 withBasePredicate:(id)arg2 inLibrary:(id)arg3;
@property(readonly) id combinedQueryGroupKey;
- (int)collectionFetchType;
@property(readonly) NSString *fetchType; // @synthesize fetchType=_fetchType;
- (id)executeQuery;
- (void)visitPredicateOperator:(id)arg1;
- (void)visitPredicateExpression:(id)arg1;
- (void)visitPredicate:(id)arg1;

@end

