//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LTEAudioDeviceList;

@interface LTEAudioSessionController : NSObject
{
    LTEAudioDeviceList *deviceList;
}

+ (void)initializeAudioSessionQ;
+ (BOOL)setInputDevice:(id)arg1;
+ (id)currentInputDevice;
+ (id)defaultOutputDevice;
+ (id)defaultInputDevice;
+ (BOOL)isMicrophoneMuted;
+ (void)setMicrophoneMuted:(BOOL)arg1;
+ (void)stopAudioSession;
+ (void)startAudioSession;
+ (void)setAudioSessionProperties:(id)arg1;
@property(retain, nonatomic) LTEAudioDeviceList *deviceList; // @synthesize deviceList;
- (id)outputDevices;
- (id)inputDevices;
- (id)devices;
@property(nonatomic) CDUnknownBlockType changeListener;
- (id)init;
- (void)dealloc;

@end

