//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MediaControlClient, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface FigCPEFPAirPlaySession : NSObject
{
    BOOL _invalid;
    unsigned long _fairPlayContext;
    NSDictionary *_protectionInfo;
    NSDictionary *_contentInfo;
    MediaControlClient *_mediaControlClient;
    NSString *_mediaControlUUID;
    unsigned long _vodkaVersion;
    struct FPStreamOpaque_ *_fairPlaySession;
    NSObject<OS_dispatch_queue> *_serializationQueue;
}

- (void)finalize;
- (void)endSession;
- (void)dealloc;
- (id)mediaControlParamsWithStoreResponse:(id)arg1;
- (id)legacySinfs;
- (id)sicWithPic:(id)arg1;
- (id)createPicRequestWithError:(id *)arg1;
- (id)initWithFairPlayContext:(unsigned long)arg1 routeInfo:(id)arg2 mediaControlClient:(id)arg3 mediaControlUUID:(id)arg4;
- (void)beginSessionWithCompletionQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithFairPlayContext:(unsigned long)arg1 contentInfo:(id)arg2 routeInfo:(id)arg3 mediaControlClient:(id)arg4 mediaControlUUID:(id)arg5;
- (id)initWithFairPlayContext:(unsigned long)arg1 protectionInfo:(id)arg2 routeInfo:(id)arg3 mediaControlClient:(id)arg4 mediaControlUUID:(id)arg5;

@end

