//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface SGEntityTag : NSObject <NSCopying>
{
    BOOL _indexed;
    BOOL _stored;
    NSString *_name;
}

+ (id)resolveName:(id)arg1;
+ (id)allDay;
+ (id)extractedFromTemplateWithShortName:(id)arg1;
+ (id)defaultDuration;
+ (id)extractedSocial;
+ (id)extractedFood;
+ (id)extractedMovie;
+ (id)extractedTicket;
+ (id)extractedCarRental;
+ (id)extractedHotel;
+ (id)extractedTrain;
+ (id)extractedBus;
+ (id)extractedFlight;
+ (id)extraKey:(id)arg1;
+ (id)containsEntityExtraction:(long long)arg1;
+ (id)messageWithMessageIdHash:(long long)arg1 fromSource:(id)arg2;
+ (id)identity:(id)arg1;
+ (id)contactDetail:(id)arg1;
+ (id)fromReply;
+ (id)fromForwardedMessage;
+ (id)extractedEventCancellation;
+ (id)human;
+ (id)hardName;
+ (id)url:(id)arg1;
+ (id)inhuman;
+ (id)testTag:(int)arg1;
+ (id)fromExtractedDomain;
+ (id)extractedEvent;
+ (id)tagForPrefix:(id)arg1 value:(id)arg2;
+ (void)rememberPrefix:(id)arg1 stored:(BOOL)arg2 indexed:(BOOL)arg3;
+ (id)remember:(id)arg1;
+ (void)initialize;
@property(readonly, nonatomic) BOOL stored; // @synthesize stored=_stored;
- (BOOL)isUrl;
- (BOOL)isExtraKey;
- (BOOL)isEqualToEntityTag:(id)arg1;
- (BOOL)isTemplateShortName;
- (BOOL)isContactDetail;
@property(readonly, nonatomic) BOOL indexed; // @synthesize indexed=_indexed;
- (id)initWithName:(id)arg1 stored:(BOOL)arg2 indexed:(BOOL)arg3;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)value;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

