//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iCalendar/ICSDateValue.h>

#import "NSCoding.h"

@interface ICSDateTimeValue : ICSDateValue <NSCoding>
{
    int _hour;
    int _minute;
    int _second;
}

- (int)dateType;
- (void)_ICSStringWithOptions:(unsigned int)arg1 appendingToString:(id)arg2;
- (id)components;
@property(readonly) int second; // @synthesize second=_second;
@property(readonly) int minute; // @synthesize minute=_minute;
@property(readonly) int hour; // @synthesize hour=_hour;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithYear:(int)arg1 month:(int)arg2 day:(int)arg3;
- (id)initWithYear:(int)arg1 month:(int)arg2 day:(int)arg3 hour:(int)arg4 minute:(int)arg5 second:(int)arg6;

@end

