//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AccessibilityUtilities/AXServer.h>

@class AXAccessQueue, NSMutableArray, NSMutableDictionary;

@interface AXSpringBoardServer : AXServer
{
    AXAccessQueue *_accessQueue;
    CDUnknownBlockType _currentAlertHandler;
    NSMutableArray *_gestureOverrides;
    NSMutableArray *_actionHandlers;
    NSMutableDictionary *_reachabilityHandlers;
}

+ (id)server;
- (void)setVolume:(float)arg1;
- (int)pid;
- (id)_axSpringBoardServerInstanceIfExists;
- (id)runningAppProcesses;
- (id)focusedAppProcess;
- (id)applicationWithIdentifier:(id)arg1;
- (BOOL)isSettingsAppFrontmost;
- (BOOL)isPurpleBuddyAppFrontmost;
- (BOOL)isSystemAppFrontmostExludingSiri;
- (BOOL)isSystemAppFrontmost;
- (id)runningAppPIDs;
- (int)purpleBuddyPID;
- (id)focusedAppPID;
- (BOOL)isSystemAppShowingAnAlert;
- (id)systemAppInfoWithQuery:(unsigned int)arg1;
- (BOOL)isSpeakThisTemporarilyDisabled;
- (BOOL)isGuidedAccessActive;
- (BOOL)isVoiceControlRunning;
- (void)openVoiceControl;
- (void)setSiriIsTalking:(BOOL)arg1;
- (BOOL)isSiriTalkingOrListening;
- (BOOL)isSiriVisible;
- (void)dismissSiri;
- (void)openSiri;
- (void)dismissAppSwitcher;
- (void)openAppSwitcher;
- (BOOL)isAppSwitcherVisible;
- (void)showControlCenter:(BOOL)arg1;
- (BOOL)showNotificationCenter:(BOOL)arg1;
- (BOOL)isControlCenterVisible;
- (void)hideNotificationCenter;
- (void)showNotificationCenter;
- (BOOL)isMakingEmergencyCall;
- (BOOL)hasActiveOrPendingCallOrFaceTime;
- (BOOL)hasActiveOrPendingCall;
- (void)resumeMedia;
- (void)pauseMedia;
- (BOOL)isMediaPlaying;
- (void)unlockDevice;
- (id)installedApps;
- (BOOL)areSystemGesturesDisabledByAccessibility;
- (BOOL)areSystemGesturesDisabledNatively;
- (BOOL)isSyncingRestoringResettingOrUpdating;
- (BOOL)isSystemSleeping;
- (BOOL)_isSystemAppFrontmostExcludingSiri:(BOOL)arg1;
- (void)toggleNotificationCenter;
- (id)_axSpringBoardServerInstance;
- (id)_axSpringBoardServerInstanceDelegate;
- (BOOL)_shouldDispatchLocally;
- (void)copyStringToPasteboard:(id)arg1;
- (int)activeApplicationOrientation;
- (BOOL)isPointInsideAccessibilityInspector:(id)arg1;
- (BOOL)isInspectorMinimized;
- (void)removeReachabilityHandler:(id)arg1;
- (void)setReachabilityEnabledDuration:(double)arg1;
- (BOOL)toggleIncomingCall;
- (void)cancelReachabilityDetection;
- (void)removeOverrideIntent:(id)arg1;
- (void)removeActionHandler:(id)arg1;
- (void)setShowSpeechPlaybackControls:(BOOL)arg1;
- (void)showAlert:(int)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)hideAlert;
- (float)volumeLevel;
- (float)reachabilityOffset;
- (BOOL)isRingerMuted;
- (BOOL)isSideSwitchUsedForOrientation;
- (void)resetDimTimer;
- (void)setOrientationLocked:(BOOL)arg1;
- (BOOL)isOrientationLocked;
- (int)topEventPidOverride;
- (void)startHearingAidServer;
- (void)setHearingAidControlVisible:(BOOL)arg1;
- (void)openSCATCommonTasks;
- (void)openSCATCustomGestureCreation;
- (void)openAssistiveTouchCustomGestureCreation;
- (void)takeScreenshot;
- (id)_serviceName;
- (void)registerReachabilityHandler:(CDUnknownBlockType)arg1 withIdentifierCallback:(CDUnknownBlockType)arg2;
- (void)registerOverrideIntentForGesture:(unsigned int)arg1 withHandler:(CDUnknownBlockType)arg2 withIdentifierCallback:(CDUnknownBlockType)arg3;
- (void)setCancelGestureActivation:(unsigned int)arg1 cancelEnabled:(BOOL)arg2;
- (void)registerSpringBoardActionHandler:(CDUnknownBlockType)arg1 withIdentifierCallback:(CDUnknownBlockType)arg2;
- (void)showAlert:(int)arg1 withHandler:(CDUnknownBlockType)arg2 withData:(id)arg3;
- (void)cleanupAlertHandler;
- (void)_didConnectToClient;
- (void)_wasDisconnectedFromClient;
- (void)_willClearServer;
- (BOOL)_shouldValidateEntitlements;
- (id)_handleReachabilityResult:(id)arg1;
- (id)_handleActionResult:(id)arg1;
- (id)_handleGestureOverrideResult:(id)arg1;
- (id)_handleReplyResult:(id)arg1;
- (void)_didConnectToServer;
@property(retain, nonatomic) NSMutableArray *actionHandlers; // @synthesize actionHandlers=_actionHandlers;
@property(retain, nonatomic) NSMutableDictionary *reachabilityHandlers; // @synthesize reachabilityHandlers=_reachabilityHandlers;
@property(retain, nonatomic) NSMutableArray *gestureOverrides; // @synthesize gestureOverrides=_gestureOverrides;
@property(copy, nonatomic) CDUnknownBlockType currentAlertHandler; // @synthesize currentAlertHandler=_currentAlertHandler;
- (BOOL)hasActiveCall;
- (int)activeInterfaceOrientation;
- (id)init;
- (void)dealloc;
@property(retain, nonatomic) AXAccessQueue *accessQueue; // @synthesize accessQueue=_accessQueue;
- (BOOL)isNotificationCenterVisible;
- (BOOL)isScreenLockedWithPasscode:(char *)arg1;

@end

