//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MPURatingControlDelegate.h"

@class MPAVItem, MPMediaItem, MusicFlipsideAlbumDetailHeaderView, NSString, UISegmentedControl, UIView;

@interface MusicFlipsideTracksViewController : UIViewController <MPURatingControlDelegate>
{
    MPMediaItem *_currentMediaItem;
    MPAVItem *_currentAVItem;
    UIView *_container;
    MusicFlipsideAlbumDetailHeaderView *_trackInfoView;
    UISegmentedControl *_segmentedControl;
    BOOL _showingRating;
    BOOL _hasPlaylist;
}

- (void)_contentSizeCategoryDidChangeNotification:(id)arg1;
- (BOOL)shouldShowActionCellConfiguration:(Class)arg1;
@property(nonatomic) BOOL hasPlaylist; // @synthesize hasPlaylist=_hasPlaylist;
- (void)_selectedSegmentDidChange:(id)arg1;
- (void)_setShowingRating:(BOOL)arg1;
- (void)_updateMediaItem;
- (void)_performRating:(id)arg1;
- (void)_performDone:(id)arg1;
- (void)ratingDidChangeForRatingControl:(id)arg1;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)contentScrollView;
- (void)viewWillAppear:(BOOL)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (void)_itemDidChangeNotification:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

