//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDAttribute, NSString;

@interface DADuetReporter : NSObject
{
    CDAttribute *_attribute;
    NSString *_value;
}

+ (id)session;
- (void)activityStopped;
- (void)activityStarted;
- (id)initWithActivityIdentifier:(id)arg1;
- (void).cxx_destruct;

@end

