//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaPlayer/MPRemotePlaybackQueue.h>

@class NSArray;

@interface MPiTunesStoreTracklistPlaybackQueue : MPRemotePlaybackQueue
{
    NSArray *_storeIDs;
    unsigned int _shuffleType;
}

- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) NSArray *storeIDs; // @synthesize storeIDs=_storeIDs;
- (id)initWithMediaRemotePlaybackQueue:(struct _MRSystemAppPlaybackQueue *)arg1;
@property(readonly, nonatomic) unsigned int shuffleType; // @synthesize shuffleType=_shuffleType;

@end

