//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MPAVPlaylistFeeder.h"

@class MPAVController, NSDictionary, NSString;

@interface MPQueueFeeder : NSObject <MPAVPlaylistFeeder>
{
    MPAVController *_avController;
    struct __CFSet *_itemsWithReferencesToClear;
    unsigned int _repeatType;
    unsigned int _shuffleType;
    struct __CFDictionary *_nextStartTimes;
    id _representedObject;
    BOOL _fullScreenPlaybackQueue;
    BOOL _isSourceChangeInProgress;
    BOOL _deallocating;
    BOOL _wantsAirPlayVideo;
    unsigned int _activeShuffleType;
}

+ (void)restoreAVControllerPlaybackQueue:(id)arg1 fromUnarchiver:(id)arg2 feederClass:(Class)arg3;
- (BOOL)canSeek;
@property(readonly, nonatomic) unsigned int itemCount;
@property(retain, nonatomic) id <NSObject> representedObject; // @synthesize representedObject=_representedObject;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *preferredLanguages;
@property(readonly, nonatomic) Class itemClass;
- (void)dealloc;
@property(readonly, nonatomic) BOOL wantsAirPlayVideo; // @synthesize wantsAirPlayVideo=_wantsAirPlayVideo;
@property(nonatomic) BOOL fullScreenPlaybackQueue; // @synthesize fullScreenPlaybackQueue=_fullScreenPlaybackQueue;
@property(nonatomic) unsigned int activeShuffleType; // @synthesize activeShuffleType=_activeShuffleType;
@property(nonatomic) unsigned int shuffleType; // @synthesize shuffleType=_shuffleType;
@property(nonatomic) unsigned int repeatType; // @synthesize repeatType=_repeatType;
@property(nonatomic) __weak MPAVController *AVController; // @synthesize AVController=_avController;
- (void)getContainerType:(unsigned int *)arg1 mediaLibraryContainerPersistentID:(long long *)arg2 storeContainerID:(id *)arg3 storePersonalizedContainerID:(id *)arg4;
- (void)archiveAVControllerPlaybackQueue:(id)arg1 toArchiver:(id)arg2;
- (void)controller:(id)arg1 willChangePlaybackIndexBy:(int)arg2 deltaType:(int)arg3 ignoreElapsedTime:(BOOL)arg4 allowSkippingUnskippableContent:(BOOL)arg5;
@property(readonly, nonatomic) unsigned int realShuffleType;
@property(readonly, nonatomic) unsigned int realRepeatType;
@property(readonly, nonatomic) BOOL userCanChangeShuffleAndRepeatType;
@property(readonly, nonatomic) BOOL trackChangesCanEndPlayback;
- (CDStruct_e0453228)skipLimit;
@property(readonly, nonatomic) BOOL playerPreparesItemsForPlaybackAsynchronously;
- (unsigned int)itemTypeForIndex:(unsigned int)arg1;
- (BOOL)canSkipToPreviousItem;
- (BOOL)canSkipItem:(id)arg1;
@property(readonly, nonatomic) BOOL allowsUserVisibleUpcomingItems;
- (BOOL)shouldBeginPlaybackOfItem:(id)arg1 error:(id *)arg2;
- (id)errorResolverForItem:(id)arg1;
- (void)commitSourceChangeWithStartQueueIndex:(unsigned int)arg1;
- (void)beginSourceChange;
- (BOOL)reloadWithDataSource:(id)arg1;
- (void)shuffleItemsWithAnchor:(unsigned int *)arg1;
- (void)setNextStartTime:(double)arg1 forIndex:(unsigned int)arg2;
- (void)_fixNextStartTimesByInsertingRange:(struct _NSRange)arg1;
- (BOOL)shouldReloadForChangeFromNetworkType:(int)arg1 toNetworkType:(int)arg2;
- (id)itemForIndex:(unsigned int)arg1;
- (BOOL)hasItemForIndex:(unsigned int)arg1;
- (unsigned int)initialPlaybackQueueDepthForStartingIndex:(unsigned int)arg1;
- (void)assumeOwnershipOfItems:(id)arg1;
- (void)restoreAVControllerPlaybackQueue:(id)arg1 fromUnarchiver:(id)arg2;
- (BOOL)_canPurgeNextStartTimes;
- (void)contentInvalidated;
- (void)contentInvalidatedWithCurrentItemMovedToIndex:(unsigned int)arg1;
@property(nonatomic) BOOL isSourceChangeInProgress; // @synthesize isSourceChangeInProgress=_isSourceChangeInProgress;
- (void)contentsDidChangeByRemovingRange:(struct _NSRange)arg1;
- (void)_fixNextStartTimesByRemovingRange:(struct _NSRange)arg1;
- (BOOL)hasValidItemAtIndex:(unsigned int)arg1;
- (void)addReferenceToItem:(id)arg1;
- (void)invalidateQueueCaches;
- (BOOL)reloadWithDataSource:(id)arg1 keepPlayingCurrentItemIfPossible:(BOOL)arg2;
- (id)localizedPositionInPlaylistString:(id)arg1;
- (id)localizedAttributedPositionInPlaylistStringForItem:(id)arg1 withRegularTextAttributes:(id)arg2 emphasizedTextAttributes:(id)arg3;
- (void)clearReferencesToItem:(id)arg1;
- (id)pathAtIndex:(unsigned int)arg1;
- (id)playbackInfoAtIndex:(unsigned int)arg1;
- (id)copyRawItemAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) int playbackMode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

