//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPRemoteCommand, NSDictionary;

@interface MPRemoteCommandEvent : NSObject
{
    NSDictionary *_mediaRemoteOptions;
    MPRemoteCommand *_command;
    double _timestamp;
}

+ (id)eventWithCommand:(id)arg1 mediaRemoteType:(unsigned int)arg2 options:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (id)init;
@property(readonly, nonatomic) MPRemoteCommand *command; // @synthesize command=_command;
- (id)mediaRemoteOptions;
- (id)initWithCommand:(id)arg1 mediaRemoteType:(unsigned int)arg2 options:(id)arg3;

@end

