//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CalendarEventLoaderDelegate.h"

@class CalendarEventLoader, EKCalendarDate, EKEvent, EKEventStore, NSArray, NSCalendar, NSLock, NSSet, NSString, _EKNotificationMonitor;

@interface CalendarModel : NSObject <CalendarEventLoaderDelegate>
{
    EKEventStore *_eventStore;
    CalendarEventLoader *_eventLoader;
    NSLock *_filterLock;
    NSArray *_visibleCalendars;
    int _readWriteCalendarCount;
    int _invitationBearingStoresExist;
    _EKNotificationMonitor *_notificationMonitor;
    id <OccurrenceCacheDataSourceProtocol> _occurrenceCacheDataSource;
    id <OccurrenceCacheDataSourceProtocol> _occurrenceCacheFilteredDataSource;
    int _cachedFakeTodayIndex;
    NSSet *_selectedCalendars;
    NSString *_searchString;
    NSCalendar *_calendar;
    EKCalendarDate *_selectedDate;
    unsigned int _firstVisibleSecond;
    EKEvent *_selectedOccurrence;
}

- (void)_localeChanged:(id)arg1;
- (void)_significantTimeChange:(id)arg1;
@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
- (void).cxx_destruct;
@property(copy, nonatomic) NSCalendar *calendar; // @synthesize calendar=_calendar;
- (double)_tomorrow;
- (id)init;
- (void)dealloc;
@property(copy, nonatomic) EKCalendarDate *selectedDate; // @synthesize selectedDate=_selectedDate;
- (BOOL)searchingOccurrences;
- (unsigned int)eventNotificationsCount;
- (BOOL)invitationBearingStoresExistForEvents;
- (BOOL)removeEvent:(id)arg1 withSpan:(int)arg2 error:(id *)arg3;
- (void)_systemWake;
- (void)prepareForAppSuspend;
- (void)updateAfterAppResume;
- (void)_occurrenceCacheChanged;
- (void)fetchCachedDaysInBackgroundStartingFromSection:(int)arg1;
- (int)sectionForCachedOccurrencesOnDate:(id)arg1 usingFilter:(BOOL)arg2;
- (int)numberOfCachedOccurrencesInSection:(int)arg1;
- (int)numberOfDaysWithCachedOccurrences;
- (void)setMaxCachedDays:(unsigned int)arg1;
- (void)setDesiredPaddingDays:(unsigned int)arg1;
- (id)closestOccurrenceToTomorrowForEventUID:(int)arg1;
- (id)selectedDateOccurrences:(BOOL)arg1 loadIsComplete:(char *)arg2;
- (id)occurrencesForStartDay:(id)arg1 endDay:(id)arg2 preSorted:(BOOL)arg3 waitForLoad:(BOOL)arg4;
@property(readonly, nonatomic) EKCalendarDate *selectedDay;
- (void)refreshCalendarDataIfNeeded:(BOOL)arg1;
- (void)refreshAccountListIfNeeded:(BOOL)arg1;
- (BOOL)isCalendarVisibleWithID:(id)arg1;
- (void)ensureCalendarVisibleWithId:(id)arg1;
@property(readonly, nonatomic) int readWriteCalendarCount;
- (BOOL)selectedOccurrenceIsSearchMatch;
- (void)_notificationCountExpired:(id)arg1;
- (void)_notificationsExpired:(id)arg1;
- (void)_reloadIfTodayDetermined;
- (id)_notificationMonitor;
- (void)startNotificationMonitor;
- (void)_invalidateCachedOccurrences;
- (void)fetchCachedDaysInBackgroundStartingFromSection:(int)arg1 usingFilter:(BOOL)arg2;
- (int)sectionForCachedOccurrencesOnDate:(id)arg1 sectionExistsForDay:(char *)arg2;
- (int)cachedFakeTodayIndex;
- (int)sectionForCachedOccurrencesOnDate:(id)arg1 sectionExistsForDay:(char *)arg2 usingFilter:(BOOL)arg3;
- (id)cachedOccurrenceAtIndexPath:(id)arg1;
- (id)cachedOccurrenceAtIndexPath:(id)arg1 usingFilter:(BOOL)arg2;
- (id)dateForCachedOccurrencesInSection:(int)arg1 usingFilter:(BOOL)arg2;
- (int)numberOfCachedOccurrencesInSection:(int)arg1 usingFilter:(BOOL)arg2;
- (id)dateForCachedOccurrencesInSection:(int)arg1;
- (int)sectionForCachedOccurrencesOnDate:(id)arg1;
- (id)_dataSourceUsingFilter:(BOOL)arg1;
- (int)numberOfDaysWithCachedOccurrencesUsingFilter:(BOOL)arg1;
- (BOOL)cachedOccurrencesAreLoaded;
- (BOOL)cachedOccurrencesAreBeingGenerated;
- (id)occurrencesForDay:(id)arg1 waitForLoad:(BOOL)arg2;
@property(retain, nonatomic) NSSet *selectedCalendars; // @synthesize selectedCalendars=_selectedCalendars;
- (void)_processReloadForCacheOnly:(BOOL)arg1 includingCalendars:(BOOL)arg2 checkCalendarsValid:(BOOL)arg3;
- (void)_recreateOccurrenceCacheDataSources;
@property(retain, nonatomic) EKEvent *selectedOccurrence; // @synthesize selectedOccurrence=_selectedOccurrence;
- (void)_invalidateOccurrenceCacheDataSources;
- (void)_searchResultsAvailable:(id)arg1;
- (void)_tzSupportTodayRolledOver;
- (void)_createOccurrenceCacheDataSources;
@property(readonly, nonatomic) int visibleCalendarCount;
- (id)occurrencesForStartDate:(id)arg1 endDate:(id)arg2 preSorted:(BOOL)arg3 waitForLoad:(BOOL)arg4;
- (void)setPreferredReloadStartDate:(id)arg1 endDate:(id)arg2;
- (void)setComponentForExpandingPadding:(unsigned int)arg1;
- (void)setComponentForExpandingRequests:(unsigned int)arg1;
- (void)addOccurrenceAwaitingDeletion:(id)arg1;
- (void)addOccurrenceAwaitingRefresh:(id)arg1;
- (void)calendarEventLoader:(id)arg1 occurrencesDidUpdateBetweenStart:(double)arg2 end:(double)arg3;
@property(nonatomic) unsigned int firstVisibleSecond; // @synthesize firstVisibleSecond=_firstVisibleSecond;
- (void)_eventStoreChanged:(id)arg1;
- (id)eventNotificationReferences;
- (void)_timeZoneChanged:(id)arg1;
- (id)defaultCalendarForNewEvents;
@property(readonly, nonatomic) EKEventStore *eventStore; // @synthesize eventStore=_eventStore;

@end

