//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <EventKitUI/EKEventDetailItem.h>

#import "MKMapViewDelegate.h"

@class MKMapView, NSString, UITableViewCell, UIView;

@interface EKEventMapDetailItem : EKEventDetailItem <MKMapViewDelegate>
{
    UITableViewCell *_cell;
    MKMapView *_mapView;
    UIView *_overlayView;
    UIView *_loadingView;
}

- (void).cxx_destruct;
- (void)mapViewDidFinishRenderingMap:(id)arg1 fullyRendered:(BOOL)arg2;
- (void)mapViewWillStartRenderingMap:(id)arg1;
- (void)_setAnnotationForEventLocation;
- (float)_mapHeight;
- (void)eventViewController:(id)arg1 didSelectReadOnlySubitem:(unsigned int)arg2;
- (void)eventViewController:(id)arg1 didUnhighlightSubitem:(unsigned int)arg2;
- (void)eventViewController:(id)arg1 didHighlightSubitem:(unsigned int)arg2;
- (float)defaultCellHeightForSubitemAtIndex:(unsigned int)arg1 forWidth:(float)arg2;
- (id)cellForSubitemAtIndex:(unsigned int)arg1;
- (BOOL)configureWithCalendar:(id)arg1 preview:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

