//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIDocumentInteractionControllerDelegate.h"

@class EKAttachment, EKEventAttachmentCell, NSString;

@interface EKEventAttachmentCellController : NSObject <UIDocumentInteractionControllerDelegate>
{
    id _downloadID;
    EKEventAttachmentCell *_cell;
    BOOL _sourceIsManaged;
    EKAttachment *_attachment;
    id <EKEventAttachmentCellControllerDelegate> _delegate;
}

+ (BOOL)_attachmentIsViewable:(id)arg1;
+ (id)cellControllersForAttachments:(id)arg1 givenExistingControllers:(id)arg2;
- (void)tearDown;
@property(retain, nonatomic) EKAttachment *attachment; // @synthesize attachment=_attachment;
@property(nonatomic) BOOL sourceIsManaged; // @synthesize sourceIsManaged=_sourceIsManaged;
- (id)documentInteractionControllerViewForPreview:(id)arg1;
- (id)documentInteractionControllerViewControllerForPreview:(id)arg1;
- (void)documentInteractionControllerWillEndPreview:(id)arg1;
- (void).cxx_destruct;
@property(readonly) EKEventAttachmentCell *cell; // @synthesize cell=_cell;
@property(nonatomic) __weak id <EKEventAttachmentCellControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_presentPreviewOnMainThreadWithInfo:(id)arg1;
- (id)_downloadProgressStringWithDownloadedBytes:(id)arg1 outOfTotalBytes:(id)arg2;
- (void)_presentPreviewWithURL:(id)arg1 filename:(id)arg2;
- (void)_clearDownloadID;
- (id)initWithAttachment:(id)arg1;
- (void)cellSelected;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

