//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <EventKitUI/EKReminderEditItem.h>

#import "EKExpandingTextViewDelegate.h"

@class EKReminderInlineEditItemCell, NSString;

@interface EKReminderInlineEditItem : EKReminderEditItem <EKExpandingTextViewDelegate>
{
    EKReminderInlineEditItemCell *_cell;
    BOOL _isListeningToHeightChanges;
}

- (int)cellStyle;
- (void).cxx_destruct;
- (void)_keyboardDidShow:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)shouldPinKeyboard;
- (BOOL)isInline;
- (void)textViewDidChangeContentHeight:(id)arg1;
- (id)textFromReminder;
- (id)newCell;
- (void)_applyStylesFromStyleProviderToTextView:(id)arg1;
- (void)addStylingToCell:(id)arg1 forSubitemAtIndex:(unsigned int)arg2;
- (float)defaultCellHeightForSubitemAtIndex:(unsigned int)arg1 forWidth:(float)arg2;
- (id)cellForSubitemAtIndex:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

