//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray, UIActivityIndicatorView, UIColor, UILabel;

@interface EKUIInviteesViewConflictSearchCell : UITableViewCell
{
    UILabel *_label;
    NSArray *_persistentConstraints;
    float _leftInset;
    UIActivityIndicatorView *_spinner;
    UIColor *_originalLabelFontColor;
}

+ (id)_labelFont;
+ (id)_grayTextColor;
@property(nonatomic) float leftInset; // @synthesize leftInset=_leftInset;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void)updateConstraints;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)_setText:(id)arg1 textColor:(id)arg2 spinnerEnabled:(BOOL)arg3;
@property(retain, nonatomic) UIColor *originalLabelFontColor; // @synthesize originalLabelFontColor=_originalLabelFontColor;
- (void)setShowMoreState;
- (void)setAvailabilityRequestInProgressState;
- (void)setNoAvailableTimesStateWithNumberOfExistingTimes:(unsigned int)arg1;
- (void)setInitialSearchInProgressState;
@property(retain, nonatomic) NSArray *persistentConstraints; // @synthesize persistentConstraints=_persistentConstraints;

@end

