//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CTCarrier, NSDictionary, NSLock, NSString;

@interface CTTelephonyNetworkInfo : NSObject
{
    struct queue _queue;
    struct __CTServerConnection *server_connection;
    NSLock *server_lock;
    CDUnknownBlockType _subscriberCellularProviderDidUpdateNotifier;
    BOOL _monitoringCellId;
    CTCarrier *_subscriberCellularProvider;
    NSString *_cachedCurrentRadioAccessTechnology;
    NSDictionary *_cachedSignalStrength;
    NSString *_cachedCellId;
}

- (id)signalStrength;
- (void).cxx_destruct;
- (id).cxx_construct;
- (id)init;
- (void)dealloc;
- (id)radioAccessTechnology;
@property(retain, nonatomic) NSString *cellId;
@property(readonly, retain, nonatomic) NSString *currentRadioAccessTechnology;
- (void)handleNotificationFromConnection:(void *)arg1 ofType:(id)arg2 withInfo:(id)arg3;
@property(copy, nonatomic) CDUnknownBlockType subscriberCellularProviderDidUpdateNotifier;
@property(retain) NSString *cachedCellId; // @synthesize cachedCellId=_cachedCellId;
- (void)queryCellId;
@property BOOL monitoringCellId; // @synthesize monitoringCellId=_monitoringCellId;
@property(retain) NSDictionary *cachedSignalStrength; // @synthesize cachedSignalStrength=_cachedSignalStrength;
@property(retain) NSString *cachedCurrentRadioAccessTechnology; // @synthesize cachedCurrentRadioAccessTechnology=_cachedCurrentRadioAccessTechnology;
- (id)createSignalStrengthDictWithBars:(id)arg1;
- (void)handleCTRegistrationCellChangedNotification:(id)arg1;
- (void)handleCTSignalStrengthNotification:(id)arg1;
- (void)updateSignalStrength:(id)arg1;
- (void)updateRadioAccessTechnology:(id)arg1;
- (void)postCellularProviderUpdatesIfNecessary;
- (BOOL)getAllowsVOIP:(char *)arg1 withCTError:(CDStruct_1ef3fb1f *)arg2;
- (BOOL)getMobileNetworkCode:(id)arg1 withCTError:(CDStruct_1ef3fb1f *)arg2;
- (BOOL)getMobileCountryCode:(id)arg1 andIsoCountryCode:(id)arg2 withCTError:(CDStruct_1ef3fb1f *)arg3;
- (BOOL)getCarrierName:(id)arg1 withCTError:(CDStruct_1ef3fb1f *)arg2;
@property(retain) CTCarrier *subscriberCellularProvider; // @synthesize subscriberCellularProvider=_subscriberCellularProvider;
- (void)cleanUpServerConnection;
- (void)queryCTSignalStrengthNotification;
- (void)queryDataMode;
- (BOOL)updateNetworkInfoAndShouldNotifyClient:(char *)arg1;
- (BOOL)setUpServerConnection;

@end

