//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, SSAccount, SSKeyValueStore;

@interface SSAccountStore : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    SSKeyValueStore *_keyValueStore;
    NSObject<OS_dispatch_queue> *_notificationQueue;
    NSMutableArray *_notifyTokens;
}

+ (id)existingDefaultStore;
+ (void)resetExpiration;
+ (void)setDefaultStore:(id)arg1;
+ (double)tokenExpirationInterval;
+ (void)resetExpirationForTokenType:(int)arg1;
+ (BOOL)isExpiredForTokenType:(int)arg1;
+ (BOOL)isExpired;
+ (id)defaultStore;
- (void)resetExpiration;
- (id)setActiveLockerAccount:(id)arg1;
- (id)setActiveAccount:(id)arg1;
- (id)accountWithUniqueIdentifier:(id)arg1;
- (void)signOutAllAccounts;
- (void)_postAccountStoreChangeNotification;
- (void)_dispatchSync:(CDUnknownBlockType)arg1;
- (void)_dispatchAsync:(CDUnknownBlockType)arg1;
- (void)setDefaultAccountName:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setAccountCredits:(id)arg1 forAccountWithUniqueIdentifier:(id)arg2;
@property(readonly, getter=isAuthenticationActive) BOOL authenticationActive;
- (void)getDefaultAccountNameUsingBlock:(CDUnknownBlockType)arg1;
- (id)accountWithUniqueIdentifier:(id)arg1 reloadIfNecessary:(BOOL)arg2;
- (id)accountWithUniqueIdentifier:(id)arg1 scope:(int)arg2;
- (void)resetExpirationForTokenType:(int)arg1;
- (BOOL)isExpiredForTokenType:(int)arg1;
- (id)_keyValueStore;
- (void)signOutAccount:(id)arg1;
- (id)addAccount:(id)arg1;
- (void)reloadAccounts;
@property(readonly, copy) NSArray *accounts;
@property(readonly, getter=isExpired) BOOL expired;
- (id)init;
- (void)dealloc;
@property(readonly) SSAccount *activeLockerAccount;
@property(readonly) SSAccount *activeAccount;

@end

