//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SSURLConnectionRequestDelegate.h"

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSNumber, NSString, NSURL, SSItemImageCollection, SSItemOffer, SSURLConnectionRequest;

@interface SSItem : NSObject <SSURLConnectionRequestDelegate>
{
    NSDate *_expirationDate;
    NSArray *_offers;
    NSDictionary *_properties;
    NSString *_tellAFriendBody;
    NSString *_tellAFriendBodyMIMEType;
    NSMutableArray *_tellAFriendHandlers;
    SSURLConnectionRequest *_tellAFriendRequest;
    NSString *_tellAFriendSubject;
}

- (id)genreName;
@property(readonly, nonatomic, getter=isGameCenterEnabled) BOOL gameCenterEnabled;
- (id)tweetURL;
- (id)tweetInitialText;
- (id)tellAFriendSubject;
- (id)tellAFriendBodyURL;
- (id)tellAFriendBodyMIMEType;
- (id)tellAFriendBody;
- (id)relatedItemsForRelationType:(id)arg1;
- (id)playableMedia;
- (id)initWithItemDictionary:(id)arg1;
- (id)priceDisplay;
- (id)softwareType;
@property(readonly, nonatomic) float averageUserRating;
- (id)viewReviewsURL;
- (id)sendGiftURL;
@property(readonly, nonatomic) NSURL *viewItemURL;
@property(readonly, nonatomic) NSArray *thumbnailImages;
- (int)numberOfPrintedPages;
- (void)loadTellAFriendMessageWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSArray *allItemOffers;
- (void)_finishTellAFriendLoadWithError:(id)arg1;
- (id)_tellAFriendDictionary;
- (id)_offers;
- (void)urlConnectionRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (id)itemOfferForIdentifier:(id)arg1;
- (id)rawItemDictionary;
@property(readonly, nonatomic) SSItemImageCollection *imageCollection;
- (id)videoDetails;
- (id)seriesName;
- (id)podcastEpisodeGUID;
- (id)numberOfItemsInCollection;
- (id)numberOfCollectionsInCollectionGroup;
- (id)genreIdentifier;
- (id)episodeSortIdentifier;
- (id)episodeIdentifier;
- (id)composerName;
- (id)collectionIndexInCollectionGroup;
- (id)collectionArtistName;
- (id)artistIdentifier;
- (id)preOrderIdentifier;
@property(readonly, nonatomic) SSItemOffer *defaultItemOffer;
- (id)podcastFeedURL;
- (id)indexInCollection;
@property(readonly, nonatomic, getter=isHighDefinition) BOOL highDefinition;
@property(readonly, nonatomic, getter=isRestricted) BOOL restricted;
- (id)releaseDateString;
@property(readonly, nonatomic) int numberOfUserRatings;
@property(readonly, nonatomic) NSString *itemKind;
@property(readonly, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
- (id)collectionIdentifier;
- (id)collectionName;
- (id)longDescription;
@property(readonly, nonatomic) NSNumber *ITunesStoreIdentifier;
@property(readonly, nonatomic) NSString *artistName;
- (id)contentRating;
- (id)networkName;
- (id)seasonNumber;
- (id)bundleVersion;
- (void)_setExpirationDate:(id)arg1;
- (id)valueForProperty:(id)arg1;
- (id)shortDescription;
@property(readonly, nonatomic) NSString *itemTitle;
- (id)bundleIdentifier;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (void)requestDidFinish:(id)arg1;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (id)releaseDate;
- (BOOL)isCompilation;
- (id)buyParameters;
- (id)mediaKind;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

