//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreServices/SSMetricsEvent.h>

#import "NSMutableCopying.h"

@class NSDictionary, NSMutableDictionary;

@interface SSMetricsMutableEvent : SSMetricsEvent <NSMutableCopying>
{
    NSMutableDictionary *_mutableBody;
}

- (void)addPropertiesWithDictionary:(id)arg1;
- (void)appendPropertiesToBody:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *bodyDictionary; // @synthesize bodyDictionary=_mutableBody;
- (id)initWithBodyDictionary:(id)arg1;
- (id)propertyForBodyKey:(id)arg1;
- (void)setProperty:(id)arg1 forBodyKey:(id)arg2;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)debugDescription;
- (id)init;
- (void)dealloc;

@end

