//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface SSSQLiteDatabase : NSObject
{
    struct sqlite3 *_db;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSString *_databasePath;
    BOOL _readOnly;
    BOOL _isInTransaction;
    CDUnknownBlockType _setupBlock;
    struct __CFDictionary *_statementCache;
    BOOL _takesTaskCompletionAssertions;
    struct SBSProcessAssertion *_taskAssertion;
    int _taskAssertionCount;
}

+ (void)_setTakesTaskCompletionAssertions:(BOOL)arg1;
+ (BOOL)statementDidFinishAfterStepping:(struct sqlite3_stmt *)arg1;
+ (void)_stepStatement:(struct sqlite3_stmt *)arg1 hasRow:(char *)arg2 didFinish:(char *)arg3 isCorrupt:(char *)arg4;
+ (BOOL)statementHasRowAfterStepping:(struct sqlite3_stmt *)arg1;
@property(copy, nonatomic) CDUnknownBlockType setupBlock; // @synthesize setupBlock=_setupBlock;
@property BOOL takesTaskCompletionAssertions;
- (void)endTaskCompletionAssertion;
- (void)beginTaskCompletionAssertion;
- (id)newDispatchSourceWithType:(struct dispatch_source_type_s *)arg1;
- (void)dispatchBlockSync:(CDUnknownBlockType)arg1;
- (void)dispatchAfter:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (int)countChanges;
- (void)accessDatabaseUsingBlock:(CDUnknownBlockType)arg1;
- (BOOL)statementDidFinishAfterStepping:(struct sqlite3_stmt *)arg1;
- (BOOL)_resetDatabaseWithPath:(id)arg1;
- (int)_resetAndReopenDatabaseWithPath:(id)arg1;
- (int)_openFlags;
- (int)userVersionForDatabase:(id)arg1;
- (BOOL)setUserVersion:(int)arg1 forDatabase:(id)arg2;
- (struct sqlite3_stmt *)_statementForSQL:(id)arg1 cache:(BOOL)arg2;
- (void)_resetCorruptDatabase;
- (void)_accessDatabaseUsingBlock:(CDUnknownBlockType)arg1;
- (void)_endTaskCompletionAssertion;
- (void)_beginTaskCompletionAssertion;
- (void)dispatchBlockAsync:(CDUnknownBlockType)arg1;
- (id)initWithDatabaseURL:(id)arg1 readOnly:(BOOL)arg2;
- (void)prepareStatementForSQL:(id)arg1 cache:(BOOL)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (BOOL)statementHasRowAfterStepping:(struct sqlite3_stmt *)arg1;
- (id)initWithDatabaseURL:(id)arg1;
- (int)_openDatabase;
- (void)performTransactionWithBlock:(CDUnknownBlockType)arg1;
- (BOOL)executeSQL:(id)arg1;
- (BOOL)setUserVersion:(int)arg1;
- (int)userVersion;
- (void)dealloc;

@end

