//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PLQMIClient : NSObject
{
}

+ (id)sharedQMIClient;
+ (id)fullNameFromServiceCode:(id)arg1;
+ (id)shortNameFromServiceCode:(id)arg1;
- (id)getBasebandTime;
- (id)getLTESleepManagerStats;
- (id)getBasebandTimeWithAPTimestamp:(id *)arg1;
- (id)init;
- (void)dealloc;

@end

