//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudKit/CKOperation.h>

@class NSArray, NSMutableDictionary;

@interface CKFetchShareInfoOperation : CKOperation
{
    NSArray *_shareURLs;
    CDUnknownBlockType _perShareInfoBlock;
    CDUnknownBlockType _fetchShareInfoCompletionBlock;
    NSMutableDictionary *_shareInfoByURL;
    NSMutableDictionary *_errorsByURL;
}

- (void)_finishOnCallbackQueueWithError:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType fetchShareInfoCompletionBlock; // @synthesize fetchShareInfoCompletionBlock=_fetchShareInfoCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType perShareInfoBlock; // @synthesize perShareInfoBlock=_perShareInfoBlock;
- (id)initWithShareURLs:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *errorsByURL; // @synthesize errorsByURL=_errorsByURL;
@property(retain, nonatomic) NSMutableDictionary *shareInfoByURL; // @synthesize shareInfoByURL=_shareInfoByURL;
@property(retain, nonatomic) NSArray *shareURLs; // @synthesize shareURLs=_shareURLs;
- (void)_handleProgressCallback:(id)arg1;
- (void)performCKOperation;
- (BOOL)CKOperationShouldRun:(id *)arg1;
- (void)fillOutOperationInfo:(id)arg1;

@end

