//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSMutableArray, NSString;

@interface AlarmManager : NSObject
{
    NSString *_defaultSound;
    int _defaultSoundType;
    BOOL _dirty;
    NSMutableArray *_alarms;
    BOOL invalidAlarmsDetected;
    NSMutableArray *logMessageList;
    NSDate *lastModified;
}

+ (id)sharedManager;
+ (BOOL)discardOldVersion;
+ (BOOL)upgrade;
+ (BOOL)isAlarmNotification:(id)arg1;
+ (void)writeAlarmsToPreferences:(id)arg1;
+ (id)copyReadAlarmsFromPreferences;
@property(retain, nonatomic) NSDate *lastModified; // @synthesize lastModified;
@property(nonatomic) BOOL invalidAlarmsDetected; // @synthesize invalidAlarmsDetected;
@property(retain, nonatomic) NSMutableArray *logMessageList; // @synthesize logMessageList;
- (void)handleExpiredOrSnoozedNotificationsOnly:(id)arg1;
- (void)handleAnyNotificationChanges;
- (void)reloadScheduledNotifications;
- (void)loadScheduledNotifications;
- (void)handleAlarm:(id)arg1 startedUsingSong:(id)arg2;
- (void)setAlarm:(id)arg1 active:(BOOL)arg2;
- (void)addAlarm:(id)arg1 active:(BOOL)arg2;
- (id)nextAlarmForDate:(id)arg1 activeOnly:(BOOL)arg2 allowRepeating:(BOOL)arg3;
- (id)alarmWithIdUrl:(id)arg1;
- (id)alarmWithId:(id)arg1;
- (BOOL)checkIfAlarmsModified;
- (void)loadAlarms;
- (void)setDefaultSound:(id)arg1 ofType:(int)arg2;
@property(readonly, nonatomic) int defaultSoundType;
@property(readonly, nonatomic) NSString *defaultSound;
- (void)handleNotificationSnoozed:(id)arg1;
- (void)handleNotificationFired:(id)arg1;
- (void)reloadScheduledNotificationsWithRefreshActive:(BOOL)arg1 cancelUnused:(BOOL)arg2;
- (void)loadScheduledNotificationsWithCancelUnused:(BOOL)arg1;
- (void)handleAlarm:(id)arg1 stoppedUsingSong:(id)arg2;
- (void)saveAlarms;
- (void)updateAlarm:(id)arg1 active:(BOOL)arg2;
- (void)countAlarmsInAggregateDictionary;
- (void)unloadAlarms;
- (void)loadDefaultSoundAndType;
- (id)init;
- (void)dealloc;
- (void)removeAlarm:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *alarms; // @synthesize alarms=_alarms;

@end

