//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSRecursiveLock;

@interface CUTTelephonyManager : NSObject
{
    BOOL _registered;
    NSRecursiveLock *_lock;
    NSMutableSet *_disableFastDormancyTokens;
    void *_suspendDormancyAssertion;
    struct __CTServerConnection *_serverConnection;
}

+ (id)sharedInstance;
@property(nonatomic) void *_suspendDormancyAssertion; // @synthesize _suspendDormancyAssertion;
@property(nonatomic) struct __CTServerConnection *_serverConnection; // @synthesize _serverConnection;
@property(retain, nonatomic) NSMutableSet *disableFastDormancyTokens; // @synthesize disableFastDormancyTokens=_disableFastDormancyTokens;
- (void)__adjustFastDormancyTokens;
- (void)_setFastDormancySuspended:(BOOL)arg1;
- (BOOL)disableFastDormancy;
- (void)_adjustFastDormancyTokens;
- (void)addFastDormancyDisableToken:(id)arg1;
- (void)removeFastDormancyDisableToken:(id)arg1;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
- (id)init;
- (void)dealloc;
@property(nonatomic) BOOL registered; // @synthesize registered=_registered;

@end

