//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class PKPhysicsBody;

@interface PKPhysicsJoint : NSObject <NSCoding>
{
    BOOL _inUse;
    BOOL _implicit;
    struct b2Joint *_baseJoint;
    PKPhysicsBody *_bodyA;
    PKPhysicsBody *_bodyB;
}

- (void)create;
@property(readonly, nonatomic) struct b2JointDef *_jointDef;
@property(nonatomic) struct b2Joint *_joint;
- (void)set_inUse:(BOOL)arg1;
@property(retain, nonatomic) PKPhysicsBody *bodyB; // @synthesize bodyB=_bodyB;
@property(retain, nonatomic) PKPhysicsBody *bodyA; // @synthesize bodyA=_bodyA;
- (void).cxx_destruct;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) float reactionTorque;
@property(readonly, nonatomic) struct CGVector reactionForce;
- (BOOL)_inUse;
- (void)set_implicit:(BOOL)arg1;
- (BOOL)_implicit;

@end

