//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HSCloudAvailability.h"
#import "RadiosPreferencesDelegate.h"

@class NSObject<OS_dispatch_queue>, NSString, RadiosPreferences;

@interface HSCloudAvailabilityController : NSObject <RadiosPreferencesDelegate, HSCloudAvailability>
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    BOOL _isAirplaneModeActive;
    BOOL _isAutoDownloadOnCellularAllowed;
    BOOL _isCellularDataActive;
    BOOL _isShowingAllMusic;
    BOOL _isShowingAllVideo;
    BOOL _isUpdateInProgress;
    BOOL _isWiFiEnabled;
    BOOL _isNetworkReachable;
    BOOL _canShowCloudMusic;
    BOOL _canShowCloudVideo;
    BOOL _canShowCloudDownloadButtons;
    int _preferencesChangedNotifyToken;
    BOOL _preferencesChangedNotifyTokenIsValid;
    int _networkType;
    RadiosPreferences *_radiosPreferences;
    struct __SCNetworkReachability *reachabilityRef;
}

+ (id)sharedController;
- (void)airplaneModeChanged;
- (void)_setNewIsNetworkReachable:(BOOL)arg1;
- (void)_handleTelephonyNotificationWithName:(id)arg1 userInfo:(id)arg2;
- (BOOL)_hasWiFiCapability;
- (BOOL)_hasCellularCapability;
- (void)_wifiEnabledDidChangeNotification:(id)arg1;
- (void)_onQueue_updateCanShowCloudTracksWithNotification:(BOOL)arg1;
- (void)_onQueue_updateCanShowCloudDownloadButtonsWithNotification:(BOOL)arg1;
- (BOOL)_uncachedIsShowingAllVideo;
- (BOOL)_uncachedIsShowingAllMusic;
- (void)_cellularNetworkAllowedDidChangeNotification:(id)arg1;
- (BOOL)_uncachedIsAutoDownloadOnCellularAllowed;
- (BOOL)_isAutoDownloadOnCellularAllowed;
- (BOOL)isNetworkReachable;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)_networkTypeDidChangeNotification:(id)arg1;
- (BOOL)canShowCloudDownloadButtons;
- (BOOL)shouldProhibitActionsForCurrentNetworkConditions;
- (BOOL)hasProperNetworkConditionsToPlayMedia;
- (BOOL)canShowCloudVideo;
- (BOOL)canShowCloudMusic;
- (BOOL)isCellularDataRestricted;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

