//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <BulletinDistributorCompanion/BLTRemoteObject.h>

#import "BLTGizmoClient.h"

@class NSString;

@interface BLTRemoteGizmoClient : BLTRemoteObject <BLTGizmoClient>
{
    id <BLTCompanionServer> _server;
}

@property(nonatomic) __weak id <BLTCompanionServer> server; // @synthesize server=_server;
- (void)addBulletin:(id)arg1 playLightsAndSirens:(BOOL)arg2;
- (void)handlePairedDeviceIdentifier:(id)arg1;
- (void)addBulletinSummary:(id)arg1;
- (void)cancelBulletinWithPublisherMatchID:(id)arg1 universalSectionID:(id)arg2 feed:(unsigned int)arg3 transmissionDate:(id)arg4 receptionDate:(id)arg5;
- (void)addBulletin:(id)arg1 playLightsAndSirens:(BOOL)arg2 updateType:(unsigned int)arg3 transmissionDate:(id)arg4 receptionDate:(id)arg5;
- (void)removeBulletinWithPublisherBulletinID:(id)arg1 recordID:(id)arg2 sectionID:(id)arg3;
- (void)cancelBulletinWithPublisherMatchID:(id)arg1 universalSectionID:(id)arg2 feed:(unsigned int)arg3;
- (void)addBulletin:(id)arg1 playLightsAndSirens:(BOOL)arg2 updateType:(unsigned int)arg3 withTimeout:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)handleHandlePairedDeviceIdentifierRequest:(id)arg1;
- (void)handleRemoveBulletinRequest:(id)arg1;
- (void)handleDidPlayLightsAndSirensReply:(id)arg1;
- (void)handleSupplementaryActionRequest:(id)arg1;
- (void)handleDismissActionRequest:(id)arg1;
- (void)handleSnoozeActionRequest:(id)arg1;
- (void)handleAcknowledgeActionRequest:(id)arg1;
- (void)registerProtobufHandlers;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

