//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISURLCacheConfiguration, NSString, NSURLCache;

@interface ISURLCache : NSObject
{
    NSURLCache *_cache;
    ISURLCacheConfiguration *_configuration;
}

+ (id)cacheDirectoryPath;
- (void)saveMemoryCacheToDisk;
- (void)purgeMemoryCache;
- (void)reloadWithCacheConfiguration:(id)arg1;
- (id)initWithCacheConfiguration:(id)arg1;
- (void)removeAllCachedResponses;
- (id)init;
- (void)dealloc;
@property(readonly) NSString *persistentIdentifier;
- (void)storeCachedResponse:(id)arg1 forRequest:(id)arg2;
- (id)cachedResponseForRequest:(id)arg1;
@property(readonly, nonatomic) unsigned int currentMemoryUsage;
@property(readonly, nonatomic) unsigned int diskCapacity;
@property(readonly, nonatomic) unsigned int memoryCapacity;
- (void)removeCachedResponseForRequest:(id)arg1;
@property(readonly, nonatomic) unsigned int currentDiskUsage;

@end

