//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ALCity : NSObject
{
    int _identifier;
    NSString *_localeCode;
    NSString *_timeZone;
    float _longitude;
    float _latitude;
    NSString *_yahooCode;
    NSString *_name;
    NSString *_unlocalizedName;
    NSString *_countryName;
    NSString *_unlocalizedCountryName;
    NSString *_countryOverride;
    NSString *_unlocalizedCountryOverride;
    NSString *_identifierForCPCity;
    BOOL _localizationAttempted;
}

@property(retain, nonatomic) NSString *yahooCode; // @synthesize yahooCode=_yahooCode;
@property(retain, nonatomic) NSString *unlocalizedCountryName;
@property(nonatomic) float longitude; // @synthesize longitude=_longitude;
@property(nonatomic) float latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *unlocalizedName;
@property(retain, nonatomic) NSString *unlocalizedCountryOverride; // @synthesize unlocalizedCountryOverride=_unlocalizedCountryOverride;
@property(retain, nonatomic) NSString *localeCode; // @synthesize localeCode=_localeCode;
@property(readonly, nonatomic) NSString *classicIdentifier;
- (void)ensureLocalized;
- (id)displayNameIncludingCountry:(BOOL)arg1 withFormat:(id)arg2;
@property(retain, nonatomic) NSString *countryOverride;
- (id)initWithSQLRow:(char **)arg1;
@property(readonly, nonatomic) NSDictionary *properties;
- (id)initWithProperties:(id)arg1;
@property(retain, nonatomic) NSString *timeZone; // @synthesize timeZone=_timeZone;
@property(nonatomic) int identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *name;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)displayNameIncludingCountry:(BOOL)arg1;
@property(retain, nonatomic) NSString *countryName;

@end

