//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MapKit/MKPlaceHeaderBackgroundView.h>

#import "MKMapViewDelegate.h"

@class CLLocation, MKMapCamera, MKMapView, NSString;

@interface MKPlaceHeaderBackgroundView_Snapshot : MKPlaceHeaderBackgroundView <MKMapViewDelegate>
{
    MKMapView *_mapView;
    BOOL _orbiting;
    BOOL _settingUpOrbitAnimation;
    BOOL _showsPin;
    MKMapCamera *_orbitCamera;
    float _zoomLevel;
    unsigned int _pinColor;
    CLLocation *_location;
}

@property(nonatomic) float zoomLevel; // @synthesize zoomLevel=_zoomLevel;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) unsigned int pinColor; // @synthesize pinColor=_pinColor;
- (void)pause;
- (void).cxx_destruct;
- (void)present;
- (void)resume;
- (void)reset;
- (void)dealloc;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapViewDidFinishRenderingMap:(id)arg1 fullyRendered:(BOOL)arg2;
- (void)mapViewDidFinishLoadingMap:(id)arg1;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)setMapItem:(id)arg1;
@property(nonatomic) BOOL showsPin; // @synthesize showsPin=_showsPin;
- (void)beginOrbit;
@property(retain, nonatomic) MKMapCamera *orbitCamera; // @synthesize orbitCamera=_orbitCamera;
@property(nonatomic) BOOL settingUpOrbitAnimation; // @synthesize settingUpOrbitAnimation=_settingUpOrbitAnimation;
@property(nonatomic) BOOL orbiting; // @synthesize orbiting=_orbiting;
- (void)_orbitNextThird;
- (void)mapFinishedLoading:(BOOL)arg1;
- (void)requestSnapshot;
- (void)pauseOrbit;
@property(readonly, nonatomic) BOOL useSatellite;
- (id)initWithFrame:(struct CGRect)arg1 mapItem:(id)arg2;
- (void)prepareForPresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

