//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SYStoreDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SYStore;

@interface MSPSyncManager : NSObject <SYStoreDelegate>
{
    SYStore *_store;
    BOOL _inUpdate;
    NSObject<OS_dispatch_queue> *_saveQueue;
    NSMutableArray *_bookmarks;
    NSMutableDictionary *_bookmarksMap;
    NSMutableArray *_pins;
    NSMutableDictionary *_pinsMap;
    NSMutableArray *_history;
    NSMutableDictionary *_historyMap;
}

- (void)notifyObservers;
- (id)history;
- (void)transaction:(CDUnknownBlockType)arg1;
- (id)bookmarks;
- (void)updateHistoryItem:(id)arg1 transaction:(id)arg2;
- (void)removeHistoryItem:(id)arg1 transaction:(id)arg2;
- (void)addHistoryItem:(id)arg1 transaction:(id)arg2;
- (void)updatePin:(id)arg1 transaction:(id)arg2;
- (void)removePin:(id)arg1 transaction:(id)arg2;
- (void)addPin:(id)arg1 transaction:(id)arg2;
- (id)pins;
- (void)updateBookmark:(id)arg1 transaction:(id)arg2;
- (void)removeBookmark:(id)arg1 transaction:(id)arg2;
- (void)addBookmark:(id)arg1 transaction:(id)arg2;
- (id)_wrapHistoryItem:(id)arg1;
- (id)_wrapPin:(id)arg1;
- (id)_wrapBookmark:(id)arg1;
- (void)updatedHistoryItem:(id)arg1;
- (void)updatedPin:(id)arg1;
- (void)updatedBookmark:(id)arg1;
- (id)readHistory;
- (id)readPins;
- (id)readBookmarks;
- (void)writeHistory:(id)arg1;
- (void)writePins:(id)arg1;
- (void)writeBookmarks:(id)arg1;
- (void)completedPreparingSync;
- (void)_notifyObservers;
- (void)_removeHistoryItem:(id)arg1;
- (void)_removePin:(id)arg1;
- (void)_removeBookmark:(id)arg1;
- (void)_updateHistoryItem:(id)arg1;
- (void)_updatePin:(id)arg1;
- (void)_updateBookmark:(id)arg1;
- (void)_addHistoryItem:(id)arg1;
- (void)_addPin:(id)arg1;
- (void)_addBookmark:(id)arg1;
- (void)_updateFromDisk;
- (void)syncStore:(id)arg1 objectDeleted:(id)arg2;
- (void)syncStore:(id)arg1 objectUpdated:(id)arg2;
- (void)syncStore:(id)arg1 objectAdded:(id)arg2;
- (void)syncStoreEnqueuedAllFullSyncMessages:(id)arg1 context:(id)arg2;
- (id)syncStoreAllObjects:(id)arg1;
- (void)syncStoreAllObjectsDeleted:(id)arg1;
- (void)syncStoreDidUpdate:(id)arg1;
- (void)syncStoreWillUpdate:(id)arg1 objectCount:(unsigned int)arg2;
- (void)syncStoreWillUpdate:(id)arg1;
- (void)syncStoreDidCompleteFullSync:(id)arg1;
- (void)setNeedsFullSync;
- (void)completedSync;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

