//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CHDDataValuesCollection, CHDFormula, EDResources;

@interface CHDData : NSObject
{
    CHDDataValuesCollection *mDataValues;
    CHDFormula *mFormula;
    unsigned int mContentFormatId;
    unsigned int mDataValueIndexCount;
    EDResources *mResources;
}

+ (id)dataWithResources:(id)arg1;
+ (id)dataWithDataPointCount:(unsigned int)arg1 resources:(id)arg2;
- (id)firstValueContentFormatWithWorkbook:(id)arg1;
- (unsigned int)averageDataPointDecimalCount;
- (unsigned int)dataValueIndexCount;
- (unsigned int)countOfCellsBeingReferenced;
- (id)initWithDataPointCount:(unsigned int)arg1 resources:(id)arg2;
- (void)setContentFormat:(id)arg1;
- (id)initWithResources:(id)arg1;
- (void)setDataValueIndexCount:(unsigned int)arg1;
- (void)setFormula:(id)arg1 chart:(id)arg2;
- (void)setContentFormatId:(unsigned int)arg1;
- (id)formula;
- (id)dataValues;
- (id)contentFormat;
- (unsigned int)contentFormatId;
- (_Bool)isEmpty;
- (void)dealloc;

@end

