//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <OfficeImport/EDFormula.h>

@class EDReferenceCollection, EDWorkbook;

@interface CHDFormula : EDFormula
{
    EDReferenceCollection *mReferences;
    EDWorkbook *mWorkbook;
}

+ (id)formulaWithReference:(id)arg1;
+ (id)formulaWithReferences:(id)arg1;
- (id)initWithWorkbook:(id)arg1;
- (void)setReferences:(id)arg1;
- (void)prepareTokens;
- (_Bool)isConstantStringFormula;
- (id)referencesFromFormula;
- (id)initWithReferences:(id)arg1;
- (id)initWithReference:(id)arg1;
- (unsigned int)countOfCellsBeingReferenced;
- (void)setWorkbook:(id)arg1;
- (id)references;
- (void)dealloc;

@end

