//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EDResources, NSMutableArray, NSString;

@interface EDConditionalFormattingRule : NSObject
{
    EDResources *mResources;
    int mType;
    int mOperator;
    NSMutableArray *mFormulas;
    unsigned int mDifferentialStyleIndex;
    _Bool mStopIfTrue;
    _Bool mAppliesToDateOnly;
    long mPriority;
    _Bool mAboveAverage;
    _Bool mBottom;
    _Bool mEqualAverage;
    _Bool mPercent;
    unsigned long mRank;
    long mStdDev;
    NSString *mText;
    int mTimePeriod;
}

+ (id)conditionalFormattingRuleWithResources:(id)arg1;
- (void)setBottom:(_Bool)arg1;
- (_Bool)bottom;
- (void)setDifferentialStyleIndex:(unsigned int)arg1;
- (unsigned int)differentialStyleIndex;
- (void)setAppliesToDateOnly:(_Bool)arg1;
- (_Bool)appliesToDateOnly;
- (void)setTimePeriod:(int)arg1;
- (int)timePeriod;
- (void)setStdDev:(long)arg1;
- (long)stdDev;
- (void)setRank:(unsigned long)arg1;
- (void)setPercent:(_Bool)arg1;
- (void)setEqualAverage:(_Bool)arg1;
- (_Bool)equalAverage;
- (void)setAboveAverage:(_Bool)arg1;
- (_Bool)aboveAverage;
- (void)setStopIfTrue:(_Bool)arg1;
- (_Bool)stopIfTrue;
- (void)setDifferentialStyle:(id)arg1;
- (id)differentialStyle;
- (void)addFormula:(id)arg1 worksheet:(id)arg2;
- (void)setOperatorEnum:(int)arg1;
- (int)operatorEnum;
- (int)compareToOtherRuleUsingPriority:(id)arg1;
- (id)initWithResources:(id)arg1;
- (id)formulaAtIndex:(unsigned int)arg1;
- (unsigned int)formulaCount;
- (_Bool)percent;
- (unsigned long)rank;
- (long)priority;
- (void)setPriority:(long)arg1;
- (void)setText:(id)arg1;
- (id)text;
- (int)type;
- (void)setType:(int)arg1;
- (void)dealloc;

@end

