//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EDReferenceCollection, NSMutableArray;

@interface EDConditionalFormatting : NSObject
{
    NSMutableArray *mRules;
    EDReferenceCollection *mRanges;
    _Bool mApplyToDate;
}

+ (id)conditionalFormatting;
- (id)rules;
- (id)rangeAtIndex:(unsigned int)arg1;
- (unsigned int)rangeCount;
- (void)addRange:(id)arg1;
- (_Bool)isApplyToDate;
- (void)addRule:(id)arg1;
- (id)ruleAtIndex:(unsigned int)arg1;
- (unsigned int)ruleCount;
- (id)init;
- (void)dealloc;

@end

