//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WDAContent, WDDocument, WDText;

@interface WDATextBox : NSObject
{
    WDText *mText;
    unsigned long mNextTextBoxId;
    _Bool mOle;
    WDDocument *mDocument;
    WDAContent *mParent;
}

- (void)setParent:(id)arg1;
- (id)parent;
- (void)setNextTextBoxId:(unsigned long)arg1;
- (BOOL)isOle;
- (void)setOle:(BOOL)arg1;
- (unsigned long)nextTextBoxId;
- (void)setDocument:(id)arg1;
- (id)document;
- (void)setText:(id)arg1;
- (id)text;
- (id)init;
- (void)dealloc;

@end

