//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICopyToPasteboardActivity.h"

@class NSMutableArray;

@interface PTSDuplicateRowsActivity : UICopyToPasteboardActivity
{
    NSMutableArray *_rows;
}

- (void)_duplicateSettings:(id)arg1 inGroup:(id)arg2;
- (void)prepareWithActivityItems:(id)arg1;
- (id)activityImage;
- (void)performActivity;
- (BOOL)canPerformWithActivityItems:(id)arg1;
- (void).cxx_destruct;
- (id)activityTitle;
- (id)activityType;

@end

