//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsGroupObserver.h"
#import "_UISettingsKeyPathObserver.h"

@class NSArray, NSDictionary, NSString, _UISettings, _UISettingsGroup;

@interface PTSHUD : UIView <UIGestureRecognizerDelegate, _UISettingsKeyPathObserver, _UISettingsGroupObserver>
{
    BOOL _showing;
    BOOL _enteringModalEditingSavedModeTableViewCell;
    BOOL _exitingModalEditingSavedModeTableViewCell;
    _UISettings *_settings;
    _UISettingsGroup *_settingsGroup;
    unsigned int _savedSettingsIndex;
    NSDictionary *_configuration;
    NSString *_mode;
    UIView *_panView;
    NSArray *_savedModeRows;
    struct CGPoint _initialPoint;
}

+ (struct CGRect)defaultFrame;
+ (id)window;
+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *savedModeRows; // @synthesize savedModeRows=_savedModeRows;
- (void)moveSavedSettingsAtIndex:(unsigned int)arg1 toIndex:(unsigned int)arg2;
- (void)removeSavedSettingsAtIndex:(unsigned int)arg1;
- (void)editSavedModeTableAction:(id)arg1;
- (void)setModalEditingSavedModeTableViewCell:(BOOL)arg1;
- (void)showSavedModeAction:(id)arg1;
- (void)showControlsModeAction:(id)arg1;
- (void)addSettingsAction:(id)arg1;
- (void)saveSettingsAction:(id)arg1;
- (void)restoreDefaultValuesAction:(id)arg1;
- (void)showInModeForKeyPath:(id)arg1;
@property(nonatomic) BOOL exitingModalEditingSavedModeTableViewCell; // @synthesize exitingModalEditingSavedModeTableViewCell=_exitingModalEditingSavedModeTableViewCell;
@property(nonatomic) BOOL enteringModalEditingSavedModeTableViewCell; // @synthesize enteringModalEditingSavedModeTableViewCell=_enteringModalEditingSavedModeTableViewCell;
- (void)updateSavedModeInterface;
- (void)updateControlsModeInterface;
- (void)showMessage:(id)arg1;
- (void)addSavedSettings;
- (void)updateInterface;
- (void)saveSettingsGroupWithReason:(id)arg1;
- (void)showSavedSettingsAtIndex:(unsigned int)arg1;
@property(nonatomic) unsigned int savedSettingsIndex; // @synthesize savedSettingsIndex=_savedSettingsIndex;
@property(retain, nonatomic) _UISettingsGroup *settingsGroup; // @synthesize settingsGroup=_settingsGroup;
- (void)configureForSettings:(id)arg1 settingsGroup:(id)arg2;
@property(retain, nonatomic) UIView *panView; // @synthesize panView=_panView;
- (void)showInMode:(id)arg1;
- (void)handleVerticalPanGesture:(id)arg1;
@property(copy, nonatomic) NSDictionary *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
@property(nonatomic) struct CGPoint initialPoint; // @synthesize initialPoint=_initialPoint;
@property(nonatomic) BOOL showing; // @synthesize showing=_showing;
@property(retain, nonatomic) _UISettings *settings; // @synthesize settings=_settings;
- (void)settingsGroup:(id)arg1 didMoveSettings:(id)arg2 fromIndex:(unsigned int)arg3 toIndex:(unsigned int)arg4;
- (void)settingsGroup:(id)arg1 didRemoveSettings:(id)arg2 atIndex:(unsigned int)arg3;
- (void)settingsGroup:(id)arg1 didInsertSettings:(id)arg2 atIndex:(unsigned int)arg3;
- (void)settings:(id)arg1 changedValueForKeyPath:(id)arg2;
@property(copy, nonatomic) NSString *mode; // @synthesize mode=_mode;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)configureForSettings:(id)arg1;
- (void)show;
- (void)hide;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

