//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "_UISettingsKeyObserver.h"

@class CADisplayLink, CMMotionManager, NSHashTable, NSMutableSet, NSString, PTXParallaxEngineSettings, PTXParallaxReferenceFrame;

@interface PTXParallaxController : NSObject <_UISettingsKeyObserver>
{
    NSHashTable *_observers;
    CMMotionManager *_motionManager;
    CADisplayLink *_displayLink;
    PTXParallaxEngineSettings *_settings;
    PTXParallaxReferenceFrame *_referenceFrame;
    double _startUpdatesTimestamp;
    BOOL _generatingUpdates;
    NSMutableSet *_suspendReasons;
}

- (void)_defaultsChanged:(id)arg1;
- (void)resetReferenceFrame;
- (void)suspend:(id)arg1;
- (BOOL)_suspended;
- (void)_sendOffset:(struct CGPoint)arg1 lockStatus:(int)arg2 lockStrength:(float)arg3;
- (void)_onDisplayLink:(id)arg1;
- (void)_sendClearOffset;
- (void)_setUpDisplayLink;
- (id)initWithParallaxEngineSettings:(id)arg1;
- (void)resume:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_tearDownDisplayLink;
- (void).cxx_destruct;
- (void)_startGeneratingUpdates;
- (BOOL)_shouldGenerateUpdates;
- (void)_stopGeneratingUpdates;
- (void)_startOrStopGeneratingUpdates;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)start;
- (void)removeObserver:(id)arg1;
- (void)stop;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

