//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaPlayerUI/MPUExtrasElementViewController.h>

@class IKViewElement;

@interface MPUExtrasViewElementViewController : MPUExtrasElementViewController
{
    BOOL _embedded;
    IKViewElement *_viewElement;
}

@property(retain, nonatomic) IKViewElement *viewElement; // @synthesize viewElement=_viewElement;
- (id)initWithViewElement:(id)arg1;
@property(nonatomic) BOOL embedded; // @synthesize embedded=_embedded;
@property(readonly, nonatomic) int preferredLayoutAttribute;
@property(readonly, nonatomic) id preferredLayoutGuide;
@property(readonly, nonatomic) BOOL matchParentHeight;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

