//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface MTLComputePipelineDescriptor : NSObject <NSCopying>
{
    struct MTLComputePipelineDescriptorPrivate *_private;
}

@property(copy, nonatomic) NSString *label;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)reset;
- (BOOL)validate;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;
@property(retain, nonatomic) id <MTLFunction> computeFunction;
- (const struct MTLComputePipelineDescriptorPrivate *)_descriptorPrivate;

@end

