//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface MTLStructType : NSObject
{
    NSDictionary *_dictionary;
    NSArray *_members;
}

@property(readonly) NSArray *members; // @synthesize members=_members;
- (id)description;
- (void)dealloc;
- (id)memberByName:(id)arg1;
- (id)initWithMembers:(id *)arg1 count:(unsigned int)arg2;
- (id)describe;

@end

