//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Metal/MTLToolsObject.h>

#import "MTLRenderPipelineState.h"

@class NSString;

@interface MTLToolsRenderPipelineState : MTLToolsObject <MTLRenderPipelineState>
{
}

@property(readonly) id <MTLDevice> device;
@property(readonly) NSString *label;
- (void)acceptVisitor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

