//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ATMovingAverage;

@interface ATThroughputCalculator : NSObject
{
    BOOL _suspended;
    double _lastUpdate;
    double _startTime;
    double _currentValue;
    ATMovingAverage *_average;
}

@property(readonly, nonatomic) double throughput;
- (void).cxx_destruct;
- (BOOL)update:(double)arg1;
- (void)resume;
- (void)suspend;
- (id)init;

@end

