//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, NSObject<OS_dispatch_queue>;

@interface SCNDisplayLink : NSObject
{
    id _reserved;
    CADisplayLink *_caDisplayLink;
    id _owner;
    CDUnknownBlockType _block;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _paused;
    BOOL _invalidated;
    BOOL _asynchronous;
    int _frameInterval;
    double _lastVideoOutput;
    int _queuedFrameCount;
}

@property(nonatomic, getter=isPaused) BOOL paused;
- (void)_teardown;
@property(nonatomic) int frameInterval;
- (void)invalidate;
- (id)init;
- (void)dealloc;
- (int)queuedFrameCount;
- (void)setPaused:(BOOL)arg1 nextFrameTimeHint:(double)arg2;
- (void)willDie;
- (id)initWithOwner:(id)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)_callbackWithTime:(double)arg1 andDeltaTime:(double)arg2;
- (BOOL)_isInvalidated;
- (void)_resume;
- (void)_caDisplayLinkCallback;
- (void)_pause;

@end

