//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSString, UIActivityIndicatorView, UIButton, UIFont, UIImage, UIImageView, UILabel, UITableView;

@interface GKContentView : UIView
{
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIImageView *_iconView;
    UIButton *_cancelButton;
    UIButton *_otherButton;
    UITableView *_table;
    UIImageView *_tableWellView;
    NSArray *_connectionButtons;
    UIActivityIndicatorView *_activityIndicator;
    BOOL _needsLayout;
}

+ (float)maxTextWidth;
@property(readonly, retain, nonatomic) NSArray *connectionButtons; // @synthesize connectionButtons=_connectionButtons;
- (void)showActivityIndicator:(BOOL)arg1;
@property(nonatomic) int numberOfMessageLines; // @dynamic numberOfMessageLines;
@property(nonatomic) int numberOfTitleLines; // @dynamic numberOfTitleLines;
- (void)setConnectionButtonTypes:(unsigned int)arg1;
- (id)initWithTitle:(id)arg1 message:(id)arg2 icon:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitle:(id)arg5;
@property(retain, nonatomic) UIButton *otherButton; // @synthesize otherButton=_otherButton;
- (id)_createButton:(BOOL)arg1;
- (void)_createMessageLabelIfNeeded;
- (id)_createConnectionButtonWithType:(unsigned int)arg1;
- (void)_createOtherButtonWithTitle:(id)arg1;
- (void)_createCancelButtonWithTitle:(id)arg1;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void)_createTitleLabelIfNeeded;
@property(readonly, nonatomic) UIFont *titleFont; // @dynamic titleFont;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) NSString *message; // @dynamic message;
@property(nonatomic) UIImage *icon; // @dynamic icon;
@property(readonly, retain, nonatomic) UITableView *table; // @dynamic table;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void)layout;
@property(nonatomic) NSString *title; // @dynamic title;
- (void)layoutIfNeeded;
- (void)dealloc;
@property(readonly, nonatomic) UIFont *messageFont; // @dynamic messageFont;

@end

