//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSSet;

@interface FontAssetDownloadManager : NSObject
{
    struct TCFRef<const __CFArray *> fDescriptors;
    struct TCFRef<const __CFSet *> fMandatoryAttributes;
    CDUnknownBlockType fProgressCallbackBlock;
    NSMutableDictionary *fProgressParams;
    NSMutableDictionary *fDownloadOptions;
    NSSet *fPreciousFontLanguages;
}

+ (id)availableFontAttributesArray;
+ (id)displayNameForCurrentUser:(id)arg1;
+ (id)enabledKeyboardLanguages;
+ (BOOL)shouldRetryWithServer;
+ (BOOL)shouldTryServer;
+ (BOOL)shouldIgnoreFontAsset:(id)arg1;
+ (Class)getASAssetQueryClass;
- (void).cxx_destruct;
- (id).cxx_construct;
- (void)dealloc;
- (void)downloadFontAssets;
- (id)initWithDescriptors:(struct __CFArray *)arg1 andMandatoryAttributes:(struct __CFSet *)arg2 withBlock:(CDUnknownBlockType)arg3;
- (id)preciousFontLanguages;
- (BOOL)activateFontsFromAssetURL:(id)arg1;
- (void)setGarbageCollectionBehaviorForAsset:(id)arg1;
- (BOOL)assetStalled:(id)arg1;
- (void)setDownloadOptionsForMobileAsset;
- (id)extractMatchingAssetsForDescriptor:(struct __CTFontDescriptor *)arg1 from:(id)arg2 withFailInfo:(char *)arg3 andFontFilePaths:(id)arg4;
- (id)availableMobileAssets:(BOOL)arg1 error:(id *)arg2;
- (id)doFinalMatching;
- (BOOL)executeDownloadingFontAssets:(id)arg1 forDescriptors:(id)arg2 andFontFilePaths:(id)arg3;
- (void)setProgressParam:(id)arg1 forKey:(id)arg2;
- (unsigned long)calculateDownloadSize:(id)arg1;
- (id)mobileAssetsForUnmatched:(id)arg1 andFontFilePaths:(id)arg2;
- (id)getUnmatchedDescriptors;
- (BOOL)callProgressCallbak:(unsigned int)arg1;

@end

