//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CameraKit/CAMBadgeView.h>

@interface CAMBadgeTextView : CAMBadgeView
{
}

- (id)_maskImage;
- (float)_textVerticalInset;
- (float)_textHorizontalKerningOffset;
- (float)_textHorizontalInset;
- (id)_textAttributes;
- (struct CGSize)_textSize;
- (id)_text;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

