//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSMutableArray;

@interface _UITextTiledLayer : CALayer
{
    NSMutableArray *_reusableTiles;
    struct CGRect _gridBounds;
    struct {
        unsigned int disableTiling:1;
        unsigned int ditchAllTiles:1;
        unsigned int suspendLayout:4;
    } _tcTiledLayerFlags;
    struct CGSize _tileSize;
}

- (void)resumeTiling;
- (void)suspendTiling;
- (void)_validateTiles;
- (void)_hideAndShowTiles:(struct CGRect)arg1 visibleBounds:(struct CGRect)arg2;
- (void)_cullAndAddLayers:(struct CGRect)arg1;
- (void)_buildTilesForRect:(struct CGRect)arg1;
- (void)drawDirtyLayer:(id)arg1 intoContext:(struct CGContext *)arg2;
@property(nonatomic) BOOL usesTiledLayers;
- (void)layoutSublayers;
@property(nonatomic) struct CGSize tileSize; // @synthesize tileSize=_tileSize;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)renderInContext:(struct CGContext *)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)init;
- (void)dealloc;

@end

