//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class ACAccount, NSDate, NSMutableDictionary, NSMutableSet, NSSet, NSString;

@interface ACAccountCredential : NSObject <NSSecureCoding>
{
    NSMutableDictionary *_credentialItems;
    NSString *_credentialType;
    NSMutableSet *_dirtyProperties;
    ACAccount *_owningAccount;
    BOOL _dirty;
    BOOL _empty;
}

+ (id)credentialWithPassword:(id)arg1;
+ (id)credentialPolicyForAccountType:(id)arg1 key:(id)arg2 clientID:(id)arg3;
+ (id)nonPersistentKeysForAccountTypeIdentifier:(id)arg1 credentialType:(id)arg2;
+ (id)supportedKeysForAccountTypeIdentifier:(id)arg1 credentialType:(id)arg2;
+ (BOOL)supportsSecureCoding;
+ (id)credentialWithOAuthToken:(id)arg1 tokenSecret:(id)arg2;
@property(nonatomic, getter=isDirty) BOOL dirty; // @synthesize dirty=_dirty;
@property(copy, nonatomic) NSString *credentialType;
@property(copy, nonatomic) NSString *oauthRefreshToken;
@property(copy, nonatomic) NSString *oauthToken;
- (void)setCredentialItem:(id)arg1 forKey:(id)arg2;
- (id)credentialItemForKey:(id)arg1;
@property(retain, nonatomic) NSDate *expiryDate;
@property(copy, nonatomic) NSString *mapsToken;
- (id)initWithPassword:(id)arg1;
@property(copy, nonatomic) NSString *password;
@property(copy, nonatomic) NSString *findMyiPhoneToken;
@property(copy, nonatomic) NSString *hsaToken;
- (id)keysForCredentialItems;
@property(copy, nonatomic) NSString *token;
- (void).cxx_destruct;
@property(nonatomic, getter=isEmpty) BOOL empty; // @synthesize empty=_empty;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithOAuth2Token:(id)arg1 refreshToken:(id)arg2 expiryDate:(id)arg3;
@property(copy, nonatomic) NSString *oauthTokenSecret;
@property(readonly, nonatomic) NSSet *dirtyProperties; // @synthesize dirtyProperties=_dirtyProperties;
@property(copy, nonatomic) NSDate *tokenExpiryDate;
- (id)oauthTokenNoSync;
- (void)setOauthTokenNoSync:(id)arg1;
- (id)initWithOAuthToken:(id)arg1 tokenSecret:(id)arg2;
- (id)credentialItems;
- (void)_markPropertyDirty:(id)arg1;
- (void)_setOwningAccount:(id)arg1;
- (void)_clearDirtyProperties;

@end

