//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ScreenReaderCore/SCRCMathExpression.h>

@interface SCRCMathSpaceExpression : SCRCMathExpression
{
}

- (id)mathMLString;
- (BOOL)endsWithSpace;
- (BOOL)beginsWithSpace;
- (id)dollarCodeDescriptionWithNumberOfOuterRadicals:(unsigned int)arg1 treePosition:(id)arg2;
- (id)initWithDictionary:(id)arg1;

@end

