//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ScreenReaderCore/SCRCMathArrayExpression.h>

@interface SCRCMathTableRowExpression : SCRCMathArrayExpression
{
}

- (id)mathMLTag;
- (BOOL)canBeWrappedInLatexMathIndicators;
- (id)latexDescriptionInMathMode:(BOOL)arg1;
- (id)dollarCodeDescriptionWithNumberOfOuterRadicals:(unsigned int)arg1 treePosition:(id)arg2;

@end

