//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Social/SLMicroBlogUserRecord.h>

#import "NSSecureCoding.h"

@class NSString, NSURL;

@interface SLTwitterUserRecord : SLMicroBlogUserRecord <NSSecureCoding>
{
    NSString *_id_str;
    NSURL *_objectID;
}

+ (BOOL)supportsSecureCoding;
+ (id)userRecordWithScreenName:(id)arg1;
+ (id)userRecordWithDictionaryRepresentation:(id)arg1;
@property(retain, nonatomic) NSURL *objectID; // @synthesize objectID=_objectID;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *id_str; // @synthesize id_str=_id_str;
- (void)setValuesWithUserDictionary:(id)arg1;

@end

