//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FCRFaceDetector, NSMutableArray, NSMutableDictionary;

@interface CIBurstImageFaceAnalysisContext : NSObject
{
    NSMutableDictionary *curConfig;
    NSMutableDictionary *faceIdMapping;
    NSMutableDictionary *renameMapping;
    int faceIdCounter;
    NSMutableArray *faceInfoArray;
    int numFramesSinceFullFaceCore;
    int numFramesNoFaces;
    FCRFaceDetector *faceDetector;
    NSMutableArray *faceTimestampArray;
    double latestImageTimestamp;
    int lastFaceIndex;
    BOOL forceFaceDetectionEnable;
    int _version;
    double timeBlinkDetectionDone;
    double timeFaceDetectionDone;
    double latestFaceTimestamp;
}

- (id)initWithVersion:(id)arg1;
@property int version; // @synthesize version=_version;
- (void)dealloc;
@property double latestFaceTimestamp; // @synthesize latestFaceTimestamp;
- (void)addFaceToArray:(id)arg1;
- (id)processSmallFaces:(id)arg1 imageStat:(id)arg2 faces:(id)arg3 extractOptions:(id)arg4;
- (BOOL)isSmallFace:(struct CGRect)arg1;
- (struct CGRect)calculateFaceCoreROI:(id)arg1 imageStat:(id)arg2 needFaceCore:(char *)arg3;
- (void)setupFaceDetector;
- (struct CGRect)padRoiRect:(struct CGRect)arg1 paddingX:(float)arg2 paddingY:(float)arg3;
@property BOOL forceFaceDetectionEnable; // @synthesize forceFaceDetectionEnable;
- (void)calcFaceScores:(id)arg1;
- (void)extractFacesFromMetadata:(id)arg1;
- (void)dumpFaceInfoArray;
- (void)adjustFaceIdsForImageStat:(id)arg1;
- (void)calculateFaceFocusInImage:(id)arg1 imageStat:(id)arg2;
@property double timeBlinkDetectionDone; // @synthesize timeBlinkDetectionDone;
@property double timeFaceDetectionDone; // @synthesize timeFaceDetectionDone;
- (int)findFacesInImage:(id)arg1 imageStat:(id)arg2;
- (void)addFacesToImageStat:(id)arg1 imageSize:(struct CGSize)arg2;

@end

