//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBar.h"

@class NSString, UIButton, UITextField, UIView;

@interface APDSearchBar : UISearchBar
{
    float _searchBarCancelButtonOffset;
    float _searchBarTextFieldDefaultOrigin;
    BOOL _RTL;
    UIButton *_searchBarCancelButton;
    NSString *_searchBarCancelText;
    UIView *_searchGlassView;
    UIView *_clearButtonView;
    UITextField *_searchBarTextField;
}

@property(nonatomic) __weak UIView *clearButtonView; // @synthesize clearButtonView=_clearButtonView;
@property(nonatomic) __weak UIView *searchGlassView; // @synthesize searchGlassView=_searchGlassView;
@property(retain, nonatomic) NSString *searchBarCancelText; // @synthesize searchBarCancelText=_searchBarCancelText;
@property(nonatomic) BOOL RTL; // @synthesize RTL=_RTL;
- (void)updateSearchBarCancelButton;
@property(nonatomic) __weak UIButton *searchBarCancelButton; // @synthesize searchBarCancelButton=_searchBarCancelButton;
@property(nonatomic) __weak UITextField *searchBarTextField; // @synthesize searchBarTextField=_searchBarTextField;
- (void).cxx_destruct;
- (void)commonInit;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

