//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (APDCardinalAdditions)
+ (id)APDCoachingTipsAPDIDForKey:(id)arg1;
+ (id)APDCoachingTipsGestureGraphicValueForKey:(id)arg1 valueIfMissing:(id)arg2;
+ (id)APDCoachingTipsLocalizedString:(id)arg1;
+ (id)APDCoachingTipsLocalizedFont;
+ (id)APDResourcesBundleURL;
+ (void)updateCoachingTipsStringsBundlesWithBundlePaths:(id)arg1;
+ (id)APDCoachingTipsAPDIDForKey:(id)arg1 valueIfMissing:(id)arg2;
+ (id)APDLocalizedString:(id)arg1 valueIfMissing:(id)arg2 table:(id)arg3 bundle:(id)arg4;
+ (id)APDLocalizedString:(id)arg1 valueIfMissing:(id)arg2 table:(id)arg3;
+ (id)APDBundleVersion;
+ (id)APDResourcesBundle;
@end

