//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSObject<OS_xpc_object>, NSString, NSURL;

@interface PKBundle : NSObject
{
    NSString *_supportPath;
    NSObject<OS_xpc_object> *__bundle;
}

@property(readonly) NSString *plugInsPath;
- (id)initWithExecutableURL:(id)arg1;
- (id)initForMainBundle;
- (id)bundleDirectory:(id)arg1;
@property(readonly) NSString *supportPath; // @synthesize supportPath=_supportPath;
- (id)stringProperty:(int)arg1;
@property(retain) NSObject<OS_xpc_object> *_bundle; // @synthesize _bundle=__bundle;
- (id)initWithExecutablePath:(id)arg1;
- (id)initWithXPCBundle:(id)arg1;
- (void).cxx_destruct;
- (id)initWithPath:(id)arg1;
- (id)initWithURL:(id)arg1;
@property(readonly) NSString *executablePath;
@property(readonly) NSString *path;
@property(readonly) NSString *bundleIdentifier;
@property(readonly) NSURL *url;
@property(readonly) NSDictionary *infoDictionary;

@end

