//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FigCameraViewfinder, FigCameraViewfinderSession;

@protocol FigCameraViewfinderDelegate <NSObject>
- (void)cameraViewfinder:(FigCameraViewfinder *)arg1 viewfinderSessionDidEnd:(FigCameraViewfinderSession *)arg2;
- (void)cameraViewfinder:(FigCameraViewfinder *)arg1 viewfinderSessionDidBegin:(FigCameraViewfinderSession *)arg2;
@end

