//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@protocol FigCameraViewfinderRemoteObjectCallbacks <NSObject>
- (void)viewfinderSession:(long long)arg1 previewStreamDidCloseWithStatus:(long)arg2;
- (void)viewfinderSessionPreviewStreamDidOpen:(long long)arg1;
- (void)viewfinderSession:(long long)arg1 didCapturePhotoWithStatus:(long)arg2 thumbnailData:(NSData *)arg3 timestamp:(CDStruct_1b6d18a9)arg4;
- (void)viewfinderSessionDidEnd;
- (void)viewfinderSessionDidBegin:(id <FigCameraViewfinderSessionRemoteObject>)arg1 withIdentifier:(long long)arg2;
@end

