//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "HDNanoSyncDescription.h"
#import "NSCopying.h"

@class HDCodableNanoSyncActivationRestore, HDCodableNanoSyncChangeSet, HDCodableNanoSyncStatus, NSData, NSString;

@interface HDCodableNanoSyncMessage : PBCodable <HDNanoSyncDescription, NSCopying>
{
    HDCodableNanoSyncActivationRestore *_activationRestore;
    HDCodableNanoSyncChangeSet *_changeSet;
    NSData *_healthPairingUUID;
    NSData *_persistentPairingUUID;
    HDCodableNanoSyncStatus *_status;
    int _version;
    struct {
        unsigned int version:1;
    } _has;
}

+ (id)messageFromPersistentUserInfo:(id)arg1;
+ (id)messageWithPersistentPairingUUID:(id)arg1 healthPairingUUID:(id)arg2;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
@property(nonatomic) BOOL hasVersion;
- (void)mergeFrom:(id)arg1;
@property(readonly, nonatomic) BOOL hasActivationRestore;
@property(readonly, nonatomic) BOOL hasChangeSet;
@property(readonly, nonatomic) BOOL hasHealthPairingUUID;
@property(readonly, nonatomic) BOOL hasPersistentPairingUUID;
@property(retain, nonatomic) HDCodableNanoSyncChangeSet *changeSet; // @synthesize changeSet=_changeSet;
- (id)copyPersistentUserInfo;
@property(retain, nonatomic) HDCodableNanoSyncActivationRestore *activationRestore; // @synthesize activationRestore=_activationRestore;
@property(retain, nonatomic) NSData *healthPairingUUID; // @synthesize healthPairingUUID=_healthPairingUUID;
@property(retain, nonatomic) NSData *persistentPairingUUID; // @synthesize persistentPairingUUID=_persistentPairingUUID;
- (id)decodedHealthPairingUUID;
- (id)decodedPersistentPairingUUID;
- (id)nanoSyncDescription;
- (BOOL)hasMinimumVersion;
@property(readonly, nonatomic) BOOL hasStatus;
@property(retain, nonatomic) HDCodableNanoSyncStatus *status; // @synthesize status=_status;
- (void).cxx_destruct;
@property(nonatomic) int version; // @synthesize version=_version;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
- (BOOL)isEqual:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

