//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HDSQLiteDatabase, HDSQLiteQueryDescriptor;

@interface HDSQLiteQuery : NSObject
{
    HDSQLiteDatabase *_database;
    HDSQLiteQueryDescriptor *_descriptor;
}

@property(readonly) HDSQLiteQueryDescriptor *queryDescriptor;
- (id)copyEntityIdentifiers;
- (void)bindToSelectStatement:(struct sqlite3_stmt *)arg1 bindingIndex:(inout int *)arg2;
- (BOOL)deleteAllEntities;
- (id)initWithDatabase:(id)arg1 descriptor:(id)arg2;
- (void)enumeratePersistentIDsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumeratePersistentIDsAndProperties:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
@property(readonly) int countOfEntities;
- (void)enumeratePersistentIDsAndPropertiesAsDoubles:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (BOOL)setValuesForAllEntitiesWithDictionary:(id)arg1;
- (BOOL)createTemporaryTableWithName:(id)arg1 properties:(id)arg2;
- (id)copySelectSQLWithProperties:(id)arg1;
- (BOOL)enumeratePersistentIDsAndProperties:(id)arg1 error:(id *)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)enumerateEntitiesUsingBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;
@property(readonly) HDSQLiteDatabase *database;

@end

