//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class PUAirplayRoute, PUAirplayRouteTableViewDataSource;

@interface PUAirplayRoutePickerViewController : UITableViewController
{
    PUAirplayRouteTableViewDataSource *_dataSource;
    PUAirplayRoute *_markedRoute;
    BOOL _shouldShowDoneButton;
    BOOL _makeRouteCurrentBeforeReturning;
    CDUnknownBlockType _completionHandler;
}

@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)init;
@property(nonatomic) BOOL makeRouteCurrentBeforeReturning; // @synthesize makeRouteCurrentBeforeReturning=_makeRouteCurrentBeforeReturning;
@property(nonatomic) BOOL shouldShowDoneButton; // @synthesize shouldShowDoneButton=_shouldShowDoneButton;
- (void)setMarkedRoute:(id)arg1;
- (void)_userSelectedRoute:(id)arg1 fromTableView:(id)arg2 atIndexPath:(id)arg3;
- (void)_updateRoutes;
- (void)_doneAction:(id)arg1;

@end

