//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, PLPhotoEditModel;

@interface PUAutoAdjustmentController : NSObject
{
    NSArray *_cachedRedEyeCorrections;
    NSDictionary *_cachedWhiteBalanceSettings;
    float _cachedSmartToneLevel;
    float _cachedSmartColorLevel;
    BOOL _cachedValuesAreValid;
    PLPhotoEditModel *_stashedPreviousManualModel;
    BOOL _busy;
}

@property(nonatomic, getter=isBusy) BOOL busy; // @synthesize busy=_busy;
- (void).cxx_destruct;
- (void)_revertAutoValuesOnModel:(id)arg1;
- (void)_setBusy:(BOOL)arg1;
- (void)_applyAutoValuesOnModel:(id)arg1 whiteBalanceSettings:(id)arg2 redEyeCorrections:(id)arg3 smartToneLevel:(float)arg4 smartColorLevel:(float)arg5 valuesCalculator:(id)arg6 animated:(BOOL)arg7;
- (void)_removeLegacyAutoEnhanceFromModel:(id)arg1;
- (void)enableAutoEnhanceOnModel:(id)arg1 baseImage:(id)arg2 valuesCalculator:(id)arg3 allowRedEye:(BOOL)arg4 animated:(BOOL)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)disableAutoEnhanceOnModel:(id)arg1;
- (BOOL)isAutoEnhanceEnabledForModel:(id)arg1;
- (void)invalidateCachedAdjustments;

@end

