//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface PUFeedTextCellContentView : UIView
{
    UILabel *label;
    UILabel *detailLabel;
    UIImageView *iconImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *label; // @synthesize label;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel;

@end

