//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PUSearchResultsDelegate.h"
#import "PUSuggestedSearchResultsDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableDictionary, NSString, PHImageManager, PSIDatabase, PUPingTimer, PUSearchResultsDataSource, PUSuggestedSearchResultsDataSource, UIBarButtonItem, UIPanGestureRecognizer, UISearchBar, UITableView, UIView, _UIBackdropView, _UIDynamicValueAnimation;

@interface PUSearchViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate, UISearchBarDelegate, PUSearchResultsDelegate, PUSuggestedSearchResultsDelegate>
{
    UIPanGestureRecognizer *_horizontalPanGestureRecognizer;
    _UIDynamicValueAnimation *_horizontalPanResetAnimation;
    UISearchBar *_searchBar;
    UITableView *_searchResultsTableView;
    UIBarButtonItem *_cancelButton;
    UITableView *_searchSuggestionsTableView;
    _UIBackdropView *_backdropView;
    UIView *_backgroundView;
    UIView *_cellSelectedBackgroundView;
    PHImageManager *_imageManager;
    PSIDatabase *_searchIndex;
    PUSearchResultsDataSource *_searchResultsDataSource;
    PUPingTimer *_searchResultsPingTimer;
    PUSuggestedSearchResultsDataSource *_suggestedSearchResultsDataSource;
    PUPingTimer *_suggestedSearchResultsPingTimer;
    id <UITableViewDataSource><UITableViewDelegate> _dataSource;
    NSMutableDictionary *_headerViews;
    BOOL _debug_showMatchScores;
    BOOL _showsSearchBarInNavigationBar;
    BOOL _showsSectionHeaderForSearchResults;
    BOOL _inCustomTransition;
    id <PUSearchViewControllerDelegate> _delegate;
    NSString *_searchText;
    NSString *_selectedDisplayTitle;
}

+ (id)_screenSnapshot;
+ (id)newSearchBar;
+ (void)viewController:(id)arg1 swapSearchViewController:(id)arg2 withResultsViewController:(id)arg3 animated:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
+ (BOOL)usePopoverAppearanceForTraitCollection:(id)arg1;
+ (BOOL)mustAdaptFromTraitCollection:(id)arg1 toTraitCollection:(id)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void)searchBarSearchButtonClicked:(id)arg1;
@property(readonly, nonatomic) UISearchBar *searchBar;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)contentScrollView;
- (void)viewWillAppear:(BOOL)arg1;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)_updateBackgroundView;
- (id)navigationItem;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) __weak id <PUSearchViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)init;
- (void)dealloc;
@property(nonatomic, getter=isInCustomTransition) BOOL inCustomTransition; // @synthesize inCustomTransition=_inCustomTransition;
- (void)_selectSearchResultAtIndexPath:(id)arg1;
- (void)_selectSuggestedSearchAtIndexPath:(id)arg1;
- (void)_configureCell:(id)arg1 inTableView:(id)arg2 atIndexAPath:(id)arg3;
- (void)_updateFloatingHeaderClippingInTableView:(id)arg1;
@property(nonatomic) BOOL showsSectionHeaderForSearchResults; // @synthesize showsSectionHeaderForSearchResults=_showsSectionHeaderForSearchResults;
- (void)_setCurrentTableViewDataSource:(id)arg1;
- (void)_handleHorizontalPan:(id)arg1;
- (void)_DEBUG_rebuildSearchIndex:(id)arg1;
- (void)_mergeSearchResults;
- (void)_mergeSuggestedSearchResultsAnimated:(BOOL)arg1;
- (unsigned int)_numberOfTableViewSectionsOutSuggestionsSection:(unsigned int *)arg1 outRecentsSection:(unsigned int *)arg2;
- (void)_pushMomentsGridForPhotosWithUUIDs:(id)arg1 title:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_pushGridForAlbumWithUUID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_setSelectedDisplayTitle:(id)arg1;
- (id)_localIdentifiersForUUIDs:(id)arg1;
- (BOOL)_isSuggestionsSection:(unsigned int)arg1;
- (void)_pushMomentsGridForPhotoCollections:(id)arg1 title:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_pushGridForAlbum:(struct NSObject *)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_applyHorizontalPanResetAnimationWithVelocity:(float)arg1;
- (void)_cancelHorizontalPanResetAnimation;
- (void)_applyHorizontalOffsetX:(float)arg1;
- (id)_searchResultsTableView;
- (void)_configureTableView:(id)arg1;
- (void)_scheduleUpdateTableFooterView;
- (void)_updateTableFooterViewWithProgress:(unsigned int)arg1;
- (void)_updateForSearchTextDidChangeWithoutAnimation;
- (void)_updateSearchWithText:(id)arg1;
- (void)_setSearchText:(id)arg1;
- (void)_updateNavigationBar;
- (void)_searchFieldTextDidChange:(id)arg1;
- (void)_pingTimerFire:(id)arg1;
- (void)suggestedSearchResultsDataSourceHasPendingChanges:(id)arg1;
- (void)searchResultsDataSourceHasPendingChanges:(id)arg1;
- (void)_cancelButtonTapped:(id)arg1;
@property(nonatomic) BOOL showsSearchBarInNavigationBar; // @synthesize showsSearchBarInNavigationBar=_showsSearchBarInNavigationBar;
- (id)newSearchResultsControllerWithSpec:(id)arg1 searchResults:(id)arg2 orAlbum:(struct NSObject *)arg3 title:(id)arg4;
- (id)pu_debugRows;
@property(retain, nonatomic) NSString *selectedDisplayTitle; // @synthesize selectedDisplayTitle=_selectedDisplayTitle;
- (void)cancelActiveSearches;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

