//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommunicationsSetupUI/CNFRegListController.h>

@class CNFRegAlias, NSArray, PSSpecifier;

@interface CNFRegAliasDetailController : CNFRegListController
{
    CNFRegAlias *_alias;
    PSSpecifier *_removeGroupSpecifier;
    PSSpecifier *_removeButtonSpecifier;
    NSArray *_resendValidationSpecifierGroup;
    CDUnknownBlockType _alertHandler;
}

- (void)resendValidationEmailTapped:(id)arg1;
- (void)forgetAliasTapped:(id)arg1;
- (void)_updateUIAnimated:(BOOL)arg1;
- (void)showRemoveAliasConfirmation;
- (void)_showResendGroup:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setRemoveAliasEnabled:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)_shouldShowResendButton;
- (void)_showAliasValidationError:(id)arg1;
- (id)initWithRegController:(id)arg1 alias:(id)arg2;
- (void)_buildSpecifierCache:(id)arg1;
- (void)_setupEventHandlers;
- (id)specifierList;
@property(retain, nonatomic) CNFRegAlias *alias; // @synthesize alias=_alias;
- (void)systemApplicationDidEnterBackground;
@property(copy, nonatomic) CDUnknownBlockType alertHandler; // @synthesize alertHandler=_alertHandler;
- (void)systemApplicationWillEnterForeground;
- (id)bundle;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)dealloc;

@end

