//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FUViewControllerAnimatedTransitioning.h"

@class NSString, UIView;

@interface FUCrossFadeZoomTransitionAnimator : NSObject <FUViewControllerAnimatedTransitioning>
{
    CDUnknownBlockType _animationCompletionBlock;
    BOOL _transitionCompleted;
    BOOL _zoomingUp;
    id _context;
    UIView *_smallView;
    UIView *_largeView;
}

@property(nonatomic) BOOL zoomingUp; // @synthesize zoomingUp=_zoomingUp;
@property(retain, nonatomic) UIView *largeView; // @synthesize largeView=_largeView;
@property(retain, nonatomic) UIView *smallView; // @synthesize smallView=_smallView;
- (void)completeTransitionImmediately;
- (void).cxx_destruct;
@property(retain, nonatomic) id context; // @synthesize context=_context;
- (void)animationEnded:(BOOL)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

