//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITMLKit/IKDOMNode.h>

#import "IKJSDOMParentNode.h"

@class IKDOMElement, IKDOMHTMLCollection;

@interface IKDOMDocumentFragment : IKDOMNode <IKJSDOMParentNode>
{
}

@property(readonly, nonatomic) IKDOMHTMLCollection *children;
@property(readonly, nonatomic) unsigned long childElementCount;
@property(readonly, nonatomic) IKDOMElement *lastElementChild;
- (id)nodeName;
- (int)nodeType;
@property(readonly, nonatomic) IKDOMElement *firstElementChild;

@end

