//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ITMLKit/IKJSObject.h>

#import "IKJSXMLHTTPRequest.h"
#import "ISStoreURLOperationDelegate.h"

@class IKDOMDocument, ISURLOperation, JSManagedValue, NSDictionary, NSError, NSHTTPURLResponse, NSMutableArray, NSMutableData, NSMutableURLRequest, NSString, NSURLConnection;

@interface IKJSXMLHTTPRequest : IKJSObject <ISStoreURLOperationDelegate, IKJSXMLHTTPRequest>
{
    BOOL _shouldSquashOnReadyStateEvents;
    int _onReadyStateChangeMessageQueueLock;
    BOOL _async;
    BOOL _inProgress;
    BOOL _jingleRequest;
    unsigned long timeout;
    ISURLOperation *_jingleOperation;
    NSMutableArray *_onReadyStateChangeMessageQueue;
    NSMutableURLRequest *_urlRequest;
    NSURLConnection *_urlConnection;
    NSString *_user;
    NSString *_password;
    NSHTTPURLResponse *_urlResponse;
    NSMutableData *_receivedData;
    int _requestReadyState;
    unsigned int _requestStatusCode;
    NSString *_requestStatusText;
    int _requestResponseType;
    NSError *_requestError;
    unsigned int _readyState;
    unsigned int _status;
    NSString *_statusText;
    NSDictionary *_performanceMetrics;
    JSManagedValue *_managedSelf;
}

+ (id)xhrOperationQueue;
- (void)operation:(id)arg1 willSendRequest:(id)arg2;
- (void)operation:(id)arg1 finishedWithOutput:(id)arg2;
- (void)operation:(id)arg1 didReceiveResponse:(id)arg2;
- (void)operation:(id)arg1 didDiscoverContentLength:(id)arg2;
@property(retain) NSDictionary *performanceMetrics; // @synthesize performanceMetrics=_performanceMetrics;
@property unsigned int readyState; // @synthesize readyState=_readyState;
- (void)abort;
@property(retain) NSString *statusText; // @synthesize statusText=_statusText;
@property unsigned int responseType;
@property(readonly) NSString *responseText;
- (id)getResponseHeader:(id)arg1;
- (id)getAllResponseHeaders;
@property(readonly) IKDOMDocument *responseXML;
@property(retain, nonatomic) NSError *requestError; // @synthesize requestError=_requestError;
@property(retain, nonatomic) NSMutableURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property unsigned long timeout; // @synthesize timeout;
@property(nonatomic) int requestResponseType; // @synthesize requestResponseType=_requestResponseType;
@property(retain, nonatomic) NSMutableArray *onReadyStateChangeMessageQueue; // @synthesize onReadyStateChangeMessageQueue=_onReadyStateChangeMessageQueue;
@property(nonatomic) BOOL jingleRequest; // @synthesize jingleRequest=_jingleRequest;
- (void)setRequestHeader:(id)arg1:(id)arg2;
- (void)open:(id)arg1:(id)arg2:(id)arg3:(id)arg4:(id)arg5;
- (id)_timeIntervalSince1970;
- (void)_clearAllReadyStateChangeMessagesAndSquashFutureOnes;
@property(nonatomic) __weak ISURLOperation *jingleOperation; // @synthesize jingleOperation=_jingleOperation;
@property(retain, nonatomic) NSHTTPURLResponse *urlResponse; // @synthesize urlResponse=_urlResponse;
@property(retain, nonatomic) NSString *requestStatusText; // @synthesize requestStatusText=_requestStatusText;
@property(nonatomic) unsigned int requestStatusCode; // @synthesize requestStatusCode=_requestStatusCode;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(nonatomic) int requestReadyState; // @synthesize requestReadyState=_requestReadyState;
@property(retain, nonatomic) NSURLConnection *urlConnection; // @synthesize urlConnection=_urlConnection;
- (id)_dequeueReadyStateChangeMessage;
- (void)_sendWithData:(id)arg1;
- (void)_openWithMethod:(id)arg1 url:(id)arg2 async:(BOOL)arg3 user:(id)arg4 password:(id)arg5;
- (void)_setException:(id)arg1;
@property(retain, nonatomic) JSManagedValue *managedSelf; // @synthesize managedSelf=_managedSelf;
- (id)initWithAppContext:(id)arg1 jingleRequest:(BOOL)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)_operationFinished:(id)arg1;
- (void)_abort;
@property(retain, nonatomic) NSString *user; // @synthesize user=_user;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property unsigned int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
@property(readonly) id response;
@property(readonly) NSDictionary *metrics;
- (id)init;
- (void)send:(id)arg1;
- (void)operation:(id)arg1 failedWithError:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

