//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSDate;

@interface HKWorkoutEvent : NSObject <NSSecureCoding>
{
    int _type;
    NSDate *_date;
}

+ (id)_workoutEventWithType:(int)arg1 date:(id)arg2;
+ (id)workoutEventWithType:(int)arg1 date:(id)arg2;
+ (BOOL)supportsSecureCoding;
+ (id)_newWorkoutEventWithType:(int)arg1 date:(id)arg2;
- (void)_setType:(int)arg1;
- (void).cxx_destruct;
- (id)awakeAfterUsingCoder:(id)arg1;
@property(readonly, copy) NSDate *date;
@property(readonly) int type;
- (id)_init;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)_setDate:(id)arg1;
- (void)_assertPropertiesValid;
- (id)_validateConfiguration;

@end

