//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DBManager;

@interface CallDBManager : NSObject
{
    BOOL _deviceUnlocked;
    unsigned char _dataStoreType;
    unsigned char _notifyDataStoreChangeReason;
    DBManager *_dbManager;
}

+ (id)dataStoreName;
+ (id)modelURL;
+ (id)getDBLocationIsSandboxed:(BOOL)arg1 isTemporary:(BOOL)arg2;
- (void)registerForNotifications;
@property BOOL deviceUnlocked; // @synthesize deviceUnlocked=_deviceUnlocked;
@property(retain) DBManager *dbManager; // @synthesize dbManager=_dbManager;
- (BOOL)notifyDataStoreChanged;
- (void)reFetchState;
@property unsigned char dataStoreType; // @synthesize dataStoreType=_dataStoreType;
@property unsigned char notifyDataStoreChangeReason; // @synthesize notifyDataStoreChangeReason=_notifyDataStoreChangeReason;
- (BOOL)shouldCreateTemporary;
- (BOOL)shouldCreatePermanent;
- (void)createDataStore;
- (void)moveCallsFromTempDatabase;
- (BOOL)createTemporary;
- (BOOL)createPermanent;
- (id)createManagedObjectContext;
- (void)handleTemporaryCreated;
- (id)tempDBLocation;
- (void)handlePermanentCreated;
- (id)permDBLocation;
- (void).cxx_destruct;
- (id)init;

@end

