//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSDictionary, NSExpression, NSMutableArray, NSString;

@interface NSEntityMapping : NSObject
{
    void *_reserved;
    void *_reserved1;
    NSDictionary *_mappingsByName;
    NSString *_name;
    unsigned int _mappingType;
    NSString *_sourceEntityName;
    NSData *_sourceEntityVersionHash;
    NSString *_destinationEntityName;
    NSData *_destinationEntityVersionHash;
    NSExpression *_sourceExpression;
    NSDictionary *_userInfo;
    NSString *_entityMigrationPolicyClassName;
    NSMutableArray *_attributeMappings;
    NSMutableArray *_relationshipMappings;
    struct __entityMappingFlags {
        unsigned int _isInUse:1;
        unsigned int _reservedEntityMapping:31;
    } _entityMappingFlags;
}

+ (void)initialize;
@property(retain, nonatomic) NSDictionary *userInfo;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEditable;
@property(copy) NSString *name;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (BOOL)_hasInferredMappingNeedingValidation;
- (void)_addRelationshipMapping:(id)arg1;
- (void)_addAttributeMapping:(id)arg1;
- (id)_migrationPolicy;
- (id)_mappingsByName;
@property(copy) NSString *entityMigrationPolicyClassName;
@property(retain) NSArray *relationshipMappings;
@property(retain) NSArray *attributeMappings;
@property(retain) NSExpression *sourceExpression;
@property(copy) NSData *destinationEntityVersionHash;
@property(copy) NSData *sourceEntityVersionHash;
- (id)_initWithSourceEntityDescription:(id)arg1 destinationEntityDescription:(id)arg2;
- (void)_setIsEditable:(BOOL)arg1;
- (void)_createCachesAndOptimizeState;
- (void)_throwIfNotEditable;
@property unsigned int mappingType;
@property(copy) NSString *destinationEntityName;
@property(copy) NSString *sourceEntityName;

@end

