//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreData/NSSQLIntermediate.h>

@interface NSSQLConstantValueIntermediate : NSSQLIntermediate
{
    unsigned int _type;
    id _constantValue;
}

- (void)dealloc;
- (id)initWithConstantValue:(id)arg1 ofType:(unsigned int)arg2 inScope:(id)arg3;
- (BOOL)_addBindVarForConstVal1:(id)arg1 inContext:(id)arg2;
- (BOOL)_addBindVarForConstId:(id)arg1 ofType:(unsigned int)arg2 inContext:(id)arg3;
- (unsigned int)sqlTypeForProperty:(id)arg1;
- (id)propertyAtEndOfKeyPathExpression:(id)arg1;
- (id)generateSQLStringInContext:(id)arg1;
- (id)initWithConstantValue:(id)arg1 inScope:(id)arg2;

@end

