//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RMSDAAPRequestManager, RMSFairPlaySession;

@interface RMSDAAPLoginManager : NSObject
{
    RMSDAAPRequestManager *_requestManager;
    RMSFairPlaySession *_fairPlaySession;
    BOOL _isFairPlayRequired;
}

- (void)loginWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithRequestManager:(id)arg1;
- (void)_continueFairPlayHandshakeWithData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)_isFairplayRequiredForServerInfo:(id)arg1;
- (void)_requestServerInfoWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_requestLoginWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_requestFairPlayHandshake:(CDUnknownBlockType)arg1;
- (void)_requestControlInterfaceWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;

@end

