//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UINavigationControllerDelegate.h"

@class NSString, SKUIAccountButtonsView, SKUIClientContext, SKUILink;

@interface SKUIAccountButtonsViewController : UIViewController <UINavigationControllerDelegate>
{
    SKUIAccountButtonsView *_buttonsView;
    SKUIClientContext *_clientContext;
    id <SKUIAccountButtonsDelegate> _delegate;
    SKUILink *_ecommerceLink;
}

@property(retain, nonatomic) SKUILink *ECommerceLink; // @synthesize ECommerceLink=_ecommerceLink;
- (void)_signInButtonAction:(id)arg1;
- (void)_usernameButtonAction:(id)arg1;
- (void)_termsAndConditionsButtonAction:(id)arg1;
- (void)_redeemButtonAction:(id)arg1;
- (void)_giftAction:(id)arg1;
- (void)_ecommerceLinkAction:(id)arg1;
- (void)_sendDidSignIn;
- (void)_openIForgot;
- (void)_signOut;
- (void)_viewAppleID;
- (void)_reloadRestrictions;
- (void)_reloadAccountsButton;
- (id)_buttonsView;
- (void)_accountStoreChangedNotification:(id)arg1;
@property(nonatomic, getter=isTermsAndConditionsHidden) BOOL termsAndConditionsHidden;
@property(nonatomic, getter=isGiftingHidden) BOOL giftingHidden;
@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
- (void)_restrictionsChangedNotification:(id)arg1;
- (void).cxx_destruct;
- (unsigned int)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(nonatomic) __weak id <SKUIAccountButtonsDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

