//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreKitUI/SKUIStorePageSection.h>

#import "SKUIArtworkRequestDelegate.h"

@class NSArray, NSString, SKUIGridComponent, SKUIViewElementLayoutContext, UIColor;

@interface SKUIGridViewElementPageSection : SKUIStorePageSection <SKUIArtworkRequestDelegate>
{
    int _cardVerticalSpacingStyle;
    float _cellContentWidth;
    SKUIViewElementLayoutContext *_cellLayoutContext;
    float _cellPaddingInteriorHorizontal;
    float _cellPaddingLeftEdgeHorizontal;
    float _cellPaddingRightEdgeHorizontal;
    int _lastNeedsMoreCount;
    int _lockupType;
    int _numberOfColumns;
    BOOL _rendersWithPerspective;
    UIColor *_separatorColor;
    int _separatorStyle;
    BOOL _showsEditMode;
    NSArray *_viewElements;
}

- (BOOL)_isContainedWithinExploreTemplate;
- (void)_reloadCellPadding;
- (float)_cellPaddingInteriorHorizontal;
- (BOOL)_useOrdinalPadding;
- (Class)_lockupCellClassWithLockup:(id)arg1;
- (Class)_cardCellClassForCard:(id)arg1;
- (BOOL)_viewElementIsStandardCard:(id)arg1;
- (int)_positionForIndexPath:(id)arg1;
- (void)_enumerateViewElementsForRowOfIndexPath:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (struct UIEdgeInsets)_cellInsetsForIndexPath:(id)arg1;
- (float)_cellHeightForViewElement:(id)arg1 width:(float)arg2;
- (struct UIEdgeInsets)_normalizedContentInsetForViewElement:(id)arg1 indexPath:(id)arg2;
- (float)_cellContentWidth;
- (float)_cellPaddingRightEdgeHorizontal;
- (float)_cellPaddingLeftEdgeHorizontal;
- (id)_lockupCellReuseIdentifierWithLockup:(id)arg1;
- (id)_cardArtworkBoundingSizeForIndexPath:(id)arg1;
- (void)_resetLayoutProperties;
- (int)_numberOfColumnsForWidth:(float)arg1;
- (void)_requestLayoutForCells;
- (void)_enumerateVisibleViewElementsUsingBlock:(CDUnknownBlockType)arg1;
- (void)artworkRequest:(id)arg1 didLoadImage:(id)arg2;
- (int)_lockupTypeForLockup:(id)arg1;
- (Class)_cellClassForViewElement:(id)arg1;
- (id)backgroundColorForIndexPath:(id)arg1;
- (int)applyUpdateType:(int)arg1;
- (void)_reloadViewElementProperties;
- (id)targetScrollingIndexPathForElementWithIndexBarEntryID:(id)arg1 relativeSectionIndex:(int)arg2;
- (void)getModalSourceViewForViewElement:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)willTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)collectionViewWillScrollToOffset:(struct CGPoint)arg1 visibleRange:(struct SKUIIndexPathRange)arg2;
- (BOOL)collectionViewShouldSelectItemAtIndexPath:(id)arg1;
- (BOOL)collectionViewShouldHighlightItemAtIndexPath:(id)arg1;
- (void)expandEditorialForLabelElement:(id)arg1 indexPath:(id)arg2;
- (void)collectionViewDidSelectItemAtIndexPath:(id)arg1;
- (void)collectionViewDidEndDisplayingCellForItemAtIndexPath:(id)arg1;
- (void)collectionViewWillDisplayCellForItemAtIndexPath:(id)arg1;
- (int)numberOfCells;
- (void)addImpressionsForIndexPath:(id)arg1 toSession:(id)arg2;
- (id)cellForIndexPath:(id)arg1;
- (struct CGSize)cellSizeForIndexPath:(id)arg1;
- (void)collectionViewWillApplyLayoutAttributes:(id)arg1;
- (void)reloadCellWithIndexPath:(id)arg1 reason:(int)arg2;
- (void)reloadVisibleCellsWithReason:(int)arg1;
- (BOOL)updateCellWithIndexPath:(id)arg1 itemState:(id)arg2 animated:(BOOL)arg3;
- (void)prefetchResourcesWithReason:(int)arg1;
- (void)willAppearInContext:(id)arg1;
- (id)initWithPageComponent:(id)arg1;
- (void).cxx_destruct;
- (struct UIEdgeInsets)sectionContentInset;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) SKUIGridComponent *pageComponent; // @dynamic pageComponent;
@property(readonly) Class superclass;

@end

