//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBFLockScreenDateFormatter.h"

@class NSString, NSTimeZone;

@interface SBFLockScreenSimpleDateFormatter : NSObject <SBFLockScreenDateFormatter>
{
    NSTimeZone *_timeZone;
}

- (id)formatDateAsTimeNoAMPM:(id)arg1;
- (void)resetFormattersIfNecessary;
- (id)formatDateAsDayOfWeekMonthDayStyle:(id)arg1;
@property(retain, nonatomic) NSTimeZone *timeZone; // @synthesize timeZone=_timeZone;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

