//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "PKPaymentServiceDelegate.h"
#import "PKPaymentVerificationPresentationDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSNumberFormatter, NSObject<OS_dispatch_source>, NSString, PKPaymentPass, PKPaymentPassDetailActivationFooterView, PKPaymentService, PKPaymentVerificationPresentationController, PKPaymentWebService, PKSettingTableCell, PKVerificationRequestRecord, UIColor;

@interface PKPaymentPassDetailViewController : UITableViewController <PKPaymentServiceDelegate, PKPaymentVerificationPresentationDelegate, UITableViewDataSource, UITableViewDelegate, MFMailComposeViewControllerDelegate>
{
    id <PKPassLibraryDataProvider> _dataProvider;
    int _detailViewStyle;
    NSObject<OS_dispatch_source> *_transactionTimer;
    BOOL _deepLinkingEnabled;
    BOOL _passDeletionInProgress;
    PKPaymentPass *_pass;
    PKPaymentWebService *_webService;
    PKPaymentService *_paymentService;
    PKPaymentVerificationPresentationController *_verificationPresenter;
    PKVerificationRequestRecord *_verificationRecord;
    PKPaymentPassDetailActivationFooterView *_activationFooter;
    NSNumberFormatter *_numberFormatter;
    PKSettingTableCell *_notificationSwitch;
    NSArray *_sections;
    id <PKPaymentVerificationEntryDelegate> _verificationDelegate;
    id <PKPassDeleteHandler> _deleteOverrider;
    UIColor *_primaryTextColor;
    UIColor *_detailTextColor;
    UIColor *_linkTextColor;
    UIColor *_warningTextColor;
    UIColor *_highlightColor;
    NSArray *_transactions;
}

- (void)_reloadView;
@property(nonatomic) UIColor *primaryTextColor; // @synthesize primaryTextColor=_primaryTextColor;
- (void)paymentPassWithUniqueIdentifier:(id)arg1 didEnableTransactionService:(BOOL)arg2;
- (void)paymentPassWithUniqueIdentifier:(id)arg1 didReceiveTransaction:(id)arg2;
@property(copy, nonatomic) NSArray *transactions; // @synthesize transactions=_transactions;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
@property(nonatomic) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)dealloc;
- (void)_done:(id)arg1;
@property(nonatomic) UIColor *warningTextColor; // @synthesize warningTextColor=_warningTextColor;
@property(nonatomic) UIColor *linkTextColor; // @synthesize linkTextColor=_linkTextColor;
@property(nonatomic) UIColor *detailTextColor; // @synthesize detailTextColor=_detailTextColor;
@property(nonatomic) id <PKPassDeleteHandler> deleteOverrider; // @synthesize deleteOverrider=_deleteOverrider;
@property(nonatomic) id <PKPaymentVerificationEntryDelegate> verificationDelegate; // @synthesize verificationDelegate=_verificationDelegate;
- (float)_heightForPassStateSectionWithTableView:(id)arg1;
- (id)initWithPass:(id)arg1 webService:(id)arg2 style:(int)arg3 dataProvider:(id)arg4;
- (void)presentVerificationViewController:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)didChangeVerificationPresentation;
- (id)_activationFooterView;
- (void)_openIssuerWebsite;
- (void)_emailIssuer;
- (void)_callIssuer;
- (void)_activationFooterPressed:(id)arg1;
- (void)_notificationSwitchChanged:(id)arg1;
- (id)_infoCell:(id)arg1 withDetailText:(id)arg2;
- (id)_subtitleCell;
- (void)_setPlaceholderColorForCell:(id)arg1;
- (id)_defaultCell;
- (unsigned int)_indexOfSection:(int)arg1;
- (void)_updateTransactionsArrayWithTransaction:(id)arg1;
- (id)_deleteCardCell;
- (id)_billingAddressCell;
- (id)_deviceAccountNumberCell;
- (id)_linkCellWithText:(id)arg1;
- (id)_infoCell:(id)arg1;
- (id)_moreTransactionsCell;
- (id)_transactionCellForIndexPath:(id)arg1;
- (id)_notificationServicesCell;
- (id)_cellForPassStateSection;
- (id)_linkedAppCell;
- (id)_footerViewForPassStateSection;
- (float)_footerViewHeightForPassStateSectionWithTableView:(id)arg1;
- (id)_deviceSpecificLocalizedStringKeyForKey:(id)arg1;
- (id)_footerTextForPassStateSection;
- (id)_headerTitleForPassStateSection;
- (void)_didSelectDeleteCard;
- (void)_didSelectPrivacySectionAtRow:(int)arg1;
- (void)_didSelectBillingAddress;
- (void)_didSelectContactBankSection;
- (void)_didSelectTransactionAtRow:(int)arg1;
- (void)_didSelectPassStateSection;
- (int)_numberOfRowsForPassStateSection;
- (id)_privacyTermsCells;
- (id)_cardInfoCells;
- (BOOL)_shouldShowPrivacyPolicyCell;
- (BOOL)_shouldShowTermsCell;
- (BOOL)_shouldShowContactCell;
- (void)_reloadTransactionsWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)_doesTableContainSection:(int)arg1;
- (void)_setupSections;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

