//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PKPassPaymentSummaryCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSNumberFormatter, NSString, PKPaymentMessage, PKPaymentPass, PKPaymentTransaction, UITableView;

@interface PKPassPaymentSummaryView : UIView <UITableViewDataSource, UITableViewDelegate, PKPassPaymentSummaryCellDelegate>
{
    NSNumberFormatter *_numberFormatter;
    UITableView *_tableView;
    BOOL _deepLinkingEnabled;
    PKPaymentPass *_pass;
    PKPaymentTransaction *_transaction;
    PKPaymentMessage *_message;
    NSString *_transactionAppLaunchToken;
    NSString *_messageAppLaunchToken;
    id <PKPassPaymentSummaryViewDelegate> _delegate;
}

@property(readonly, nonatomic) PKPaymentPass *pass; // @synthesize pass=_pass;
@property(readonly, nonatomic) PKPaymentMessage *message; // @synthesize message=_message;
@property(nonatomic) id <PKPassPaymentSummaryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) NSString *messageAppLaunchToken; // @synthesize messageAppLaunchToken=_messageAppLaunchToken;
@property(readonly, nonatomic) NSString *transactionAppLaunchToken; // @synthesize transactionAppLaunchToken=_transactionAppLaunchToken;
@property(readonly, nonatomic) PKPaymentTransaction *transaction; // @synthesize transaction=_transaction;
- (int)_sectionIndexOfMessage;
- (int)_sectionIndexOfTransaction;
- (void)setTransaction:(id)arg1 appLaunchToken:(id)arg2 animated:(BOOL)arg3;
- (id)initWithPaymentPass:(id)arg1;
- (id)_imageFromTransaction:(id)arg1;
- (id)_amountTextFromTransaction:(id)arg1;
- (id)_detailTextFromTransaction:(id)arg1;
- (id)_primaryTextFromTransaction:(id)arg1;
- (void)_performAction:(int)arg1 forSection:(int)arg2 animated:(BOOL)arg3;
- (void)setMessage:(id)arg1 appLaunchToken:(id)arg2 animated:(BOOL)arg3;
- (void)_configureCell:(id)arg1 forMessage:(id)arg2;
- (BOOL)_isSectionIndexOfMessage:(int)arg1;
- (void)_configureCell:(id)arg1 forTransaction:(id)arg2;
- (BOOL)_isSectionIndexOfTransaction:(int)arg1;
- (void)paymentSummaryCellDetailsButtonPressed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

