//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (UIAccessibilityElementTraversal)
- (int)_accessibilityCompareGeometryForViewOrDictionary:(id)arg1;
- (id)_accessibilityElementsInDirectionWithCount:(unsigned int)arg1 options:(id)arg2;
- (id)_accessibilityParentFromOrderedChildrenContainer:(id)arg1;
- (void)_accessibilityEnumerateSiblingsFromOrderedChildrenContainer:(id)arg1 fromChildAtIndex:(int)arg2 headerIndex:(int)arg3 footerIndex:(int)arg4 isMovingForward:(BOOL)arg5 usingBlock:(CDUnknownBlockType)arg6;
- (void)_handleSupplementaryViewIfNeededWithOrderedChildrenContainer:(id *)arg1 childOfOrderedChildrenContainer:(id *)arg2 headerIndex:(unsigned int *)arg3 footerIndex:(unsigned int *)arg4;
- (id)_accessibilityOrderedChildrenContainer;
- (BOOL)_accessibilityShouldUseSupplementaryViews;
- (BOOL)_accessibilityAppendOrderedChildLeafDescendantsToArray:(id)arg1 count:(unsigned int)arg2 shouldStopAtRemoteElement:(BOOL)arg3 options:(id)arg4;
- (BOOL)_accessibilityShouldBeProcessed:(id)arg1;
- (BOOL)_accessibilityHasVisibleFrame;
- (void)_accessibilityEnumerateSiblingsWithParent:(id *)arg1 options:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)_accessibilityLeafDescendantsWithCount:(unsigned int)arg1 shouldStopAtRemoteElement:(BOOL)arg2 options:(id)arg3;
- (id)_accessibilityLeafDescendantsWithOptions:(id)arg1;
- (id)_accessibilityLeafDescendantsWithCount:(unsigned int)arg1 options:(id)arg2;
- (id)_accessibilityViewChildrenWithOptions:(id)arg1;
@end

