//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (UIAccessibilityElementTraversal)
+ (id)_accessibilitySortedElementsAndContainersDescendingFromViews:(id)arg1 options:(id)arg2;
+ (id)_accessibilityElementsAndContainersDescendingFromViews:(id)arg1 options:(id)arg2 sorted:(BOOL)arg3;
- (id)_accessibilitySubviewsForGettingElementsWithOptions:(id)arg1;
- (void)_addAccessibilityElementsAndOrderedContainersWithOptions:(id)arg1 toCollection:(id)arg2;
- (BOOL)_accessibilityShouldBeAddedToViewChildrenWithOptions:(id)arg1;
- (BOOL)_accessibilityShouldUseSupplementaryViews;
- (BOOL)_accessibilityShouldBeProcessed:(id)arg1;
- (id)_accessibilityViewChildrenWithOptions:(id)arg1;
@end

