//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <QuartzCore/CAPropertyAnimation.h>

@interface CABasicAnimation : CAPropertyAnimation
{
}

- (void)CA_prepareRenderValue;
@property float endAngle;
- (void)applyForTime:(double)arg1 presentationObject:(id)arg2 modelObject:(id)arg3;
@property float startAngle;
@property BOOL roundsToInteger;
@property(retain) id toValue;
@property(retain) id fromValue;
@property(retain) id byValue;
- (double)_timeFunction:(double)arg1;
- (struct Animation *)_copyRenderAnimationForLayer:(id)arg1;
- (BOOL)_setCARenderAnimation:(struct Animation *)arg1 layer:(id)arg2;

@end

