//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@interface CAReplicatorLayer : CALayer
{
}

+ (BOOL)_hasRenderLayerSubclass;
+ (BOOL)CA_automaticallyNotifiesObservers:(Class)arg1;
+ (id)defaultValueForKey:(id)arg1;
@property double instanceDelay;
@property int instanceCount;
@property struct CATransform3D instanceTransform;
@property struct CGColor *instanceColor;
@property float instanceAlphaOffset;
- (id)implicitAnimationForKeyPath:(id)arg1;
- (void)didChangeValueForKey:(id)arg1;
- (id)init;
@property float instanceBlueOffset;
@property float instanceGreenOffset;
@property float instanceRedOffset;
- (void)_renderSublayersInContext:(struct CGContext *)arg1;
@property BOOL preservesDepth;
- (struct Layer *)_copyRenderLayer:(struct Transaction *)arg1 layerFlags:(unsigned int)arg2 commitFlags:(unsigned int *)arg3;
- (unsigned int)_renderLayerPropertyAnimationFlags:(unsigned int)arg1;
- (_Bool)_renderLayerDefinesProperty:(unsigned int)arg1;

@end

