//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LSApplicationWorkspaceObserver.h"

@class NSObject<ATWorkspaceObserverDelegate>, NSObject<LSApplicationWorkspaceObserverProtocol>;

@interface ATWorkspaceObserver : LSApplicationWorkspaceObserver
{
    NSObject<LSApplicationWorkspaceObserverProtocol> *_delegate;
}

- (void)stopObserving;
- (void).cxx_destruct;
@property(nonatomic) NSObject<ATWorkspaceObserverDelegate> *delegate;
- (void)applicationInstallsArePrioritized:(id)arg1 arePaused:(id)arg2;
- (void)applicationsDidInstall:(id)arg1;
- (void)applicationInstallsDidChange:(id)arg1;
- (void)applicationInstallsDidPrioritize:(id)arg1;
- (void)applicationInstallsDidCancel:(id)arg1;
- (void)startObserving;

@end

