//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MBManager, NSError;

@protocol MBManagerDelegate

@optional
- (void)managerDidLoseConnectionToService:(MBManager *)arg1;
- (void)manager:(MBManager *)arg1 didFailVerificationWithError:(NSError *)arg2;
- (void)manager:(MBManager *)arg1 didFailRestoreWithError:(NSError *)arg2;
- (void)manager:(MBManager *)arg1 didFailScanWithError:(NSError *)arg2;
- (void)manager:(MBManager *)arg1 didFailBackupWithError:(NSError *)arg2;
- (void)managerDidFinishVerification:(MBManager *)arg1;
- (void)managerDidCancelRestore:(MBManager *)arg1;
- (void)managerDidFinishRestore:(MBManager *)arg1;
- (void)managerDidFinishScan:(MBManager *)arg1;
- (void)managerDidFinishBackup:(MBManager *)arg1;
- (void)manager:(MBManager *)arg1 didUpdateProgress:(float)arg2 estimatedTimeRemaining:(unsigned int)arg3;
- (void)manager:(MBManager *)arg1 didSetBackupEnabled:(BOOL)arg2;
@end

