//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class NSMutableSet, PLAccountingGroup, PLNSNotificationOperatorComposition;

@interface PLApplicationAgent : PLAgent
{
    PLNSNotificationOperatorComposition *_notificationSBApplicationStateChanged;
    PLAccountingGroup *_accountingGroupApplication;
    PLAccountingGroup *_appAccountingGroup;
    NSMutableSet *_keyboardPlugins;
}

+ (id)pluginEntryFromProxy:(id)arg1;
+ (id)entryAggregateDefinitionApplicationReason;
+ (id)entryEventNoneAllPlugins;
+ (id)entryEventNoneAllApps;
+ (id)entryEventNoneDefinitionApplicationMetadata;
+ (id)entryEventPointDefinitionApplication;
+ (id)installedPlugins;
+ (id)appNameForBundleID:(id)arg1;
+ (id)installedBundleIDs;
+ (id)entryAggregateDefinitions;
+ (id)entryEventNoneDefinitions;
+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitions;
+ (id)accountingGroupDefinitions;
+ (void)load;
@property(retain) NSMutableSet *keyboardPlugins; // @synthesize keyboardPlugins=_keyboardPlugins;
@property(readonly) PLAccountingGroup *accountingGroupApplication; // @synthesize accountingGroupApplication=_accountingGroupApplication;
@property(readonly) PLNSNotificationOperatorComposition *notificationSBApplicationStateChanged; // @synthesize notificationSBApplicationStateChanged=_notificationSBApplicationStateChanged;
- (void)storeUninstalledAppsInfo:(id)arg1;
- (void)storeInstalledAppsInfo:(id)arg1;
- (void)logUninstalledApp:(id)arg1;
- (void)logInstalledPlugin:(id)arg1;
- (void)logInstalledApp:(id)arg1;
- (void)logEventPointApplicationForDisplayID:(id)arg1;
- (void)logEventPointApplication;
- (void)logAllPlugins;
- (void)logAllApps;
- (void)logEventPointApplicationForDisplayID:(id)arg1 withPid:(int)arg2 withState:(id)arg3 withReasons:(id)arg4;
@property(retain) PLAccountingGroup *appAccountingGroup; // @synthesize appAccountingGroup=_appAccountingGroup;
- (void)addAccountingEvent:(id)arg1;
- (id)trimmingConditionsForRolloverAtDate:(id)arg1;
- (void)initOperatorDependancies;
- (void).cxx_destruct;
- (void)log;
- (id)init;

@end

