//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PowerlogLiteOperators/PLBBMsgRoot.h>

@class NSArray, NSMutableArray, NSMutableDictionary, NSNumber, NSString;

@interface PLBBMavHwRfLTELogMsg : PLBBMsgRoot
{
    unsigned char _inited;
    NSString *_error;
    NSArray *_dlC0TBSzCnt;
    NSArray *_dlC1TBSzCnt;
    NSNumber *_logDuration;
    NSNumber *_dupMode;
    NSArray *_caFreqInfo;
    NSArray *_txPwrCnt;
    NSArray *_caSCCCnt;
    NSArray *_actRxTxCnt;
    NSArray *_sleepStateCnt;
    NSString *_groupEntryKey;
    NSString *_groupID;
    NSMutableArray *_groupArrEntries;
    NSMutableDictionary *_commonInfo;
    NSMutableDictionary *_kvPairs;
}

+ (id)entryEventBackwardDefinitionBBMav10HwRfLTE;
- (void)refreshMav10BBRfAllRats;
@property(retain) NSArray *sleepStateCnt; // @synthesize sleepStateCnt=_sleepStateCnt;
@property(retain) NSArray *actRxTxCnt; // @synthesize actRxTxCnt=_actRxTxCnt;
@property(retain) NSArray *caSCCCnt; // @synthesize caSCCCnt=_caSCCCnt;
@property(retain) NSArray *txPwrCnt; // @synthesize txPwrCnt=_txPwrCnt;
@property(retain) NSArray *dlC1TBSzCnt; // @synthesize dlC1TBSzCnt=_dlC1TBSzCnt;
@property(retain) NSArray *dlC0TBSzCnt; // @synthesize dlC0TBSzCnt=_dlC0TBSzCnt;
@property(retain) NSArray *caFreqInfo; // @synthesize caFreqInfo=_caFreqInfo;
@property(retain) NSNumber *dupMode; // @synthesize dupMode=_dupMode;
@property(retain) NSMutableArray *groupArrEntries; // @synthesize groupArrEntries=_groupArrEntries;
@property(retain) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain) NSString *groupEntryKey; // @synthesize groupEntryKey=_groupEntryKey;
- (id)logEventBackwardBBMav10HwRfLTE;
@property(nonatomic) unsigned char inited; // @synthesize inited=_inited;
- (void)populateEntry:(id)arg1;
- (void)addPairWithKey:(id)arg1 andWithVal:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *kvPairs; // @synthesize kvPairs=_kvPairs;
@property(retain, nonatomic) NSMutableDictionary *commonInfo; // @synthesize commonInfo=_commonInfo;
- (void)sendAndLogPLEntry:(id)arg1 withName:(id)arg2 withType:(id)arg3;
@property(retain) NSNumber *logDuration; // @synthesize logDuration=_logDuration;
- (void)setHeaderWithSeqNum:(id)arg1 andDate:(id)arg2 andTimeCal:(double)arg3;
@property(retain) NSString *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (id)init;

@end

