//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class PLCFNotificationOperatorComposition;

@interface PLLocationAgent : PLAgent
{
    PLCFNotificationOperatorComposition *_appStatusChangedNotification;
    PLCFNotificationOperatorComposition *_techStatusChangedNotification;
}

+ (id)bundleIdFromBundlePath:(id)arg1;
+ (id)entryEventNoneDefinitionClientStatusDebug;
+ (id)entryEventForwardDefinitionClientStatus;
+ (id)entryEventForwardDefinitionTechStatus;
+ (id)entryAggregateDefinitions;
+ (id)entryEventNoneDefinitions;
+ (id)entryEventIntervalDefinitions;
+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitions;
+ (id)accountingGroupDefinitions;
+ (id)railDefinitions;
+ (id)defaults;
+ (void)load;
@property(retain) PLCFNotificationOperatorComposition *techStatusChangedNotification; // @synthesize techStatusChangedNotification=_techStatusChangedNotification;
@property(retain) PLCFNotificationOperatorComposition *appStatusChangedNotification; // @synthesize appStatusChangedNotification=_appStatusChangedNotification;
- (void)logEventNoneClientStatus;
- (void)createLocationAccountingGroups:(id)arg1;
- (id)readClientCacheForClient:(id)arg1 andType:(id)arg2 forEntryKey:(id)arg3;
- (void)logEventNoneClientStatusDebugWithClients:(id)arg1;
- (void)updateClientCacheForClient:(id)arg1 andType:(id)arg2 forEntry:(id)arg3;
- (void)modelGPSICEPower:(id)arg1;
- (id)humanReadableNameForTechnology:(id)arg1;
- (void)logEventForwardTechStatus;
- (void)logEventForwardClientStatus;
- (void)initOperatorDependancies;
- (void).cxx_destruct;
- (void)log;
- (id)init;

@end

