//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@interface TDThemeConstant : NSManagedObject
{
    int _identifier;
}

- (void)setConstantName:(id)arg1;
- (id)constantName;
- (void)setAttributesFromCopyData:(id)arg1;
- (id)copyDataFromAttributes;
- (void)setDisplayName:(id)arg1;
- (id)displayName;
- (void)setIdentifier:(unsigned int)arg1;
- (unsigned int)identifier;
- (id)debugDescription;

@end

