//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SAObjects/SABaseClientBoundCommand.h>

@class NSArray, NSString, NSURL, SALocation;

@interface SAFmfSearch : SABaseClientBoundCommand
{
}

+ (id)search;
+ (id)searchWithDictionary:(id)arg1 context:(id)arg2;
@property(copy, nonatomic) NSArray *friends;
@property(retain, nonatomic) SALocation *requestedLocation;
@property(copy, nonatomic) NSURL *targetAppId;
- (BOOL)requiresResponse;
- (id)encodedClassName;
@property(copy, nonatomic) NSArray *emailAddresses;
- (id)groupIdentifier;
@property(copy, nonatomic) NSString *proximity;
@property(retain, nonatomic) SALocation *currentLocation;

@end

