//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SAObjects/AceObject.h>

#import "SASTTemplateItem.h"

@class NSString, SAUIDecoratedText;

@interface SASTSpecificAnswerItem : AceObject <SASTTemplateItem>
{
}

+ (id)specificAnswerItemWithDictionary:(id)arg1 context:(id)arg2;
+ (id)specificAnswerItem;
@property(retain, nonatomic) SAUIDecoratedText *decoratedFooter;
@property(retain, nonatomic) SAUIDecoratedText *decoratedValue;
- (id)encodedClassName;
@property(copy, nonatomic) NSString *footer;
@property(copy, nonatomic) NSString *value;
- (id)groupIdentifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

