//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotoLibraryServices/PLChangeNotification.h>

@class NSArray, NSIndexSet, NSString, PLManagedObject, PLObjectSnapshot;

@interface PLContainerChangeNotification : PLChangeNotification
{
    id _object;
    PLObjectSnapshot *_snapshot;
    NSArray *_changedObjects;
    BOOL _didCalculateDiffs;
    BOOL _shouldReload;
    NSIndexSet *_deletedIndexes;
    NSIndexSet *_insertedIndexes;
    NSIndexSet *_movedIndexes;
    struct __CFArray *_movedFromIndexes;
    NSIndexSet *_changedIndexes;
    BOOL _countDidChange;
}

@property(nonatomic, setter=_setDidCalculateDiffs:) BOOL _didCalculateDiffs;
- (unsigned int)snapshotIndexForContainedObject:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *changedObjects;
@property(readonly, retain, nonatomic) NSIndexSet *changedIndexesRelativeToSnapshot;
@property(readonly, nonatomic) BOOL hasMoves;
@property(readonly, nonatomic) BOOL countDidChange;
@property(readonly, retain, nonatomic) NSString *_contentRelationshipName;
@property(readonly, retain, nonatomic) NSArray *_changedObjects;
- (BOOL)_getOldSet:(id *)arg1 newSet:(id *)arg2;
- (id)_initWithObject:(id)arg1 snapshot:(id)arg2 changedObjects:(id)arg3;
- (void)_calculateDiffsIfNecessary;
@property(readonly, retain, nonatomic) NSString *_diffDescription;
- (void)_calculateDiffs;
@property(readonly, retain, nonatomic) PLManagedObject *_managedObject;
@property(readonly, retain, nonatomic) NSIndexSet *changedIndexes;
- (void)enumerateMovesWithBlock:(CDUnknownBlockType)arg1;
@property(readonly, retain, nonatomic) NSIndexSet *insertedIndexes;
@property(readonly, retain, nonatomic) NSIndexSet *deletedIndexes;
@property(readonly, nonatomic) BOOL shouldReload;
@property(readonly, retain, nonatomic) NSArray *deletedObjects;
@property(readonly, retain, nonatomic) NSArray *insertedObjects;
- (id)object;
@property(readonly, retain, nonatomic) PLObjectSnapshot *snapshot;
- (id)_init;
- (id)name;
- (id)init;
- (void)dealloc;

@end

