//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface PLImageGeometry : NSObject <NSCopying>
{
    int _appliedOrientation;
    struct CGRect _inputRect;
}

+ (id)geometryWithOutputSize:(struct CGSize)arg1 appliedOrientation:(int)arg2;
+ (id)geometryWithInputSize:(struct CGSize)arg1 initialOrientation:(int)arg2;
@property(nonatomic) int appliedOrientation; // @synthesize appliedOrientation=_appliedOrientation;
- (struct CGAffineTransform)transformFromOrientation:(int)arg1;
- (struct CGAffineTransform)transformToOrientation:(int)arg1;
- (struct CGRect)normalizeRect:(struct CGRect)arg1 basis:(int)arg2;
- (struct CGRect)denormalizeRect:(struct CGRect)arg1 basis:(int)arg2;
- (struct CGRect)outputRectForInputRect:(struct CGRect)arg1;
- (struct CGRect)inputRectForOutputRect:(struct CGRect)arg1;
- (void)rotateCounterClockwise;
- (void)rotateClockwise;
- (void)flipHorizontally;
- (void)flipVertically;
@property(readonly, nonatomic, getter=isMirrored) BOOL mirrored;
@property(readonly, nonatomic, getter=isSizeInverted) BOOL sizeInverted;
@property(readonly, nonatomic) struct CGAffineTransform appliedTransform;
- (struct CGAffineTransform)_transformFromOrientation:(int)arg1 toOrientation:(int)arg2;
- (struct CGRect)_basisRect:(int)arg1;
@property(readonly, nonatomic) struct CGRect outputRect;
@property(readonly, nonatomic) struct CGRect inputRect; // @synthesize inputRect=_inputRect;
- (void)applyOrientation:(int)arg1;
- (id)initWithInputSize:(struct CGSize)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;

@end

