//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BrightnessSystemInternal;

@interface BrightnessSystem : NSObject
{
    BrightnessSystemInternal *bsi;
}

- (id)copyPropertyForKey:(id)arg1;
- (BOOL)isAlsSupported;
- (void)registerNotificationBlock:(CDUnknownBlockType)arg1;
- (BOOL)setProperty:(id)arg1 forKey:(id)arg2;
- (id)init;
- (void)dealloc;

@end

