//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MKSearchCompleterDelegate.h"

@class CLGeocoder, MKLocalSearchCompleter, NSString;

@interface TWCValidator : NSObject <MKSearchCompleterDelegate>
{
    MKLocalSearchCompleter *_completer;
    CLGeocoder *_geocoder;
    id <WeatherValidatorDelegate> _delegate;
}

+ (id)sharedValidator;
- (void)geocodeLocation:(id)arg1;
- (void)autocompleteLocation:(id)arg1;
- (id)aggregateDictionaryDomain;
@property(nonatomic) id <WeatherValidatorDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)dealloc;
- (void)cancel;
- (void)completerDidFail:(id)arg1 error:(id)arg2;
- (void)completerDidUpdateResults:(id)arg1 finished:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

