//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UILongPressGestureRecognizer.h>

#import "UIAutoscrollDelegate.h"
#import "_UIScrollNotification.h"

@class NSString, UIAutoscroll, UIScrollView;

@interface _UIActivityDragGestureRecognizer : UILongPressGestureRecognizer <UIAutoscrollDelegate, _UIScrollNotification>
{
    UIScrollView *_targetScrollView;
    UIAutoscroll *_autoscroll;
    struct UIEdgeInsets _draggingInsets;
}

@property(nonatomic) struct UIEdgeInsets draggingInsets; // @synthesize draggingInsets=_draggingInsets;
- (int)autoscrollDirectionsForPoint:(struct CGPoint)arg1 inView:(id)arg2;
@property(retain, nonatomic) UIScrollView *targetScrollView; // @synthesize targetScrollView=_targetScrollView;
@property(retain, nonatomic) UIAutoscroll *autoscroll; // @synthesize autoscroll=_autoscroll;
- (void)beginAutoscrollAndUpdateDirectionIfNeeded;
- (void)updateAutoscroll:(id)arg1;
- (void)cancelAutoscroll;
- (void)autoscrollWillNotStart;
- (void)_didScroll;
- (void)_updateBackdropMaskViewsInScrollView:(id)arg1;
- (void)reset;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)setState:(int)arg1;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

