//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/_UIDocumentPickerContainerItem.h>

@class NSString;

@interface _UIDocumentPickerContainerContainerItem : _UIDocumentPickerContainerItem
{
    NSString *_cachedSubtitle;
}

- (id)subtitle;
- (void)_modelChanged;
- (id)sortDate;
- (id)_blockingThumbnailWithSize:(struct CGSize)arg1 scale:(float)arg2;
- (id)_defaultThumbnailWithSize:(struct CGSize)arg1 scale:(float)arg2;
- (id)title;
- (int)type;
- (id)url;
- (void)dealloc;

@end

