//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UISearchBarDelegate.h"

@class NSLayoutConstraint, NSString, UISearchController, _UIDocumentPickerContainerViewController, _UIDocumentPickerSearchContainerModel, _UINavigationControllerPalette;

@interface _UIDocumentPickerSearchPaletteView : UIView <UISearchBarDelegate>
{
    _UINavigationControllerPalette *_palette;
    _UIDocumentPickerSearchContainerModel *_searchModel;
    UISearchController *_searchController;
    _UIDocumentPickerContainerViewController *_resultsController;
    NSLayoutConstraint *_searchFieldLeftConstraint;
    NSLayoutConstraint *_searchFieldRightConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *searchFieldRightConstraint; // @synthesize searchFieldRightConstraint=_searchFieldRightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *searchFieldLeftConstraint; // @synthesize searchFieldLeftConstraint=_searchFieldLeftConstraint;
- (void)searchCanceled:(id)arg1;
@property(nonatomic) _UINavigationControllerPalette *palette; // @synthesize palette=_palette;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) _UIDocumentPickerContainerViewController *resultsController; // @synthesize resultsController=_resultsController;
@property(retain, nonatomic) _UIDocumentPickerSearchContainerModel *searchModel; // @synthesize searchModel=_searchModel;
- (id)serviceViewController;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)willMoveToSuperview:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

