//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface _UIFocusDebugOverlayView : UIView
{
    UIColor *_overlayColor;
    UIView *_highlightView;
}

@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(copy, nonatomic) UIColor *overlayColor; // @synthesize overlayColor=_overlayColor;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (void)_unhighlightPreferredFocusView;
- (void)_highlightPreferredFocusView:(id)arg1;
- (id)initWithView:(id)arg1;
- (void)_removeFocusItemOverlayViews;
- (id)_focusItemsOverlayCreateIfNecessary:(BOOL)arg1;
- (void)dealloc;

@end

