//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CADisplayLink, CALayer, NSMutableArray, NSTimer, UIImageView;

@interface UIDictationMeterView : UIButton
{
    UIImageView *_background;
    UIImageView *_overlay;
    NSMutableArray *_micListeningImages;
    CALayer *_micImageLayer;
    CALayer *_animatingLayer;
    NSTimer *_fillTimer;
    int _phase;
    int _state;
    float _runningPowerLevels[5];
    unsigned int _powerPointer;
    CADisplayLink *_displayLink;
    double _releaseStart;
    float _releaseLevel;
    int _cachedViewMode;
}

- (void)_startRelease;
- (void)_startSustain;
- (void)_startDecay;
- (void)_updateListeningAnimation:(id)arg1;
- (void)_updateReleaseAnimation:(id)arg1;
- (void)_resetRunningPowerLevels;
- (float)_currentMicPowerLevel;
- (id)_sustainKeyFrameAnimation;
- (id)_decayKeyFrameAnimation;
- (id)_attackKeyFrameAnimation;
- (id)_keyframeAnimationForCGImages:(id)arg1 duration:(double)arg2;
- (float)_adjustedDuration:(float)arg1;
- (id)imageForMicLevel:(float)arg1;
- (double)_animationInterval;
- (float)_powerLevelForMicPower:(float)arg1;
- (float)_updateMedianWithNewValue:(float)arg1;
- (void)_removeAnimationsAndClearLayers;
- (void)_clearDisplayLink;
- (void)_startAttack;
- (void)_startListening;
- (id)_emptyMicImage;
- (void)_reset;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)setState:(int)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

