//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface UIGroupTableViewCellBackground : UIView
{
    int _sectionLocation;
    int _newSectionLocation;
    int _animationCount;
    int _selectionStyle;
    int _separatorStyle;
    UIView *_topSeparatorView;
    UIView *_bottomSeparatorView;
    UIColor *_selectionTintColor;
    float _sectionBorderWidth;
    struct UIEdgeInsets _separatorInset;
    struct {
        unsigned int selected:1;
    } _groupBackgroundFlags;
}

+ (void)_flushCacheOnNotification:(id)arg1;
+ (void)initialize;
- (void)setSelectionTintColor:(id)arg1 layoutSubviews:(BOOL)arg2;
- (void)_setSectionLocationAnimationDidStop;
- (void)_decrementAnimationCount;
- (void)_incrementAnimationCount;
- (struct CGRect)_contentRectForContentHeight:(float)arg1;
- (id)_cachedImageForKey:(id)arg1;
- (void)_updateSeparatorViews;
- (struct CGRect)_contentsCenter:(BOOL)arg1;
- (struct CGRect)_contentsRect:(BOOL)arg1;
- (float)_pixelDisplayedImageHeight;
- (id)_roundedRectBezierPathInRect:(struct CGRect)arg1 withSectionLocation:(int)arg2 forBorder:(BOOL)arg3 cornerRadiusAdjustment:(float)arg4;
@property(nonatomic) float sectionBorderWidth; // @synthesize sectionBorderWidth=_sectionBorderWidth;
- (id)_bottomShadowColor;
- (id)_topShadowColor;
@property(nonatomic) int sectionLocation;
- (id)_topShadowViewWithColor:(id)arg1;
- (id)_contentMaskLayer;
@property(retain, nonatomic) UIColor *selectionTintColor;
@property(nonatomic) int selectionStyle;
- (id)_fillColor;
- (void)displayLayer:(id)arg1;
- (void)_layoutSubviews:(BOOL)arg1;
- (id)_sectionBorderColor;
- (id)_separatorColor;
@property(nonatomic) int separatorStyle;
@property(nonatomic) struct UIEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
@property(nonatomic, getter=isSelected) BOOL selected;
- (void)setSectionLocation:(int)arg1 animated:(BOOL)arg2;
- (id)_backgroundColor;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

