//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, _UIInlineCandidateCell;

@interface UIInlineCandidateTextView : UIView
{
    int m_type;
    int m_edgeType;
    BOOL m_animating;
    NSMutableArray *_candidateCellArray;
    NSArray *_candidates;
    id _target;
    SEL _action;
    unsigned int _selectedItem;
    _UIInlineCandidateCell *_currentlyPushedItem;
    BOOL _showingArrow;
    BOOL _arrowHighlighted;
    BOOL _phraseEditable;
}

- (void)showHighlightedArrow;
- (BOOL)_arrowHighlighted;
- (void)redrawArrow;
- (id)findCell:(struct CGPoint)arg1;
- (void)_cellSelected:(id)arg1;
- (float)_layoutCandidates:(id)arg1 maxCount:(int)arg2 height:(float)arg3 maxScreenWidth:(float)arg4 hasExtensionCandidates:(BOOL)arg5;
- (unsigned int)selectedItem;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (int)edgeType;
- (id)initWithFrame:(struct CGRect)arg1 candidates:(id)arg2 type:(int)arg3 maxScreenWidth:(float)arg4 hasExtensionCandidates:(BOOL)arg5;
- (unsigned int)numberOfShownItems;
- (struct CGRect)_calculateRectForExpandedHitRegion;
- (void)setEdgeType:(int)arg1;
- (int)textEffectsVisibilityLevel;
- (void)setAnimating:(BOOL)arg1;
- (void)setSelectedItem:(unsigned int)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

