//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextInputDelegate.h"
#import "_UITextDocumentInterfaceDelegate.h"

@class NSObject<UITextDocumentProxy>, NSString, UIInputView, UIKeyboard;

@interface UIInputViewController : UIViewController <_UITextDocumentInterfaceDelegate, UITextInputDelegate>
{
    BOOL _alignsToContentViewController;
    NSObject<UITextDocumentProxy> *_textDocumentProxy;
    NSString *_primaryLanguage;
}

+ (BOOL)_requiresProxyInterface;
@property(nonatomic) BOOL _alignsToContentViewController; // @synthesize _alignsToContentViewController;
- (void)requestSupplementaryLexiconWithCompletion:(CDUnknownBlockType)arg1;
- (void)returnToPreviousInputMode;
- (void)advanceToNextInputMode;
- (BOOL)_shouldForwardSystemLayoutFittingSizeChanges;
- (id)_extensionContext;
- (void)_setTextDocumentProxy:(id)arg1;
@property(readonly, nonatomic) NSObject<UITextDocumentProxy> *textDocumentProxy; // @synthesize textDocumentProxy=_textDocumentProxy;
- (id)_textDocumentInterface;
- (id)_proxyInterface;
- (void)_setupInputController;
- (void)_didResetDocumentState;
- (void)_willResetDocumentState;
- (id)_compatibilityController;
@property(readonly, nonatomic) UIKeyboard *_keyboard;
- (void)dismissKeyboard;
@property(copy, nonatomic) NSString *primaryLanguage; // @synthesize primaryLanguage=_primaryLanguage;
- (void)selectionDidChange:(id)arg1;
- (void)selectionWillChange:(id)arg1;
@property(retain, nonatomic) UIInputView *inputView;
- (struct CGSize)_systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (void)_setExtensionContext:(id)arg1;
- (void)viewDidLoad;
- (void)textDidChange:(id)arg1;
- (void)textWillChange:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

