//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardMenuView.h>

@interface UIKeyboardDictationMenu : UIKeyboardMenuView
{
}

+ (id)activeInstance;
+ (id)sharedInstance;
- (void)cleanupForFadeOrHide;
- (BOOL)centerPopUpOverKey;
- (void)performShowAnimation;
- (BOOL)usesDimmingView;
- (struct CGSize)preferredSize;
- (BOOL)usesTable;
- (void)fade;
- (void)fadeWithDelay:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)show;
- (void)hide;

@end

