//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol UIKeyboardEmojiInput <NSObject>
- (void)reloadForCategory:(int)arg1;

@optional
- (int)reloadSectionForOffsetPercentage:(float)arg1;
@end

