//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UIKeyboardEmojiCategoryController : NSObject
{
    int _currentCategory;
}

+ (Class)classForCategoryControl;
- (int)sectionWithOffsetPercentage:(float)arg1;
- (void)setCurrentCategory:(int)arg1;
- (id)initWithCategoryControl:(id)arg1;

@end

