//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "_UIScreenEdgePanRecognizerDelegate.h"

@class NSMutableArray, NSString, UIKBScreenTraits, UIKBTextEditingTraits, UIKeyboardTaskQueue, UITextInputTraits, UITouch, _UIScreenEdgePanRecognizer;

@interface UIKeyboardLayout : UIView <_UIScreenEdgePanRecognizerDelegate>
{
    UITextInputTraits *_inputTraits;
    UIKBScreenTraits *_screenTraits;
    UIKBTextEditingTraits *_textEditingTraits;
    NSMutableArray *_uncommittedTouches;
    UITouch *_activeTouch;
    UITouch *_shiftKeyTouch;
    int _cursorLocation;
    BOOL _disableInteraction;
    UIKeyboardTaskQueue *_taskQueue;
    BOOL hideKeysUnderIndicator;
    BOOL _isExecutingDeferredTouchTasks;
    _UIScreenEdgePanRecognizer *_screenEdgePanRecognizer;
    CDUnknownBlockType _deferredTouchDownTask;
    CDUnknownBlockType _deferredTouchMovedTask;
    double lastTouchUpTime;
}

+ (Class)_subclassForScreenTraits:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType deferredTouchMovedTask; // @synthesize deferredTouchMovedTask=_deferredTouchMovedTask;
@property(copy, nonatomic) CDUnknownBlockType deferredTouchDownTask; // @synthesize deferredTouchDownTask=_deferredTouchDownTask;
@property(nonatomic) BOOL hideKeysUnderIndicator; // @synthesize hideKeysUnderIndicator;
@property(retain, nonatomic) UITouch *shiftKeyTouch; // @synthesize shiftKeyTouch=_shiftKeyTouch;
- (float)flickDistance;
- (void)reloadTargetEdgesForScreenGestureRecognition;
- (void)deactivateActiveKeysClearingTouchInfo:(BOOL)arg1 clearingDimming:(BOOL)arg2;
- (BOOL)performSpaceAction;
- (void)screenEdgePanRecognizerStateDidChange:(id)arg1;
- (void)didRecognizeGestureOnEdge:(unsigned int)arg1 withDistance:(float)arg2;
@property(nonatomic) double lastTouchUpTime; // @synthesize lastTouchUpTime;
@property(retain, nonatomic) _UIScreenEdgePanRecognizer *screenEdgePanRecognizer; // @synthesize screenEdgePanRecognizer=_screenEdgePanRecognizer;
- (unsigned int)targetEdgesForScreenGestureRecognition;
- (void)_notifyLayoutOfGesturePosition:(struct CGPoint)arg1 relativeToEdge:(unsigned int)arg2;
- (void)_addTouchToScreenEdgePanRecognizer:(id)arg1;
- (BOOL)_canAddTouchesToScreenGestureRecognizer:(id)arg1;
- (void)_executeDeferredTouchTasks;
@property(nonatomic) BOOL isExecutingDeferredTouchTasks; // @synthesize isExecutingDeferredTouchTasks=_isExecutingDeferredTouchTasks;
- (void)commitTouches:(id)arg1 executionContext:(id)arg2;
- (void)forceUpdatesForCommittedTouch;
- (void)touchCancelled:(id)arg1;
- (void)didFinishScreenGestureRecognition;
- (void)touchUp:(id)arg1;
- (BOOL)canForceTouchCommit:(id)arg1;
- (BOOL)_shouldAllowKeyboardHandlingForTouchesEndedOrCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchDragged:(id)arg1;
- (BOOL)_shouldAllowKeyboardHandlingForTouchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchDown:(id)arg1;
- (void)commitTouches:(id)arg1;
- (id)touchesToCommitBeforeTouch:(id)arg1;
- (BOOL)_shouldAllowKeyboardHandlingForTouchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchCancelled:(id)arg1 executionContext:(id)arg2;
- (void)touchUp:(id)arg1 executionContext:(id)arg2;
- (void)didCommitTouch:(id)arg1;
- (void)clearShiftIfNecessaryForEndedTouch:(id)arg1;
- (void)touchDragged:(id)arg1 executionContext:(id)arg2;
- (void)touchDown:(id)arg1 executionContext:(id)arg2;
- (void)assertSavedLocation:(struct CGPoint)arg1 onTouch:(id)arg2 inWindow:(id)arg3 resetPrevious:(BOOL)arg4;
- (SEL)handlerForNotification:(id)arg1;
- (void)addWipeRecognizer;
- (void)wipeGestureRecognized:(id)arg1;
- (id)simulateTouchForCharacter:(id)arg1 errorVector:(struct CGPoint)arg2 shouldTypeVariants:(BOOL)arg3 baseKeyForVariants:(BOOL)arg4;
- (id)simulateTouch:(struct CGPoint)arg1;
- (void)changeToKeyplane:(id)arg1;
- (id)keyplaneNamed:(id)arg1;
- (id)keyplaneForKey:(id)arg1;
- (id)baseKeyForString:(id)arg1;
- (void)setPasscodeOutlineAlpha:(float)arg1;
@property(nonatomic) BOOL disableInteraction; // @synthesize disableInteraction=_disableInteraction;
@property(nonatomic) int cursorLocation; // @synthesize cursorLocation=_cursorLocation;
- (void)updateLocalizedKeys:(BOOL)arg1;
- (BOOL)isShiftKeyBeingHeld;
- (BOOL)isShiftKeyPlaneChooser;
- (BOOL)ignoresShiftState;
- (void)setReturnKeyEnabled:(BOOL)arg1 withDisplayName:(id)arg2 withType:(int)arg3;
- (float)hitBuffer;
- (BOOL)canProduceString:(id)arg1;
- (void)longPressAction;
- (void)setLongPressAction:(SEL)arg1 forKey:(id)arg2;
- (void)setAction:(SEL)arg1 forKey:(id)arg2;
- (void)setTarget:(id)arg1 forKey:(id)arg2;
- (void)updateBackgroundCorners;
- (void)restoreDefaultsForAllKeys;
- (void)didClearInput;
- (void)triggerSpaceKeyplaneSwitchIfNecessary;
- (BOOL)usesAutoShift;
- (void)setTextEditingTraits:(id)arg1;
- (unsigned int)textEditingKeyMask;
- (void)restoreDefaultsForKey:(id)arg1;
- (void)setLabel:(id)arg1 forKey:(id)arg2;
- (void)fadeWithInvocation:(id)arg1;
- (BOOL)shouldFadeToLayout;
- (BOOL)shouldFadeFromLayout;
@property(retain, nonatomic) UIKeyboardTaskQueue *taskQueue;
- (void)setAutoshift:(BOOL)arg1;
- (void)showKeyboardWithInputTraits:(id)arg1 screenTraits:(id)arg2 splitTraits:(id)arg3;
- (id)currentKeyplane;
- (BOOL)performReturnAction;
- (BOOL)canHandleEvent:(id)arg1;
@property(readonly, nonatomic) int idiom;
- (BOOL)keyplaneContainsEmojiKey;
- (id)activationIndicatorView;
- (BOOL)shouldShowIndicator;
- (struct CGSize)dragGestureSize;
- (struct CGRect)frameForKeylayoutName:(id)arg1;
@property(retain, nonatomic) NSString *layoutTag;
- (BOOL)isAlphabeticPlane;
- (BOOL)canMultitap;
- (BOOL)hasAccentKey;
- (BOOL)hasCandidateKeys;
- (void)deactivateActiveKeys;
- (void)clearTransientState;
- (void)clearUnusedObjects:(BOOL)arg1;
- (id)candidateList;
- (void)willMoveToWindow:(id)arg1;
@property(readonly, nonatomic) int orientation;
- (void)setRenderConfig:(id)arg1;
@property(retain, nonatomic) UITouch *activeTouch; // @synthesize activeTouch=_activeTouch;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setShift:(BOOL)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

