//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITextMagnifier.h>

@interface UITextMagnifierRanged : UITextMagnifier
{
    float _touchOffsetFromMagnificationPoint;
    float _magnifierOffsetFromTouch;
    BOOL _isHorizontal;
    BOOL _isAnimating;
    int _delayedAnimationType;
}

+ (id)sharedRangedMagnifier;
- (BOOL)wasPlacedCarefullyAtTime:(double)arg1;
- (int)horizontalMovementAtTime:(double)arg1;
- (struct CGPoint)clipPoint:(struct CGPoint)arg1 inRect:(struct CGRect)arg2;
- (void)updateFrame;
- (struct CGPoint)snappedPoint:(struct CGPoint)arg1;
- (float)offsetFromMagnificationPoint;
- (struct CGRect)caretRectClosestToPoint:(struct CGPoint)arg1;
@property(nonatomic) BOOL isHorizontal; // @synthesize isHorizontal=_isHorizontal;
- (void)zoomDownAnimation;
- (void)zoomUpAnimation;
- (void)remove;
- (void)zoomDownAnimationDidStop:(id)arg1 finished:(id)arg2;
- (void)zoomUpAnimationDidStop:(id)arg1 finished:(id)arg2;
- (id)initWithFrame;
- (void)setAutoscrollDirections:(int)arg1;
- (int)horizontalMovement;
- (BOOL)terminalPointPlacedCarefully;
- (void)setMagnificationPoint:(struct CGPoint)arg1;
- (void)beginMagnifyingTarget:(id)arg1 text:(id)arg2 magnificationPoint:(struct CGPoint)arg3 offset:(struct CGPoint)arg4 animated:(BOOL)arg5;
- (void)stopMagnifying:(BOOL)arg1;
- (void)dealloc;

@end

