//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class GEOPDPlaceGlobalResult, NSMutableArray;

@interface GEOPDPlaceResponse : PBCodable <NSCopying>
{
    GEOPDPlaceGlobalResult *_globalResult;
    NSMutableArray *_placeResults;
    int _requestType;
    int _status;
    struct {
        unsigned int requestType:1;
        unsigned int status:1;
    } _has;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(nonatomic) int requestType; // @synthesize requestType=_requestType;
@property(retain, nonatomic) GEOPDPlaceGlobalResult *globalResult; // @synthesize globalResult=_globalResult;
@property(readonly, nonatomic) BOOL hasGlobalResult;
- (id)initWithGeocoderPlace:(id)arg1;
@property(retain, nonatomic) NSMutableArray *placeResults; // @synthesize placeResults=_placeResults;
- (id)placeResultAtIndex:(unsigned int)arg1;
- (void)clearPlaceResults;
- (unsigned int)placeResultsCount;
- (void)addPlaceResult:(id)arg1;
- (id)_disambiguationLabels;
@property(nonatomic) BOOL hasRequestType;
@property(nonatomic) BOOL hasStatus;
@property(nonatomic) int status; // @synthesize status=_status;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

