//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <GeoServices/GEOMapRequest.h>

@class GEOZilchDecoder, NSError, NSObject<OS_dispatch_semaphore>;

@interface GEOZilchDecoderRequest : GEOMapRequest
{
    struct unique_ptr<geo::ZilchMapModel, std::__1::default_delete<geo::ZilchMapModel>> _mapModel;
    GEOZilchDecoder *_decoder;
    shared_ptr_27244a92 _message;
    CDUnknownBlockType _pathHandler;
    CDUnknownBlockType _errorHandler;
    NSError *_firstTileLoadingError;
    NSObject<OS_dispatch_semaphore> *_finishedSemaphore;
}

- (void)_finishedDecodingWithPath:(Path_7b702847)arg1;
@property(copy) CDUnknownBlockType pathHandler; // @synthesize pathHandler=_pathHandler;
- (void)decodeWithPathHandler:(CDUnknownBlockType)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (id)initWithDecoder:(id)arg1 message:(shared_ptr_27244a92)arg2;
@property(copy) CDUnknownBlockType errorHandler; // @synthesize errorHandler=_errorHandler;
- (void).cxx_destruct;
- (id).cxx_construct;
- (void)dealloc;
- (void)cancel;

@end

