//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, QLPreviewViewController, UIScreen, UISnapshotView, _UIHostedWindow;

@interface QLAirPlayController : NSObject
{
    int _mode;
    UIScreen *_screen;
    _UIHostedWindow *_airPlayWindow;
    UISnapshotView *_snapshotView;
    QLPreviewViewController *_previewViewController;
    NSTimer *_refreshTimer;
}

@property(retain) QLPreviewViewController *previewViewController;
- (void)update;
@property int mode;
@property(retain) UIScreen *screen;
- (void)invalidate;
- (void)dealloc;
- (float)_screenScaleFactorForPreviewViewController:(id)arg1;
- (float)_screenAspectRatioForPreviewViewController:(id)arg1;
- (void)_removeAirPlayWindow;
- (void)_createAirPlayWindowIfNeeded;
- (void)_updateWindowSize;
- (void)_startUsingPreviewController;
- (void)_stopUsingPreviewController;
- (void)refreshSnapshot;
- (id)initWithScreen:(id)arg1;
- (void)updateGeometryForPreviewViewController:(id)arg1;

@end

