//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreDAV/CoreDAVTask.h>

@class CoreDAVMultiStatusItem, NSSet;

@interface CoreDAVPropertyFindBaseTask : CoreDAVTask
{
    CoreDAVMultiStatusItem *_multiStatus;
    NSSet *_propertiesToFind;
}

@property(retain, nonatomic) NSSet *propertiesToFind; // @synthesize propertiesToFind=_propertiesToFind;
@property(retain, nonatomic) CoreDAVMultiStatusItem *multiStatus; // @synthesize multiStatus=_multiStatus;
- (id)parseHints;
- (id)successfulValueForNameSpace:(id)arg1 elementName:(id)arg2;
- (id)getTotalFailureError;
- (void)updateMultiStatusFromResponse;
- (id)initWithPropertiesToFind:(id)arg1 atURL:(id)arg2;
- (id)copyDefaultParserForContentType:(id)arg1;
- (void)finishCoreDAVTaskWithError:(id)arg1;
- (id)additionalHeaderValues;
- (id)description;
- (void)dealloc;

@end

