//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetWriterInputConfigurationState, AVAssetWriterInputPassDescription, AVOutputSettings, AVWeakReference, NSArray, NSDictionary, NSString, NSURL;

@interface AVAssetWriterInputHelper : NSObject
{
    AVAssetWriterInputConfigurationState *_configurationState;
    AVWeakReference *_weakReferenceToAssetWriterInput;
}

@property(copy, nonatomic) NSString *extendedLanguageTag;
@property(readonly, nonatomic) int trackID;
@property(readonly, nonatomic) NSString *mediaType;
@property(copy, nonatomic) NSArray *metadata;
- (void)markAsFinished;
@property(copy, nonatomic) NSString *languageCode;
@property(readonly, nonatomic) AVOutputSettings *outputSettings;
@property(readonly, nonatomic) int status;
@property(nonatomic) struct CGSize naturalSize;
@property(nonatomic) struct CGAffineTransform transform;
@property(nonatomic) int layer;
- (id)description;
- (void)dealloc;
@property(readonly, nonatomic) NSDictionary *trackReferences;
- (void)transitionAssetWriterAndAllInputsToFailedStatusWithError:(id)arg1;
@property(retain) AVWeakReference *weakReferenceToAssetWriterInput; // @synthesize weakReferenceToAssetWriterInput=_weakReferenceToAssetWriterInput;
- (id)associatedInputsWithTrackAssociationType:(id)arg1;
- (void)addTrackAssociationWithTrackOfInput:(id)arg1 type:(id)arg2;
- (BOOL)canAddTrackAssociationWithTrackOfInput:(id)arg1 type:(id)arg2;
- (void)markCurrentPassAsFinished;
- (BOOL)appendPixelBuffer:(struct __CVBuffer *)arg1 withPresentationTime:(CDStruct_1b6d18a9)arg2;
- (BOOL)appendSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)requestMediaDataWhenReadyOnQueue:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL shouldRespondToInitialPassDescription;
- (BOOL)canStartRespondingToEachPassDescriptionReturningReason:(id *)arg1;
@property(readonly, nonatomic) AVAssetWriterInputPassDescription *currentPassDescription;
@property(readonly, nonatomic) BOOL canPerformMultiplePasses;
@property(readonly, nonatomic, getter=isReadyForMoreMediaData) BOOL readyForMoreMediaData;
- (id)transitionToAndReturnTerminalHelperWithTerminalStatus:(int)arg1;
- (BOOL)prepareToFinishWritingReturningError:(id *)arg1;
- (void)prepareToEndSession;
- (void)didStartInitialSession;
@property(readonly, nonatomic) struct __CVPixelBufferPool *pixelBufferPool;
@property(copy, nonatomic) NSURL *sampleReferenceBaseURL;
@property(nonatomic) int preferredMediaChunkSize;
@property(nonatomic) int preferredMediaChunkAlignment;
@property(nonatomic) CDStruct_1b6d18a9 preferredMediaChunkDuration;
@property(nonatomic) BOOL performsMultiPassEncodingIfSupported;
@property(nonatomic) BOOL expectsMediaDataInRealTime;
@property(nonatomic) int mediaTimeScale;
@property(copy, nonatomic) NSDictionary *sourcePixelBufferAttributes;
@property(nonatomic) BOOL marksOutputTrackAsEnabled;
@property(readonly, nonatomic) struct opaqueCMFormatDescription *sourceFormatHint;
@property(readonly, nonatomic) AVAssetWriterInputConfigurationState *configurationState; // @synthesize configurationState=_configurationState;
- (id)initWithConfigurationState:(id)arg1;
@property(nonatomic) short alternateGroupID;
@property(nonatomic) float preferredVolume;
- (id)availableTrackAssociationTypes;

@end

